### ISSUE TITLE
Convert to SQL doesn't work with IN Clause

### ISSUE THREAD

**Issue by Davey1971** [rappen/FetchXMLBuilder#1001]
When trying to convert a FetchXML query to SQL, it fails when there is a operator "IN"

Example

<fetch top="50">
  <entity name="account">
    <attribute name="accountid" />
    <filter>
      <condition attribute="accountid" operator="in">
        <value>G999DBBB-6d9b-ed11-BBB9-0022486GG415</value>
      </condition>
    </filter>
  </entity>
</fetch>

Error message when trying to convert to SQL Query

Failed to generate SQL Query.

Unsupported SQL condition operator 'in'

**Comment by Davey1971** [comment]
Sorry, I forgot to include the Example in Code brackets

`
<fetch top="50">
  <entity name="account">
    <filter>
      <condition attribute="accountid" operator="in" uiname="Dan Test Child Account" uitype="account">
        <value>G999DBBB-6d9b-ed11-BBB9-0022486GG415</value>
      </condition>
    </filter>
  </entity>
</fetch>
`

**Comment by MarkMpn** [comment]
If you have SQL 4 CDS installed, tick the "Use SQL 4 CDS for SQL conversion" option under Options > Settings > Behavior and it should handle this conversion.

**Comment by Davey1971** [comment]
Thanks that worked

**Comment by rappen** [comment]
Thanks @MarkMpn.
I'm closing this now.
Reopen if needed!
