### ISSUE TITLE
Cannot find metadata for relation

### ISSUE THREAD

**Issue by lambeaulady** [rappen/FetchXMLBuilder#1013]
When I attempt to Convert to Power Automate Parameters, I get this message:
Cannot find metadata for relation task.ownerid =>team.teamid

It otherwise works to generate the results/FetchXML. I really like this tool but the whole reason I was using it was to generate the ExpandQuery code.

![image](https://github.com/rappen/FetchXMLBuilder/assets/86423610/6080c5a0-859c-41ef-94fd-fbacc9e70166)

<fetch>
  <entity name="task">
    <attribute name="description" />
    <attribute name="subject" />
    <attribute name="ownerid" />
    <attribute name="activityid" />
    <attribute name="createdby" />
    <attribute name="regardingobjectid" />
    <attribute name="statecode" />
    <attribute name="statuscode" />
    <filter>
      <condition attribute="statecode" operator="eq" value="0" uitype="task" />
    </filter>
    <link-entity name="team" from="teamid" to="ownerid" link-type="outer" alias="teamdetails">
      <attribute name="name" />
      <attribute name="teamid" />
    </link-entity>
    <link-entity name="teammembership" from="systemuserid" to="ownerid" link-type="outer" alias="teammembers">
      <attribute name="systemuserid" />
    </link-entity>
    <link-entity name="owner" from="ownerid" to="ownerid" alias="ownerdetails">
      <attribute name="owneridtype" />
      <filter>
        <condition attribute="owneridtype" operator="eq" value="9" />
      </filter>
    </link-entity>
    <link-entity name="knowledgearticle" from="knowledgearticleid" to="regardingobjectid" alias="articledetails">
      <attribute name="title" />
    </link-entity>
  </entity>
</fetch>

**Comment by MarkMpn** [comment]
The conversion to Web API & Power Automate parameters relies on using the defined relationships - you can't join on arbitrary attributes in the same way you can in Fetch XML. In this case the relationship is defined as being `task.owningteam >- team.teamid`, so if you use Fetch XML like:

```xml
<fetch>
  <entity name="task">
    <link-entity name="team" from="teamid" to="owningteam">
      <attribute name="name" />
    </link-entity>
  </entity>
</fetch>
```

this will convert to Web API & Power Automate parameters:

![image](https://github.com/rappen/FetchXMLBuilder/assets/31017244/d8f6a3f5-03bc-4638-82c6-ac1755ce7992)

**Comment by rappen** [comment]
@lambeaulady, do you have anything more that I should fix? Otherwise, this issue will be closed.

**Comment by lambeaulady** [comment]
It seems to be working now, thank you.
