### ISSUE TITLE
Fetch Error: Incorrect Data Type Expected

### ISSUE THREAD

**Issue by ryncdr** [rappen/FetchXMLBuilder#1014]
Filtering the audit table with ObjectTypeCode is incorrectly expecting an integer rather than string.
See [Microsoft: Web API Reference](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/audit?view=dataverse-latest) for entity definition.

The OData calls successfully using the same parameters which are failing in FetchXMLBuilder:
`https://redacted.dynamics.com/api/data/v9.2/audits?$filter=(Microsoft.Dynamics.CRM.LastXHours(PropertyName='createdon',PropertyValue=1) and objecttypecode ne 'systemuser')&$top=50`

---
```
System.ServiceModel.FaultException<Microsoft.Xrm.Sdk.OrganizationServiceFault>:
An exception System.FormatException was thrown while trying to convert input value '[REDACTED]' to attribute 'audit.objecttypecode'. Expected type of attribute value: System.Int32. Exception raised: Input string was not in a correct format.
FetchXML Builder

Server stack trace: 
- System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
- System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
- System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
- System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
- Microsoft.Xrm.Tooling.Connector.CrmServiceClient.RetrieveMultiple(QueryBase query)
- Rappen.XTB.FetchXmlBuilder.FetchXmlBuilder.RetrieveMultiple(QueryBase query, Boolean allrecords)
- Rappen.XTB.FetchXmlBuilder.FetchXmlBuilder.<>c__DisplayClass125_0.<RetrieveMultiple>b__0(BackgroundWorker worker, DoWorkEventArgs eventargs)
- System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
- System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

---

```
<fetch top="50">
  <entity name="audit">
    <filter type="and">
      <condition attribute="createdon" operator="last-x-hours" value="1" />
      <condition attribute="objecttypecode" operator="ne" value="systemuser" />
    </filter>
  </entity>
</fetch>
```
---
- XrmToolBox Version: 1.2023.12.68
- FetchXML Builder Version: 1.2023.11.1
- DB Version: 9.2.23123.240
- Deployment: Online

**Comment by rappen** [comment]
The `ObjectTypeCode`  columns are often fishy... 
I'll try to find a good/better solution to this and similar issue.

**Comment by rappen** [comment]
The problem here was that this attribute was filtered out, and FXB can't know which type of attribute it is, therefore it would not convert it to the ETC.
This explains how to show that attribute:
https://app.screencast.com/adZNg3sBM4LvE

**Comment by rappen** [comment]
For the next version, it can also handle attributes filtered out.
Thanks for your report! 🤓

**Comment by ryncdr** [comment]
Ah-ha! Thank you for the solution and explanation!
