### ISSUE TITLE
Fetch XML Builder does not retain the correct table if there are multiple entities with the same display name.

### ISSUE THREAD

**Issue by AzzaTsy** [rappen/FetchXMLBuilder#1015]
In our implementation we have renamed the standard account table to 'entity'.

Upon selecting a table in the query builder and with the fetch XML open we can see the schema name of the table, below are the options our system.

-DisplayName: Entity, Schema Name: entity
-Display Name: Entity, Schema Name: msdyn_entityroutingconfiguration
-Display Name: Entity, Schema Name: account

<img width="720" alt="FetchXml Builder Bug with Accounts" src="https://github.com/rappen/FetchXMLBuilder/assets/159731887/5aff87ae-b89a-46f5-99cc-8eeab4296181">

After making our selection for account then trying to select columns or adding a filter in the query builder window, it seems to revert back to the first table with the display name of 'Entity' and were unable to select columns from the account table.

D365 system allows for the same display names on tables if that is what it is getting confused about. The work around I have discovered is to disable friendly names or filter by your solution.

![image](https://github.com/rappen/FetchXMLBuilder/assets/159731887/5f5cefd2-2560-4599-b65f-1ed8e65a90d6)

**Comment by rappen** [comment]
Oh, I see that issue...!
I'll try to find a good solution that can make it very clear which table (and columns) you are really working on.

Thanks for the info!

**Comment by rappen** [comment]
Added an option to show both DisplayName and LogicalName:

![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/7144f803-ca79-418a-9adb-c0d5245f0e42)

![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/49282554-b091-4cc0-b620-e0fdaba5d4d2)
