### ISSUE TITLE
Linked Entities not displaying in results because selected attributes are not added to the Layout

### ISSUE THREAD

**Issue by kayetter** [rappen/FetchXMLBuilder#1040]
This seems different to me. I have an entity for which I added several linked entities (and I aliased them) and added the attributes that i wanted displayed in the results. I was expecting to see the linked entity attributes in the result grid but I see this.

![image](https://github.com/rappen/FetchXMLBuilder/assets/22959546/e727841e-b43f-453a-8075-7b10227a65d3)

However, when I go to the "layout" tab I see that my selected attributes are not there.

![image](https://github.com/rappen/FetchXMLBuilder/assets/22959546/d6be91ad-a01f-4214-85fc-4cc42fc8aac8)

I then have to add them manually to the Layout tab.
![image](https://github.com/rappen/FetchXMLBuilder/assets/22959546/ef0c1447-b51c-4320-b72d-2741f2e16e82)

Then I see them in the results view.
![image](https://github.com/rappen/FetchXMLBuilder/assets/22959546/77622c2e-82a0-4310-ab25-54b35a0a48ef)

Is this how it is supposed to work or do I have a setting that is wrong?

**Comment by rappen** [comment]
Thank you so much for this report! 🙏

1. You say you use Alias on `link-entity`, but in the screenshots, I don't see any aliases.
2. Can you look at the Attribute properties? Can you check the layout checkbox and set the width?
3. Is it possible to include the query in XML?

**Comment by kayetter** [comment]
Sure. Here is the XML but I don't see a "Layout" check box. I only see the layout tab.

```
<fetch top="50">
  <entity name="slp_test">
    <attribute name="slp_name" />
    <attribute name="slp_testid" />
    <attribute name="vet_patient" />
    <attribute name="slp_testcode" />
    <filter>
      <condition attribute="statecode" operator="eq" value="0" />
    </filter>
    <link-entity name="slp_testcode" from="slp_testcodeid" to="slp_testcode" alias="slp_testcode">
      <link-entity name="team" from="teamid" to="owningteam" link-type="inner" alias="owningteam">
        <attribute name="name" />
        <filter>
          <condition attribute="name" operator="eq" value="POCT" />
        </filter>
      </link-entity>
    </link-entity>
    <link-entity name="vet_patient" from="vet_patientid" to="vet_patient" alias="vet_patient">
      <attribute name="vet_name" />
      <attribute name="vet_medicalrecordnum" />
      <attribute name="vet_name2" />
      <attribute name="vet_name3" />
      <attribute name="vet_breed" />
    </link-entity>
  </entity>
</fetch>
```
