### ISSUE TITLE
FetchXML Timeout

### ISSUE THREAD

**Issue by BobCapel** [rappen/FetchXMLBuilder#1042]
There used to be an option in XRMToolbox to change the time out for FetchXML queries. I can't find that option now. Has that been removed? Is there a way to extend the time out for long-running queries?

**Comment by rappen** [comment]
Very short to show how to do it:
https://app.screencast.com/B3BTL5EyeVjpM

**Comment by BobCapel** [comment]
Awesome. Thanks a ton!

Bob Capel
Dynamics 365 and Power Platform Engineer
Altigen Technologies
[cid:b27dafef-c4dc-48f4-94d5-192d9a217338]
***@***.***?anonymous&ep=signature>                Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________
