### ISSUE TITLE
Dates 

### ISSUE THREAD

**Issue by jpvj** [rappen/FetchXMLBuilder#1045]
Hi,

It seems as the date files now currupts the date content by formatting it as local timestamps and not ISO 6301. It happens as soon as you leave the "Date / Time" text box:

![image](https://github.com/rappen/FetchXMLBuilder/assets/38222864/8c95a29d-809d-4e9f-89bb-ffd7c6651d2e)

This is rather critical :-o 

Best regards,

Jens-Peter

**Comment by rappen** [comment]
That's bad...
Have you tried using the general format, yyyy-mm-dd ? Will it break bad that too?

**Comment by jpvj** [comment]
Yes. It happens as soon as you click the condition in the treeview:

![image](https://github.com/rappen/FetchXMLBuilder/assets/38222864/eef5d83b-6565-47f8-ab56-ecb631ac7c36)

**Comment by jpvj** [comment]
If you click "Enter text" it's possible to correct it or overwrite it directly in the FetchXML editor.

**Comment by rappen** [comment]
For the next release, I have now forced ISO 8601 so no one can ever misunderstand which date we are actually meaning. I've tested it back and forth, and it looks to work fine.
(I binged about ISO 6301 that you wrote, but that only shows me something about "Pneumatic fluid power"... 🤔)

If you have any more feedback or thoughts - please send it!

**Comment by jpvj** [comment]
Hi Jonas,

Sounds great – I have been using the previous version ever since due to the problem, so I’m ready to test the new version!

I have no idea why I wrote ISO 6301 … Let’s stick to ISO 8601 😉

/JP

Fra: Jonas Rapp ***@***.***>
Sendt: 15. august 2024 10:39
Til: rappen/FetchXMLBuilder ***@***.***>
Cc: Jens-Peter Vraa Jensen ***@***.***>; Author ***@***.***>
Emne: Re: [rappen/FetchXMLBuilder] Dates (Issue #1045)


For the next release, I have now forced ISO 8601 so no one can ever misunderstand which date we are actually meaning. I've tested it back and forth, and it looks to work fine.
(I binged about ISO 6301 that you wrote, but that only shows me something about "Pneumatic fluid power"... 🤔)

If you have any more feedback or thoughts - please send it!

**Comment by jpvj** [comment]
Thank you very much!

Any eastimate on next release?
I noticed you've fixed some bugs here and there :-)

**Comment by rappen** [comment]
"Soon..."
A week or so.
