### ISSUE TITLE
Visulize time elapsed

### ISSUE THREAD

**Issue by ChriPalm** [rappen/FetchXMLBuilder#1046]
Hi there

As you already know, I'm a big fan of your apps whitin XRM toolbox. 
I would find it most useful to se the output of how many seconds/minutes/hours/years/decades .. ok.. at least seconds/minutes a query take to run in FetchXML Builder and sometimes Bulk Data Updater.

I'm sometimes work with large datasets and would like to see the impact if I construct the FetchXML query in different ways!

Keep up the good work!

Best regards

Christian 

---
- Deployment: Online
- DB Version: 9.2.24044.212
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68
- Tool Version: 1.2024.5.2

**Comment by rappen** [comment]
Example:

![image](https://github.com/user-attachments/assets/5addaebe-996f-4245-b9e6-6d2239435cfb)
