### ISSUE TITLE
Last Name won't display?

### ISSUE THREAD

**Issue by daryllabar** [rappen/FetchXMLBuilder#1048]
Weird behavior with names and some sort of caching.

Run this query first:
``` xml
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="contact">
    <attribute name="fullname" />
    <filter>
      <condition attribute="lastname" operator="eq" value="Smith" />
    </filter>
  </entity>
</fetch>
```

Looks good:
![image](https://github.com/rappen/FetchXMLBuilder/assets/9728423/52d727a9-168d-41d3-8028-8aed0c881878)

Then update fullname to lastname and run again ( I hand typed it in the xml window, not sure if it matters):
``` xml
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="contact">
    <attribute name="lastname" />
    <filter>
      <condition attribute="lastname" operator="eq" value="Smith" />
    </filter>
  </entity>
</fetch>
```

I get this result with no last name or full name:
![image](https://github.com/rappen/FetchXMLBuilder/assets/9728423/18641775-4899-49c4-a942-eedc93832b78)

But if I add in the full name, it returns correctly, but then if I remove the fullname, the full name is still shown in the grid, but empty...

**Comment by rappen** [comment]
Most likely it happens when you change attributes to return.
In the second, you ask for the lastname, but it shows fullname. Which is a bug, too well known.
If you go to the low-menu, select Columns and Show All. Now you see lastname, I hope.
