### ISSUE TITLE
Failed to generate SQL Query.  Unsupported SQL condition operator 'notbeginwith'

### ISSUE THREAD

**Issue by jpvj** [rappen/FetchXMLBuilder#1054]
Hi!

I just tried to convert FetchXML til SQL and faced this "error".

I should be easy to support notbeginwith by converting it to NOT LIKE '[match]%'  :-)

Cheers!

**Comment by rappen** [comment]
There we go! 😊

![image](https://github.com/user-attachments/assets/96dd9e97-a7c0-4221-933c-bae1aa0c7f71)

Stay tuned for the next release...
