### ISSUE TITLE
Layout XML possibly invalid when using aggregations on linked table

### ISSUE THREAD

**Issue by taylordgordon** [rappen/FetchXMLBuilder#1057]
This view (made by FetchXMLBuilder) does not show correctly in the UI... maybe it has to do with my link-entities or the aggregation?

FetchXml from the builder:
`
<fetch aggregate="true" output-format="xml-platform" savedqueryid="0ca720b0-4949-ef11-a317-7c1e52153b73">
  <entity name="contact">
    <attribute name="entityimage_url" alias="imageurl" groupby="true" />
    <attribute name="statecode" alias="statecode" groupby="true" />
    <attribute name="fullname" alias="FullName" groupby="true" />
    <attribute name="mobilephone" alias="Phone" groupby="true" />
    <attribute name="emailaddress1" alias="Email" groupby="true" />
    <attribute name="contactid" alias="ContactId" groupby="true" />
    <filter type="and">
      <condition attribute="ownerid" operator="eq-userid" />
      <condition attribute="gcrm_contacttype" operator="eq" value="321670001" />
    </filter>
    <link-entity name="gcrm_mortgageparticipant" from="gcrm_participant" to="contactid" link-type="inner" alias="mp">
      <link-entity name="gcrm_mortgage" from="gcrm_mortgageid" to="gcrm_mortgage" link-type="inner" alias="mtg">
        <attribute name="gcrm_mortgageid" alias="LoansClosed" aggregate="count" />
        <attribute name="gcrm_closingdate" alias="LatestCloseDate" aggregate="max" />
        <filter>
          <condition attribute="gcrm_pipelinestage" operator="eq" value="321670013" />
        </filter>
        <order alias="LoansClosed" descending="true" />
      </link-entity>
    </link-entity>
  </entity>
</fetch>
`

LayoutXML from the builder:
`<grid name="resultset" object="2" jump="fullname" select="1" icon="1" preview="1">
  <row name="result" id="contactid">
    <cell name="FullName" width="100" />
    <cell name="Email" width="100" />
    <cell name="Phone" width="100" />
    <cell name="LoansClosed" width="100" />
    <cell name="LatestCloseDate" width="100" />
    <cell name="imageurl" ishidden="1" />
    <cell name="statecode" ishidden="1" />
    <cell name="ContactId" ishidden="1" />
  </row>
</grid>`

What is shown in interface:
![image](https://github.com/user-attachments/assets/163d22ff-2623-4c60-a0cf-6861d52226a1)

The query returns data and is perfect in FetchXMLBuilder.  I can see the data returned to the browser in devtools, but it won't display in UI.

If I change the layoutXML manually to the logical names of the group-by attributes, the column names do show up - but still no data rows appearing.  Regardless, I am still unsure how to properly refer to my two aggregate columns "LoansClosed" and "LatestCloseDate".
![image](https://github.com/user-attachments/assets/9d692bc3-e38f-4d5e-b8e1-61e8e89c184b)

Resulting in this, despite there being 1 row evident in browser devtools:
![image](https://github.com/user-attachments/assets/499b4017-a5fb-4167-ad93-6150ea0bf28d)

**Comment by rappen** [comment]
Maybe I've been offline too long, but to my knowledge, the aggregate queries are not allowed (or not supported) in Views.
Am I wrong? If so, can you send me a link to MS Docs? I want to learn... :)

**Comment by taylordgordon** [comment]
I am pretty sure you are not wrong Jonas, I tried a lot of things without success, and can't find any documentation saying it is supported.  It would be handy though, so we can do simpler aggregations in Views without PBI.  Probably a risk to performance though.

Cheers!
