### ISSUE TITLE
Setting date column to 'Enter text' changes back to 'Use DatePicker'

### ISSUE THREAD

**Issue by Roland80** [rappen/FetchXMLBuilder#1060]
When you've added a date/time column in a filter condition and choose to manually enter the text by setting the radio button to 'Enter text', the radio buttons change back to 'User DatePicker' after selecting something else in the Query Builder and re-selecting the date/time column's condition.
This behavior is also observed after manually editing the FetchXML and clicking the OK-button. It seems to be related to the refreshing of the Node Properties pane, as the pane briefly 'flashes' after saving the manual change(s).

This is in FetchXML Builder version 1.2024.4.1

**Comment by rappen** [comment]
Thanks for your report!
Fixed in next release.
