### ISSUE TITLE
Separating or re-docking tab causes loss of data

### ISSUE THREAD

**Issue by Roland80** [rappen/FetchXMLBuilder#1061]
Observed in FetchXML Builder version 1.2024.4.1:
When pulling a tab from the main XrmlToolBox window, for example to place on a second screen, the created query is los:
![image](https://github.com/user-attachments/assets/801c13c5-91f4-4673-b263-29fe9df3f484)
becomes
![image](https://github.com/user-attachments/assets/cbe7b96f-0919-4075-8ad6-efe33d07a52f)

The exact same happens when a separated tab is placed back in the main window:
![image](https://github.com/user-attachments/assets/48ccbb8b-f270-4536-8c4e-1ba651d314ca)
becomes 
![image](https://github.com/user-attachments/assets/2ae61a81-3b9f-4e50-83c3-7d8c985a3f37)

**Comment by rappen** [comment]
I'm annoyed about that, too...
Will try to fix it.
