### ISSUE TITLE
Fetch all pages when top or paging info is given

### ISSUE THREAD

**Issue by Rasmus-Petersen-RLL-Sampension** [rappen/FetchXMLBuilder#1065]
Hi Jonas

Another problem when I omit top or page limits on a query FetchXmlBuilder begins fetching all pages. This is terribly annoying.
Can this be disabled or possibly add a "Fetch all pages" checkbox where one is entering paging information.

This new checkbox MUST be unchecked for ALL new queries, to minimize the risk of lengthy queries being run against Dataverse.

**Comment by rappen** [comment]
I know, and I'm sorry... ugly stuff. See #1047 if you want to see how.
It was fixed at the beginning of the summer, I'm now working my *ss off to publish a new release asap!
