### ISSUE TITLE
[Feature Request] Add Bypass Plugin Execution option to settings 

### ISSUE THREAD

**Issue by killerrin** [rappen/FetchXMLBuilder#1066]
Would it be possible to add an option to the settings under "Behavior" to Bypass Plugin Execution?

There are some usecases (for us, this usecase would be to operate a Translation Plugin on Code Tables) where individuals may register a synchronous/asynchronous plugin that executes on the Retrieve or Retrieve Multiple messages. And without having this capability it would result in the system taking longer to return data in scenarios where execution could be safely bypassed.

Some developers may also utilize the Bypass feature within plugins for data retrievals in contexts which are performance sensitive. And as a result by not having this built into the FetchXML builder would result in not being able to accurately assess how long a given query might take to run.

Thanks!

**Comment by rappen** [comment]
I never thought about that - but it's a great request!

**Comment by rappen** [comment]
Does this looks nice?
https://app.screencast.com/Vlg4btefGMJYV

**Comment by killerrin** [comment]
That looks perfect. That'll make it much easier to benchmark some of our plugin-bypassed queries.

Thanks for taking the time to do this!
