### ISSUE TITLE
Exception when switching to the Excel tab

### ISSUE THREAD

**Issue by Paul-CONSOS** [rappen/FetchXMLBuilder#1068]
[Write any error info to resolve easier]

---
```
System.Runtime.InteropServices.COMException:
Unable to set the FreezePanes property of the Window class
FetchXML Builder
   bei System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   bei Microsoft.Office.Interop.Excel.Window.set_FreezePanes(Boolean )
   bei Rappen.XTB.FetchXmlBuilder.DockControls.ResultGrid.OpenInExcel()
```

---
- XrmToolBox Version: 1.2023.12.68
- FetchXML Builder Version: 1.2024.9.3
- DB Version: 9.2.24074.216
- Deployment: Online

**Comment by rappen** [comment]
Thanks for the report, @Paul-CONSOS 
Do you know if this occurs every time, now and then, or only once?

**Comment by Paul-CONSOS** [comment]
@rappen this occurs every time. The Excel file is generated, but the exception is still there
![image](https://github.com/user-attachments/assets/c1568a26-d4aa-463a-ae48-444ba3e86ab9)

**Comment by rappen** [comment]
It seems like something breaks before creating the sheet "FetchXML Builder - Source".
Wonder why... Thanks for this info!
