### ISSUE TITLE
Filter condition for string type should support all valid operators

### ISSUE THREAD

**Issue by jhwkendall** [rappen/FetchXMLBuilder#1070]
The drop down list of conditions for string fields is missing the operators 'ge', 'gt', 'le', and 'lt'. If a condition in the FetchXML pane is edited to use one of these operators, they don't stick, they are changed to 'eq' by the XML validation logic. The operators are valid for strings according to
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/fetchxml/reference/operators#string-data:~:text=Use%20the%20following%20operators%20in%20conditions%20using%20string%20values.

**Comment by rappen** [comment]
Good point! I will fix it.
