### ISSUE TITLE
Easier switch between result view types

### ISSUE THREAD

**Issue by jhwkendall** [rappen/FetchXMLBuilder#1071]
I often find myself switching between result grid view and the json (web api format) view. It would be nice if it could be done in one or two mouse clicks instead of the seven it requires now. The number of view switches could be reduced if the grid view cell data could be copied to the clipboard. Often, the only need to switch to the json view is so data can be copied.

**Comment by rappen** [comment]
Another good point.
Do you have a favorite shortcut sequence for it?

**Comment by rappen** [comment]
Looking good?

![image](https://github.com/user-attachments/assets/6633b053-0c30-4025-95b2-b97e4eaa9063)

**Comment by rappen** [comment]
Added Friendly/Raw/Both to the menu too.

![image](https://github.com/user-attachments/assets/159759d6-2628-4930-a93a-73940182c324)
