### ISSUE TITLE
Version 1.2024.9.3 - reconnecting resets all existing open FXB tabs to the same query.

### ISSUE THREAD

**Issue by mtnmuncher** [rappen/FetchXMLBuilder#1077]
1. I left work yesterday with 6 active FXB windows.
2. this morning, I clicked connect to refresh my connection.
3. selected 'all tabs'.
4. all 6 query windows contain the query from the first window.

### this is the first window
![image](https://github.com/user-attachments/assets/df8cc69e-85bc-49b8-abe2-bd5f383d3fe2)

### Second window 
![image](https://github.com/user-attachments/assets/606f4aad-dcaa-4429-8224-5c5cee91117b)

**Comment by rappen** [comment]
Aouch, that's a bad "new feature"... 🫣
I will fix it for the next release.
Thanks for your detailed report! 🙏

**Comment by rappen** [comment]
It will now never try to reload the last query if updated to the same connection.
