### ISSUE TITLE
Could not load file or assembly 'NuGet.Packaging, Version=5.9.1.11

### ISSUE THREAD

**Issue by azeemnawaz12** [rappen/FetchXMLBuilder#1093]
Hello,

Recently i have updated the FetchXML builder tool and started getting this error. Please advise the fix!

![image](https://github.com/user-attachments/assets/2f7a1a65-1b89-46a8-aac0-27f19b85413d)
[FetchXML_Load_Error.txt](https://github.com/user-attachments/files/18057517/FetchXML_Load_Error.txt)

**Comment by azeemnawaz12** [comment]
Hello, quick update. I uninstalled and reinstalled the FetchXML Builder tool and the issue was resolved!

**Comment by rappen** [comment]
I guessed so - the version you were using seems quite old...
My tip is - always accept to update tools when available! 😉
