### ISSUE TITLE
Support data pre-filtering attributes

### ISSUE THREAD

**Issue by davidlb** [rappen/FetchXMLBuilder#116]
I use FetchXML builder to build my FetchXml query to use in my reports. It would be nice to support the 2 data pre-filtering attributes : https://technet.microsoft.com/en-us/library/dn531099(v=crm.7).aspx#Fetch_basedPre_filtering

Thanks!

**Comment by rappen** [comment]
Good idea!
Will have a look at that, unless you feel like contributing...? ;)

**Comment by mscottsewell** [comment]
Oh yeah.  +1

**Comment by rappen** [comment]
Does anyone have any idea where this is defined?
The [fetch.xsd schema](https://msdn.microsoft.com/en-us/library/gg309405.aspx) does not appear to support it, so validation of a pre-filtered query against the schema would fail.

**Comment by mscottsewell** [comment]
I've reached out to the team to ask. Will let you know what I find.

> In FetchXML for SSRS reporting we can use prefiltering by adding options to the FetchXML query: https://technet.microsoft.com/en-us/library/dn531099(v=crm.7).aspx#Fetch_basedPre_filtering 
> 
> However those extensions aren’t documented in the fetch.xsd schema and consequently, validation of a correctly built pre-filtered query against the documented schema would always fail.
> 
> Is there an XSD that includes the prefiltering options as valid?

**Comment by rappen** [comment]
:+1:

**Comment by mscottsewell** [comment]
Jim D. has confirmed and submitted it to the team as a bug in the documentation - it will be a few months before it completes the cycle and arrives in the published XSD - until then I would assume it's a 'known limitation' - (or you can override/edit the XSD yourself to allow for the exception.)

**Comment by davidlb** [comment]
Ok, thanks :)

**Comment by scottdurow** [comment]
For me - probably the biggest use I have for the FetchXml Builder is authoring queries for reports - so I'd really like it just strip out these attributes when running the query.

**Comment by rappen** [comment]
Jim D confirmed it is now fixed in the XSD and docs for v9 updated, so it should be possible to implement this with the tech supporting it!
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/org-service/fetchxml-schema

**Comment by rappen** [comment]
This is my oldest open issue... Time to implement it, or just close it!

I think my first Q goes back to @jimdaly:
From the very old [un-updated docs](https://learn.microsoft.com/en-us/previous-versions/dynamicscrm-2015/deployment-administrators-guide/dn531099(v=crm.7)?redirectedfrom=MSDN#enabling-data-pre-filtering-in-fetch-based-reports) it says that `entity` node can have more parameters: `enableprefiltering="1" prefilterparametername="CRM_FilteredAccount"`.
I can't see that in the updated docs, no info about that today. Is it still working? Should it work?

A more general Q to all of you commenting here - is that feature still used? Or is Power BI using other ways to solve it? Sorry, but this is not my forte... Ping @davidlb @mscottsewell @scottdurow

**Comment by mscottsewell** [comment]
From the Power BI perspective - I'm no longer querying Dataverse with FetchXML. #FabricEverything!

The number of users building SSIS reports for embedding in model driven Power Apps / D365 - where the prefiltering attributes are used - that population of SSIS makers is getting smaller (and **_definitely getting much older_**) than it was when this was a hot issue.

**Comment by davidlb** [comment]
Hi guys, sorry I moved to Salesforce few years ago.

**Comment by JimDaly** [comment]
I worked with the data engine team to review all the parameters that are relevant for invoking RetrieveMultiple. 
We examined the XSD and found that it wasn't the source of truth I thought it was. Seems no one used or maintained it, so we stopped publishing it. It is replaced by this [FetchXml Reference](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/fetchxml/reference) that is focused on using RetrieveMultiple in code. We removed all other attributes that were introduced for other scenarios, such as views in model-driven apps and reporting.  They may still be valid, but aren't part of our core scenarios around using FetchXml with SDK FetchExpression or OData.

So, the [Improve report performance by using filters](https://learn.microsoft.com/en-us/dynamics365/customerengagement/on-premises/analytics/improve-report-performance-by-using-filters) is the only documentation about these attributes.  I don't expect that there will be any changes here.

While this is still mentioned in older docs for the on-premises product, as @mscottsewell said, there seem to be better options these days for Dataverse.

**Comment by rappen** [comment]
Thanks to @JimDaly and @mscottsewell!
And I'm sorry to hear that, @davidlb 🫣 Welcome back, when you are ready.

I missed to add the link to [reference of entity](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/fetchxml/reference/entity), and that there are no such attributes anymore. I totally accept/agree with what should be included in the docs.

So, I guess this should just be closed. Moving on, the future is bright! 😎
