### ISSUE TITLE
Optionsets should be selectable from dropdowns for "in" and "not-in"

### ISSUE THREAD

**Issue by rajyraman** [rappen/FetchXMLBuilder#118]
When I build "in" and "not-in" condition against an optionset attribute, there is no dropdown to assist with selecting the correct integer value. This behaviour is different when I use "eq" condition. In this case a drop down is displayed with all the valid optionset values.

The other option is to have a right click menu item on "in" and "not-in" conditions called "values" only for optionsets. When this is selected, all valid optionset values are displayed with checkboxes in a popup window (like entity->select attributes). The selection can then be converted into the condition->value nodes.

**Comment by rappen** [comment]
Fixed, long ago (I think...)
