### ISSUE TITLE
Generate WebAPI url

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#123]
Just like function #4 FXB should be able to generate corresponding WebAPI url.
It should be possible to both generate query using the FetchXML query type and "native REST".

**Comment by rappen** [comment]
Related to #124

**Comment by mscottsewell** [comment]
Integrating CRM with PowerBI & Flow could benefit from this.

**Comment by ghurlman** [comment]
For anyone taking this on... take a look at the API requests made by a lookup control when doing a lookup search in UCI/model-driven PowerApps. The FetchXML is passed along as a parameter to the API, so this _should_ be ezpz. Note that multilookups do a batch request, but that isn't strictly necessary.

If this isn't picked up by someone during the workday today, I'll try to take a look tonight (no guarantees)

**Comment by rappen** [comment]
Thanks @ghurlman,
Also note that the wireframing is already initiated in branch WebAPI:
https://github.com/rappen/FetchXMLBuilder/tree/WebAPI

The "only" thing that remains is the actual WebAPI query generation.... menu option, display window etc should already be there.
