### ISSUE TITLE
Implement optional caching of FetchXML results

### ISSUE THREAD

**Issue by shytikov** [rappen/FetchXMLBuilder#130]
It would be nice to have some well controlled memory caching to `FXB`.

For example, if same request was issued within one or two minutes after completely identical one, we can assume, that results will not differ, so why not use cached values, you already fetched two minutes ago?

But.

In any case it would be great to have a label, that will inform user, that result was taken from cache and a button, to delete cache for that request and request new result.

Or provide advanced settings, like for `activity` records cache should be not more than 30 seconds (since they could change often), for example, but for account we can have like 30 minutes cache easily (probably accounts not added that often for some customers), etc.

We could also made caching a bit intellectual. If a filter condition was changed — we should abandon cache 100%, if attribute was added — we should abandon 100%, but if attribute was removed... we could use previous results, but hide fields not needed anymore...

**Comment by rappen** [comment]
I think this is not relevant for FXB at all.
FXB is a tool for development and testing, not an alternate UI for CRM.
Unless a good developer-centric argument is made, I will close the issue.

**Comment by shytikov** [comment]
Exactly.

I'm was talking from developer prospective. Sometimes I just don't care do the results are actual results or not. I'm quite OK with the fact, that my request succeeded and contains correct information exactly now, at the moment when I finished it. 

If I closed results window because I started working with another query and if I would love to have my previous results once again, to verify, for example, value of some field. I don't want to wait for actual results, which in case of development server in 99,99% cases would be the same as 10 minutes ago.

I believe caching could be helpful and could speed up development, if it's done smart.

**Comment by shytikov** [comment]
Supplementary idea:

For first call always request values for all fields. Cache them, and when user will add or remove attributes from query, not re-execute query, but remove or add fields from already cached result. 

This could help avoid unnecessary delays when debugging query.

**Comment by rappen** [comment]
The whole point of FXB is to develop and test queries.
Faking subsequent calls and instead showing cached data really makes no sense to me.
How could you debug a query if the query is not executed?

**Comment by shytikov** [comment]
You're definitely right, but sometimes this `REPL` (read–eval–print loop) process is slow either because of query complexity or network delays. I believe we could involve some caching to make it more responsive for user.

How about following: if no conditions was changed, or attributes removed — present user cached result right away, but execute actual call in background, if results are different, update windows with actual data. 

Execution delays will be hidden, and for user, visually, tool will be working faster. Web-sites do this all the time to compensate network latency.
