### ISSUE TITLE
DataGridView extra export compatibilities

### ISSUE THREAD

**Issue by shytikov** [rappen/FetchXMLBuilder#132]
When you copy data from `DataGridView` for some reason columns headers are not copied.

It would be nice to control that behavior — either include it to result or not.

Maybe it would be possible to export data to excel spreadsheet also (in future)?

**Comment by rappen** [comment]
This is only 8+ years old...
I'll keep #801 open, and now closing this one.
It can (since ages) be copied including or excluding headers by a setting.
