### ISSUE TITLE
Entity name autocompletion via [Tab] key gives only not-manually-written but auto-completed part of entity name

### ISSUE THREAD

**Issue by myfairsyer** [rappen/FetchXMLBuilder#146]
![fxbi1](https://cloud.githubusercontent.com/assets/13559472/20092008/18c19332-a596-11e6-8639-c6c21005ff68.png)

![fxbi2](https://cloud.githubusercontent.com/assets/13559472/20091863/4abadd7c-a595-11e6-9f09-a0943cb27e49.png)

![fxbi3](https://cloud.githubusercontent.com/assets/13559472/20091865/4abf2b20-a595-11e6-8dd6-c0173e0bc575.png)

**Comment by rappen** [comment]
I see that sometimes too....
Extremely annoying, something in the standard combobox control.
If you have any clues to overcoming this behavior they are most welcome :)

**Comment by rappen** [comment]
I truly believe this is fixed after a lot changes in the UI since this lovely old UI streenshots.
I'm closing this issue now.
