### ISSUE TITLE
Distinct on attribute

### ISSUE THREAD

**Issue by Oztrea** [rappen/FetchXMLBuilder#175]
In fetchxml it's possible to do a countcolumn and distinct on attribute.
With fetch xml builder the parser gives an error: "The distinct attribute is not declared".

see https://msdn.microsoft.com/en-us/library/gg309565.aspx#Anchor_3 (count distinct column)
Ex:
```
<fetch distinct='false' mapping='logical' aggregate='true'> 
    <entity name='opportunity'> 
       <attribute name='name' alias='opportunity_distcount' aggregate='countcolumn' distinct='true'/> 
    </entity> 
</fetch>
```

So, we build the query with fetchxml builder and we can't run it, we have to run it with fetchxml tester :)

**Comment by rappen** [comment]
Thanks, I will have a look at that!
There is one way to run it in FXB without validation: open the query editing window and hit the Execute button. This is for testing "semi supported" queries, and should probably work for you in this case :)

**Comment by Oztrea** [comment]
Thank you Jonas :)

**Comment by rappen** [comment]
The fetch.xsd schema has been updated to latest version, can you verify if this is still a problem? Ping @Oztrea

**Comment by rappen** [comment]
Duplicate with #206, soon to be released.
