### ISSUE TITLE
Access the recordid in result grids

### ISSUE THREAD

**Issue by PerHolgerssonAtInnofactorcom** [rappen/FetchXMLBuilder#179]
Suggestion 1
If a recordid attribute is explicitly given in the fetch statement, this should override the setting in the "Display options" menu in the grid form.

Suggestion 2
Please let the "Display options" settings remember my choices when I open a new window

**Comment by rappen** [comment]
RE Suggestion 2: It *should* remember your preferences! Can you verify that it does not? Note that most settings are stored per connection.

**Comment by rappen** [comment]
Closing for now, feel free to reopen if necessary!
