### ISSUE TITLE
Convert from QueryExpression code to FetchXML

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#195]
Per request from @KhashRastin :

Add the possiblity to reverse engineer C# QueryExpression code to FetchXML.
The code should be "interpreted" and then execute a [QueryExpressionToFetchXmlRequest](https://docs.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.queryexpressiontofetchxmlrequest) to get the corresponding FetchXML.

**Comment by carfup** [comment]
If i manage to make roslyn work in my new plugin, i might be able to answer that request with it !

**Comment by rappen** [comment]
Awesome! 🤓

**Comment by rajyraman** [comment]
Even with Rosyln and parsing the syntax tree, I think it easier to pass the queryexpression as-is to _QueryExpressionToFetchXmlRequest_ and use the response.

**Comment by rappen** [comment]
I think the trick is that you don't have the `QueryExpression` object, only the text representation of the code. So that text has to be "interpreted" as code to instantiate the object to send to `QueryExpressionToFetchXmlRequest`.
Or am I missing something?

**Comment by carfup** [comment]
Well as said Jonas, you need to interpret the "string" you receive as the QueryExpression object in order to use it with the Request. So far, i managed to do this with Roslyn in a simple console app, working fine. But didn't find out if there was an easier solution. And my next challenge is to ILMerge all of this in one single DLL which is not working at all so far :)

**Comment by rajyraman** [comment]
That sounds exciting @carfup.

**Comment by BetimBeja** [comment]
Hello @rappen ,
I think I have a solution for this, the only problem I have to solve right now is where to place the code which does the conversion. I was thinking to put it in [QueryExpressionCodeGenerator.cs](https://github.com/rappen/FetchXMLBuilder/blob/36027002f88c0e05549b2c2da23346c83ce73f8a/FetchXmlBuilder/AppCode/QueryExpressionCodeGenerator.cs). And I still have to figure out the best way to add the action which does the conversion to the QueryExpression view.

I will start with a PR where I will add a function to the class which handles compiling and the request to the IOrganizationService and later I can improve the PR by calling the function in the QueryExpression view.

Best regards,
Betim.
