### ISSUE TITLE
Don't Allow Fields that aren't readable

### ISSUE THREAD

**Issue by daryllabar** [rappen/FetchXMLBuilder#201]
So I created a query for the Workflow Entity, and did a select, and checked all attributes.  It gave an error with an attribute that is not valid for reads.  This should be filtered so a user can't select it.

**Comment by rappen** [comment]
Did the error occur when this checkbox was checked?

![image](https://user-images.githubusercontent.com/2572253/37124007-c5ee6992-2266-11e8-9da7-0ca18d6036d5.png)

**Comment by rappen** [comment]
Ready to close this one @daryllabar ?
