### ISSUE TITLE
SQL -> FetchXML converter like KingswaySoft's online tool would be expected

### ISSUE THREAD

**Issue by GitHubAlexBP** [rappen/FetchXMLBuilder#203]
Why is there no way of going the other way, converting from SQL to FetchXML ?

Please take a look at this URL / site and "get inspired" a lot :-)

http://www.sql2fetchxml.com

Kind regards
/Alex B Pedersen

**Comment by rappen** [comment]
Because that url 😉

**Comment by GitHubAlexBP** [comment]
Closed without further comments
