### ISSUE TITLE
Window opens too small

### ISSUE THREAD

**Issue by jahillHCR** [rappen/FetchXMLBuilder#208]
The toolbox opens in a small window, which means setting the entity name is impossible if a user doesn't know to expand the window.  Having a default window size less than the space used is a big design flaw.  Either make the query builder section a dynamic size or just open larger/maximized.  

You may not have control of the window size since it's all in the toolbox now, but so much wasted space in query builder causing important info to be hidden.  Or move the node properties to the right.  Anything to keep that from being hidden by window size.

**Comment by rappen** [comment]
Thanks for the advice. Can you post a screenshot here so I can see exactly what you mean?

**Comment by jahillHCR** [comment]
<img width="669" alt="xrmtoolbox" src="https://user-images.githubusercontent.com/39096009/39814470-fafa8096-5383-11e8-8c11-2c1866c72337.png">

**Comment by rappen** [comment]
Could you check which version of FXB you have? Should be 1.2018.4.2.
I thought I fixed that thing... 🤔

**Comment by jahillHCR** [comment]
Yes, it shows version 1.2018.4.2

**Comment by rappen** [comment]
I could reproduce if I use ridiculously low height of the XTB window.
Let's see if I can handle that too...

**Comment by rappen** [comment]
Actually quite tricky to fix this in a generic way without obstructing other features.
As FXB is a complex tool, it does not really make sense to use in this low height. Increasing the height will show the necessary window components. Though I partly do sympathize with the issue you have.
