### ISSUE TITLE
Activity entities gives issues

### ISSUE THREAD

**Issue by koenvb** [rappen/FetchXMLBuilder#211]
As mentioned in the Power Query M builder plugin project, it seems you have the same issue.
(not sure how you are affiliated with each other? What is the difference of the projects?)

https://github.com/ITLec/PowerQueryBuilder/issues/7

**Comment by rappen** [comment]
Hi - we are not affiliated at all, other than that I happen to know one of the guys behind the Power Query Builder.
Could you elaborate on how the problem is preduced in FXB?

**Comment by koenvb** [comment]
Hi Jonas sorry it seems I was very confused here... 
reason I was thinking it was affiliated was that it looked so similar as the Power Query builder but seems I was just looking at the wrong plugin... Must have been a bad day. 

Sorry for bothering you about this and thanks for your plugin!

**Comment by rappen** [comment]
No worries :)
