### ISSUE TITLE
Not able to fetch metadata in fetch XML BUilder

### ISSUE THREAD

**Issue by nbhar** [rappen/FetchXMLBuilder#216]
Here are the errors I received. See attachment.
[FetchXMLBuilderIssue.docx](https://github.com/rappen/FetchXMLBuilder/files/2321591/FetchXMLBuilderIssue.docx)

**Comment by rappen** [comment]
That looks very strange...
What versions of XrmToolBox and FetchXML Builder are you currently using?

Could you start the Metadata Browser in XrmToolBox, load entities, and see what is returned?
Should return something like this:

![image](https://user-images.githubusercontent.com/2572253/44856715-5f4c0e00-ac6e-11e8-8a62-5f9d1b0351b9.png)

**Comment by nbhar** [comment]
I can see all the entities in Metadata Browser, but fetchxml builder does not work.
Some of the entities it works, but some of the entities now not showing at all.
I stopped using fetch XML Builder due to these issues. It is difficult for me to explain the whole thing in a document, rather if we can connect in a meeting would be better.

**Comment by rappen** [comment]
@nbhar Did this ever get resolved? Shall we take a closer look?

**Comment by nbhar** [comment]
No, it is not yet solved. However, other plugins are working fine except fetch xml builder.

**Comment by rappen** [comment]
Can you connect with me offline to set up a call?
jonas at jonasrapp dot net

**Comment by rappen** [comment]
Nothing changed on my end... FXB version is still 1.2018.8.2.
Did you try the reset trick to make the update work? https://www.xrmtoolbox.com/documentation/for-users/reset-xrmtoolbox-installation/
Or simply manually downloading latest version of XTB?

**Comment by nbhar** [comment]
OK, I had downloaded the latest version couple of days ago that worked I guess. 
But now there is another one update came from XRM toolbox and when I try to update the toolbox it is again showing the same error. I can set up a call with you sometime today or tomorrow.
Let me know your favorable timing.

**Comment by rsilver875** [comment]
I am experiencing the same error!

![fetchxml builder error](https://user-images.githubusercontent.com/17501394/48229956-7f3b3480-e377-11e8-8d79-70db6ffb6aba.png)

**Comment by rappen** [comment]
@rsilver875 The error that popped up there is from the View-Role Configuration tool, that somehow is running in the background even if only FXB is visible.
Try uninstalling that tool and running FXB again, please.
