### ISSUE TITLE
Make the default "Top" value for new queries either blank or configurable in settings

### ISSUE THREAD

**Issue by rarumberger** [rappen/FetchXMLBuilder#217]
The one little annoyance with every new query is having to clear out the "top" value first thing. I'd prefer that it start out with no value, but a configurable value (that supports not having a default value) would work just as well.

**Comment by rappen** [comment]
Making the entire "default new query" configurable! :)

![image](https://user-images.githubusercontent.com/2572253/44800037-b510af80-abb5-11e8-99a2-1e66618fb605.png)
