### ISSUE TITLE
Bad C# code generated

### ISSUE THREAD

**Issue by larmccoy** [rappen/FetchXMLBuilder#220]
The C# generated from a FetchXml query has errors in the code.
The anonymously typed fetchData variable in the code has duplicate members defined, specifically cms_licensestatusreason2.  It appears that the conversion algorithm does not properly handle more than 2 values for the "IN" operator in a condition element.
BTW I love the format of the FetchXml that uses the anonymous type to specify input parameters to the fetchXml.

[BadCsharp.txt](https://github.com/rappen/FetchXMLBuilder/files/2353614/BadCsharp.txt)

Thanks!
Larry McCoy
larmccoy@pacbell.net

**Comment by rappen** [comment]
I could probably reverse from the C# code to get the originating FetchXML, but if you supply it here a fix will be even faster 😊
