### ISSUE TITLE
Filters not generated correct in C# code

### ISSUE THREAD

**Issue by mradell** [rappen/FetchXMLBuilder#223]
If three or more conditions of the same attribute is used in the fetchXML, the numbering is not generated correct in the C# code view.

	var fetchData = new {
		statuscode = "1",
		statuscode2 = "478880001",
		statuscode2 = "478880000"
	};

**Comment by rappen** [comment]
@phuocle Would you like to have a look at this?

**Comment by rappen** [comment]
Don't seem to get any attention from @phuocle, perhaps you would like to have a go at it @mradell 😉

**Comment by phuocle** [comment]
@rappen sry, missing your last mention email. I'm looking on it now.
