### ISSUE TITLE
Distinct property maybe shouldn't be default

### ISSUE THREAD

**Issue by RhINO-CRM** [rappen/FetchXMLBuilder#227]
I've run into an interesting issue with the Distinct property set to true on the QueryExpression. When that property is set to true, the Id property of the returned Entities in the EntityCollection is Guid.Empty, 

cheers

/Rickard

**Comment by rappen** [comment]
That is a quite natural effect of `distinct`, as including the ids would make the distinct useless (ids are ofc always unique).
Am I missing something here?
I don't think distinct is default either... but you can edit the default "New" query in the options of FXB.

**Comment by rappen** [comment]
:)
