### ISSUE TITLE
Exception on creating query

### ISSUE THREAD

**Issue by dodgster02** [rappen/FetchXMLBuilder#246]
Using XRMToolbox v1.2019.2.32 with Addon version 1.2019.3.3 I get the following exception when I start to build a new query:

![image](https://user-images.githubusercontent.com/26326026/54134118-4091b580-440f-11e9-83ce-a1cac56f22bf.png)

This occurs after I've chosen the entity that I want to search on and attempt to add attributes to retrieve.

I'm connecting to a CRM 2015 onpremise environment

**Comment by rappen** [comment]
Hi, which output windows were visible (FetchXML, OData etc) ?
Can you paste the call stack in the details window here?

**Comment by rappen** [comment]
This is a bug in FXB for CRM 2015 and earlier. Working on a fix.

To get the previous version back, find this folder:
`C:\Users\<yourusername>\AppData\Roaming\MscrmTools\XrmToolBox\NugetPlugins\Cinteros.Xrm.FetchXMLBuilder.1.2018.12.5\lib\net452\Plugins`

Copy the contents to this folder:
`C:\Users\<yourusername>\AppData\Roaming\MscrmTools\XrmToolBox\Plugins`

**Comment by rappen** [comment]
I have just published an update, please try the latest which should be version 1.2019.3.5 and let me know if it works for you!
