### ISSUE TITLE
Organization name missing in generated OData v4 URL

### ISSUE THREAD

**Issue by mdocter** [rappen/FetchXMLBuilder#250]
Hi Jonas,

I noticed that in case of an on-premise Dynamics deployment (no IFD) the organization name is missing in the OData v4 URL. I use version 1.2019.3.6 of FetchXML Builder.

So it shows:

     https://crm.company.intra/api/data/v8.2/contacts?$select=...

instead of:

     https://crm.company.intra/MyOrgName/api/data/v8.2/contacts?$select=...

The OData v2 URL is correct and contains the organization name as expected.

Kind regards,

Maarten Docter

**Comment by rappen** [comment]
Problem code line: https://github.com/rappen/FetchXMLBuilder/blob/master/FetchXmlBuilder/FetchXmlBuilder.cs#L591

**Comment by rappen** [comment]
@mdocter Fix is now available, but I'd like someone to test it before publishing since I don't currently have access to an onprem environment.
