### ISSUE TITLE
Incorrect target record URL for IFD connections

### ISSUE THREAD

**Issue by georged** [rappen/FetchXMLBuilder#253]
When navigating from the results to the target record, URL has organization name appended. That shouldn't be done for IFD connections as org name is part of the URL.

**Comment by MarkMpn** [comment]
I can't reproduce this. I've connected to an IFD org, run a simple query for all accounts, double-clicked on a row in the results and it's navigated me to the correct URL. Is there some other step I need to do to reproduce the error?

**Comment by georged** [comment]
From memory it happened on single-click navigation on a lookup field. The other possibility, of course, is that @rappen fixed it while I wasn't looking.

**Comment by rappen** [comment]
I must have...
