### ISSUE TITLE
ODATA Query (4.0) builder.  Filter on Booleans are not translated correctly from 1,0 to true,false

### ISSUE THREAD

**Issue by ThreeTen22** [rappen/FetchXMLBuilder#255]
When you filter boolean attributes with fetchxml, you need to use 1,0, however ODATA requires using true,false.

Currently, the OData (v4.0) builder does not translate 1 and 0 to true and false respectively. 
and instead gives the error:

"String was not recognized as a valid Boolean."

FetchXml Query used to test:
`
<fetch>`
`  <entity name='crdb1_asset' >`
`    <attribute name='crdb1_generatesaudits' />`
`    <attribute name='crdb1_description' />`
`    <attribute name='crdb1_auditedexchanges' />`
`    <filter>`
`      <condition attribute='crdb1_generatesaudits' operator='eq' value='1' />`
`    </filter>`
`  </entity>`
`</fetch>`

**Comment by rappen** [comment]
Thanks for reporting, will have a look at this!

**Comment by advancedhair** [comment]
Can confirm issue. Also, when setting to value to 'true' it gets converted to 'True' in Odata 4 and Flow List parameters, which is not recognized (has to be lowercase).

**Comment by rappen** [comment]
Fixed in next release.
