### ISSUE TITLE
FetchXML not returning results correctly when value contains white space

### ISSUE THREAD

**Issue by MichaelSchofeld** [rappen/FetchXMLBuilder#259]
This is not an issue with this application but a problem I seem to be having with the FetchXML query in general. It fails in this component and it fails when I execute the FetchXML in my own code.
But I'm hoping someone has an answer.

I'm querying the Solution table to pull the data for my solution.  Here is my XML

<fetch>
  <entity name="solution">
    <attribute name="uniquename" />
    <attribute name="version" />
    <attribute name="versionnumber" />
    <filter type="or">
      <condition attribute="friendlyname" operator="eq" value="Engagement Portal" />
      <condition attribute="parentsolutionidname" operator="eq" value="Engagement Portal" />
    </filter>
  </entity>
</fetch>

the problem is that the "Engagement Portal" syntax fails to return any results if I type in the value.
However, it works if I copy and past the value from the results returned if I query the entire Solution table.

As well, in the FetchXMLBuilder, if I add a filter on the Solution table for the attribute "FriendlyName" equal "Engagement Portal", typed in to the value field, it return nothing.

however, do a query on all the records in the solution table, find and copy the "Engagement Portal" friendly name into Notepad then paste that value in the the Value field in the Filter and it works. ?????

Is there an issue with white space characters in the fetchXML? is it an ascii value problem that a copy and paste solves?

Any help would be greatly appreciated.

**Comment by rappen** [comment]
Sorry about the delay after vacation here - could you please try pasting the FetchXML again? It seems the brackets are hiding everything.
But it seems super weird from your description...

**Comment by rappen** [comment]
No response, closing.
Feel free to reopen if necessary.
