### ISSUE TITLE
Bool value prevents Viewing query as Odata 4.0(WebAPI)

### ISSUE THREAD

**Issue by KhashRastin** [rappen/FetchXMLBuilder#260]
**Problem**: 
When defining a filter with a bool field condition, the value is restricted to 0 or 1. This restriction prevents converting the FetchXml to Odata 4.0(WebAPI) since booleans in the odata query only accepts true or false.  

**Repro Steps:**

1. Define bool field condition with 0 or 1.
2. Click view as Odata 4.0(Web API) => Will fail
3. Try changing bool condition to true or false

![image](https://user-images.githubusercontent.com/2624303/64242882-a1a1ce00-cf06-11e9-830a-931ca22b6117.png)

**Comment by rappen** [comment]
Fixed but not released in #255.
