### ISSUE TITLE
Invalid settings name causes XTB to raise unhandled exception

### ISSUE THREAD

**Issue by peta** [rappen/FetchXMLBuilder#269]
[When closing the FetchXmlBuilder plugin, the settings manager is always invoke in order to persist the plugin settiings in a file. As name for the settings file, the current connection's name is used.](https://github.com/rappen/FetchXMLBuilder/blob/master/FetchXmlBuilder/FetchXmlBuilder.cs#L1666)

**Expected behaviour**

The connection name should be automatically sanitized in order to be usable as windows file name.

**Actual behaviour**

The connection name is used as it is, without any further sanitization.

**Effect** 

Given I have a connection name with special characters, using it as-is (as done by FXB today) makes XTB raise a system exception because the `SettingsManager` internally is using the given settings name 1:1 for building up an (invalid) file path to which the settings file is written. I usually use the full CRM instance URL as the connection name (including protocol part) and thus are wondering for quite some time why FXB seems to crash everytime I close it. Until today, when I had enough and turned up the debugger. :-)

 ![image](https://user-images.githubusercontent.com/131624/69066643-e925f980-0a21-11ea-810a-a60e43fe83a6.png)

I am not sure if this suboptimal value handling should be solved on the plugin-side or rather on the XTB infrastructure level (right inside the SettingsManager.Save method). What do you think @MscrmTools , @rappen ?

**Comment by rappen** [comment]
@mscrmtools what do you say about this - perhaps the serializer should be a bit forgiving if someone pass a weird file path?

**Comment by MscrmTools** [comment]
We can certainly add some path cleaning

**Comment by rappen** [comment]
🥳

**Comment by peta** [comment]
Just thinking out loud: maybe simply stripping out any [illegal characters](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidfilenamechars?view=netframework-4.8) from the passed name string before putting it into the path template string would be enough here. By doing so, the adapted save/load implementation would remain deterministic since the input value (settings name) would not need to change.

**Comment by rappen** [comment]
Yep, sounds like proper way forward with this.
I'll see if I can squeeze it in before @MscrmTools does!

**Comment by rappen** [comment]
I believe this has been implemented in XrmToolBox core, closing the issue for now but feel free to reopen if necessary!
