### ISSUE TITLE
Link Entity : "from" and "to" values should be swapped

### ISSUE THREAD

**Issue by vigneshcrm** [rappen/FetchXMLBuilder#271]
--Generate from CRM Advanced Find--
link-entity name="account" from="accountid" to="parentaccountid" link-type="inner" alias="ad" 

--Generated from FetchXmlBuilder--
link-entity name="account" from="**parentaccountid**" to="**accountid**"

I think there is issue on generating link entity from FetchXmlBuilder. "from" and "to" values should be swapped. 
If both lookup schema name and entity unique identifier schema are same, it will not be an issue since both going to have an same value. In my scenario, i am linking self referential entity and it doesn't return result

My FetchXmlBuilder Version : 1.2019.12.1

**Comment by rappen** [comment]
Fixed by @MarkMpn for next release.
