### ISSUE TITLE
WebApi output with inner join seems possible in v9.1

### ISSUE THREAD

**Issue by MscrmTools** [rappen/FetchXMLBuilder#272]
Reading [this documentation](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api#use-lambda-operators), it seems possible with api 9.1 to filter based on an inner join using keywords `any` and `all`

If so, would be cool to add to the webapi output

**Comment by rappen** [comment]
Indeed so!
Good catch. Will look into this.

**Comment by rappen** [comment]
Hi @MarkMpn - still assigned to you.
I haven't dug into this issue. Do you know the status?

**Comment by MarkMpn** [comment]
Yes, this is already implemented by adding a. For a N:1 relationship like:

```xml
<fetch>
  <entity name="account">
    <attribute name="name" />
    <link-entity name="contact" from="contactid" to="primarycontactid">
      <attribute name="fullname" />
    </link-entity>
  </entity>
</fetch>
```

it generates:

```
/api/data/v9.2/accounts?
  $select=name&
  $expand=primarycontactid($select=fullname)&
  $filter=(primarycontactid/contactid ne null)
```

For a 1:N relationship like:

```xml
<fetch>
  <entity name="contact">
    <attribute name="fullname" />
    <link-entity name="account" from="accountid" to="parentcustomerid">
      <attribute name="name" />
    </link-entity>
  </entity>
</fetch>
```

it produces:

```
/api/data/v9.2/contacts?
  $select=fullname&
  $expand=parentcustomerid_account($select=name)&
  $filter=(parentcustomerid_account/accountid ne null)
```

**Comment by rappen** [comment]
Great, thanks!
