### ISSUE TITLE
Allow Contains-Values/not-contains-values on FetchXML

### ISSUE THREAD

**Issue by eleung83** [rappen/FetchXMLBuilder#273]
Can we have the possibility to use the following operators when querying on multi-select option sets:

1. Contain-Values
2. Not-Contain-Values

It looks like we can't edit the FetchXML window to include the fetchxml format for this either as shown in  https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/multi-select-picklist

**Comment by rappen** [comment]
I will have a look at the multi select optionset options available for querying.
In the meanwhile it is absolutely possible to edit the FetchXML manually in the FetchXML window.
If the query does not render properly in the treeview, Hit Execute in the editing window directly.

![image](https://user-images.githubusercontent.com/2572253/70327577-64b3e300-1837-11ea-8bcc-13d10e30bdb9.png)

**Comment by dodgster02** [comment]
There seems to be a set of steps where you can end up causing the the fetchxml window to become readonly and the code cannot be copied out. I will see if I can recreate the issue. It did revolve around me trying to build a fetchxml query using the builder for a multi select picklist and I realised that I couldn't edit the fetchxml query 

The Execute button works well, except that you lose the custom fetch xml query when you jump to the Results tab and back to the FetchXml tab

**Comment by rappen** [comment]
Thanks @dodgster02 , looks like I have a few usability things to work on.
Please add repro steps if you manage to find out how you got to the readonly state.
