### ISSUE TITLE
If each row of an attribute is NULL the column will not be shown in the "Result View"

### ISSUE THREAD

**Issue by SErfkamp** [rappen/FetchXMLBuilder#275]
Hi,

I noticed that when you execute a query which has an attribute:
    <attribute name="some_customattribute" />
And the value for this attribute is NULL for all rows, then the column will not be displayed in the result view.

I think the issue is, that this data is not returned in the raw results and therefor does not show in the results view.

Use Case:
When I want to copy out the values of the result view and use this in further analysis the columns will vary each time, which is not really expected from e.g. an sql query point of view.

I think an option would be great to include this column, even with empty values, to keep the output columns consistent.

Best Wishes!

**Comment by rappen** [comment]
Hi @SErfkamp 

Your analysis is quite correct :) Null values are not even returned, and the result grid is entirely based on the results returned from the backend, there is no "column enforcement" from the query itself.

That said, I see how this can be annoying (especially if you compare to other query languages) and I will think a bit about how this could be accomplished.
Perhaps something related to the fix to #186.

**Comment by SErfkamp** [comment]
Yes!
I basically just went (a little) mad figuring out myself what is also described in #186. 
A consistent result would be really great. 
Do you know how this behaves in the C# results?

I do have some other issues that some „name“ columns (e.g. relationship: „ordername“) do not show up right In the result right now, that I don’t know why yet.
