### ISSUE TITLE
principalobjectaccessset does not show in OData 4.0 link

### ISSUE THREAD

**Issue by timothybohte** [rappen/FetchXMLBuilder#276]
When querying the principalobjectaccess table, the principalobjectaccess table does not show in the ODate 4.0 link as principalobjectaccessset before the "?". Also trying to filter on systemusers or teams does not work properly. You need to use 8 for systemuser and 9 for team in the condition to create the results. Which will fail in the ODate 4.0 link, which doesn't accept the integers 8 and 9. It only accepts the conditions team and systemusers.

**Comment by MarkMpn** [comment]
Do you have an example of the FetchXML query and how the OData URL should look for it?

**Comment by rappen** [comment]
This issue is stale.
Closing it now. Please reopen if needed!
