### ISSUE TITLE
Error message locks up the program

### ISSUE THREAD

**Issue by Erwin-D** [rappen/FetchXMLBuilder#279]
### Issue
While editing an Attribute Name in the Query Builder Pane I deleted the Attribute Name by mistake and pressed the Tab key. This results in an error message which can not be closed and "locks up" the entire program.

![error](https://user-images.githubusercontent.com/31799121/74644368-7807f680-5176-11ea-80c4-5dd756a6a3f0.jpg)

### Expected behaviour
The user should be able to close the pop-up to correct the mistake, without having to restart the entire program.

### Actual behaviour
Pop-up error message constantly reappears when clicking OK or trying to close it.

**Comment by rappen** [comment]
Trying to repro but I can't.
I get two popups, annoying indeed, but it's not infinite.
See: https://www.screencast.com/t/wTzywzxQgoKT

Can you share more details on how you get stuck?

Which version are you running btw?

**Comment by Dory-dev** [comment]
Sorry for the missing information:
XrmToolBox version: 1.2020.2.37
FetchXML Builder version: 1.2019.12.1

And here's a screencast: http://i.imgur.com/ePxteBH.gif

**Comment by MarkMpn** [comment]
I’ve reproduced this and I’m working on updating the validation logic to avoid this situation.

**Comment by rappen** [comment]
Solved in next release.
