### ISSUE TITLE
Opening record from results gives wrong record if resorted

### ISSUE THREAD

**Issue by akaskela** [rappen/FetchXMLBuilder#286]
The results grid allows you to sort results by clicking on the header. When you resort the results and double-click to open a record in the results, the ID used to open the record is the ID from the index in the original order, not the updated sort order. The result is that the wrong records are opened after sorting.

**Comment by rappen** [comment]
Aouch - that's not pretty!
Thanks for reporting.

**Comment by rappen** [comment]
Tried this back and forth and I just cannot reproduce...
@akaskela could you please verify this is (still) an issue?

**Comment by akaskela** [comment]
@rappen - Just updated to the latest versions and I can't reproduce this. Thanks!

**Comment by rappen** [comment]
What dodgy old version did you use before updating...? 🙄
And FXB hasn't been updated since early December - you're late! 😁

**Comment by akaskela** [comment]
I thought I updated to the latest before reporting 🤦
