### ISSUE TITLE
"in" query doesn't translate the comm-delimited string to nodes

### ISSUE THREAD

**Issue by thibaug** [rappen/FetchXMLBuilder#288]
Hi,

Trying to use the "in" filter condition an in older version, I could enter a comma-delimited string in the Values field and nodes were automatically created (1.2019.4.x). But it's now (1.2019.12.1) no longer creating nodes. 

<condition attribute='quotenumber' operator='in' value='abc, def, efg' />

Thanks!
G

**Comment by MarkMpn** [comment]
This sounds like a dupe of #277, which was fixed in February. There hasn’t been a release since then though, but this will be fixed when the next release does come out.

**Comment by rappen** [comment]
I really need to prep for a new release.... 🙄

**Comment by thibaug** [comment]
Ah, sorry about the dup. I had only checked the open issues... 😊 Thanks!
