### ISSUE TITLE
Aggregate columns not working

### ISSUE THREAD

**Issue by ashraflaskar** [rappen/FetchXMLBuilder#294]
Aggregate columns like count, countcolumn etc. do not seem to be working the same way as it used to in previous versions. I did a simple count on account to count no. of accounts and it did not return correctly. Using XRMtoolbox v1.2020.5.39. Please advise

Thanks
Ashraf

**Comment by rappen** [comment]
Hi Ashaf - could you please elaborate?
Did it crash?
Did it count differently?
How to repro?
Sample query?
Version of FetchXML Builder (it should have been in the comment text when you created the issue from XrmToolBox) where it doesn't work as expected, version where it did work as expected?
And any other info that might be relevant.

Nothing _should_ have changed in this area but I really want to make sure I didn't break anything for you!

**Comment by ashraflaskar** [comment]
Hi,

It did not crash, it just gave a wrong result. I just updated to the FXB
version 1.2020.5.7

The previous version I am not sure what it was - I do not know how to check
that now.

The query was simple to count the number of accounts - This is the result

[image: image.png]

FetchXML - FYI
<fetch no-lock="true" aggregate="true" >
  <entity name="account" >
    <attribute name="accountid" alias="cnt" aggregate="countcolumn"
distinct="true" />
  </entity>
</fetch>

The result if I convert it to OData 4 WebAPI gives the correct result
though.

Let me know if you need any more information

Thanks
Ashraf

**Comment by rappen** [comment]
Thanks for the additional info.
The image though did not come through, I guess it only works if you add a comment on GitHub, not by replying to the email.

As you say that is a very simple query... and I really cannot see how it could get the wrong result. Will try to dig some into this.

**Comment by rappen** [comment]
Oh wait... I've got it.
I thought you meant that it didn't count correctly, but it's actually not showing any results!
It's a bug in the CRMGridView (the component displaying the results).
If you change the result view to "Raw fetch result" like this, do you get the correct value?
![image](https://user-images.githubusercontent.com/2572253/82876248-c6c4e980-9f38-11ea-8b53-9f1f9af4b2e4.png)

I now get a result like:
![image](https://user-images.githubusercontent.com/2572253/82876323-e0663100-9f38-11ea-9c93-28c00d0fb69c.png)

**Comment by ashraflaskar** [comment]
Yes you are right. I do get a result in the Raw result but not in the grid!
![image](https://user-images.githubusercontent.com/65943548/82877377-b839fa80-9f57-11ea-9ac8-de6d022eb662.png)

**Comment by ashraflaskar** [comment]
Is there a way I can rollback to a previous version of FXB where this bug is not present? Can you help with that?

**Comment by MarkMpn** [comment]
As another temporary workaround you could use a different column instead of `accountid`. If you switch to another column that is populated for all records, e.g. `statecode`, you should get the result displayed correctly.

**Comment by rappen** [comment]
To rollback to previous version, follow [these instructions](https://github.com/rappen/FetchXMLBuilder/wiki/Manual-installation) and make sure you get the file from the [previous release](https://github.com/rappen/FetchXMLBuilder/releases/tag/FetchXMLBuilder-1.2019.12.001) instead of latest.

**Comment by ashraflaskar** [comment]
Thanks. Will do!
