### ISSUE TITLE
Not able to paste a guid for a lookup 

### ISSUE THREAD

**Issue by scubaracer** [rappen/FetchXMLBuilder#295]
Hi, I'm not able to enter or past a guid for a lookup. The lookup control works and really looks good, but mostly I have the guid and want to enter it.

**Comment by rappen** [comment]
Did you try unchecking this option?

![image](https://user-images.githubusercontent.com/2572253/83051383-3e386d00-a04e-11ea-8a62-3bcbfc9219b4.png)

**Comment by scubaracer** [comment]
Hi, no I just read it.
But I want to use both 😉
Kind regards,
Daniel
PS keep up the good work!
I couldn’t work without your tool

**Comment by scubaracer** [comment]
fyi when I uncheck the option I get the old functionality

**Comment by rappen** [comment]
> fyi when I uncheck the option I get the old functionality

That's the intended behavior.
There is currently no option to get both or select for each condition which method to use.

Related issue #293 is solved for next release, where defining a record for condition on the primary key is currently not possible with the Lookup Dialog.

**Comment by scubaracer** [comment]
ok thanks for the explanation, mayby you can put the option to switch between lookup and manually on the form where you enter the query? Then you can quickly switch.

**Comment by rappen** [comment]
That's actually a good idea!
Reopening the issue to pursue that improvement.

**Comment by scubaracer** [comment]
👍😊

**Comment by rappen** [comment]
![image](https://user-images.githubusercontent.com/2572253/83814681-06b96880-a6bf-11ea-89ac-9b8f5954b772.png)

![image](https://user-images.githubusercontent.com/2572253/83814703-120c9400-a6bf-11ea-923b-7f497c207bd6.png)
