### ISSUE TITLE
Cannot set the Guid for SavedQuery entity

### ISSUE THREAD

**Issue by aboodh95** [rappen/FetchXMLBuilder#300]
Hi,

Thanks for the new update, it's now much easier to find records instead of coping the Guid, but, I was trying to fetch a SavedQuery, I was not able to select the view, and also I was not able to type the guide manual, the filter part stuck, even I was not able to do the changes in the XML side

---
- Deployment: Online
- DB Version: 9.1.0.17154
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.5.39
- Tool Version: 1.2020.5.7

**Comment by rappen** [comment]
Hi, please see #295, I think you are facing the same issue.
The UX will be improved for next release.

**Comment by aboodh95** [comment]
Hi,

Yes it's the same issue, I will close this one and follow that one
