### ISSUE TITLE
Issue with Lookup Control to select record

### ISSUE THREAD

**Issue by VastConfinement** [rappen/FetchXMLBuilder#307]
Hello Jonas,

I was attempting to filter a quote query for a specific quote and came across two issues that repeated. When I select the quote as my entity and add a filter condition to select the quoteid (id) field I get an error "Cannot determine lookup entity, please enter Guid manually." If I build my condition on the accountid I am able to use the Lookup control with no issue.

Additionally, after receiving the error notification, if I don't enter a guid and instead navigate anywhere else in FetchXML builder e.g. resize the quick actions window or selecting in the query builder, the tool becomes read only. I cannot even click back into the quick actions to enter a value for the record field.

![FetchXML Builder Lookup](https://user-images.githubusercontent.com/44209815/83883366-604a8300-a711-11ea-802f-573e67006509.png)

**Comment by rappen** [comment]
Thanks for reporting @VastConfinement.
Issue with entering the guid will be solved by improved UI as described [here](https://github.com/rappen/FetchXMLBuilder/issues/295#issuecomment-639140309).
I will have to dig into the behavior making the tool disabled (readonly) that does not get released.

**Comment by rappen** [comment]
Should be fixed for next release.
