### ISSUE TITLE
History records every key stroke

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#308]
The instantaneous update of the query as you update the node properties is nice - but this also records history for each key stroke.

https://www.screencast.com/t/kSrmtzjF7uA6

History works better for each "action" (adding / changing a node etc)

**Comment by MarkMpn** [comment]
I’ll be honest, I never realised FXB had an undo/redo feature! I’ll take a look, should be able to make this work more smoothly
