### ISSUE TITLE
Problem with Like queries

### ISSUE THREAD

**Issue by jjkoran** [rappen/FetchXMLBuilder#319]
[Write your comment/feedback/issue here]
I am having issues returning data using the Like operator.   I was able to return data using the advanced find in CRM.  I then exported the FetchXML and attempted to run in it in FetchXMLBuilder, and it returned no data.    I was querying the invoice number and name field of the invoice entity if that matters. 
---
- Deployment: Online
- DB Version: 9.1.0.17754
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2020.6.2

**Comment by MarkMpn** [comment]
It seems to be working for me. Can you share your query?

**Comment by rappen** [comment]
Closing for now due to lack of feedback. Feel free to reopen if necessary.
