### ISSUE TITLE
Create Default Administrator Repository

### ISSUE THREAD

**Issue by daryllabar** [rappen/FetchXMLBuilder#326]
It would be useful to create a default Administrator repository that comes with the FetchXML Builder.  Maybe even call it a "Managed Repository" since you're really not supposed to edit it.  But it could contain a list of useful FetchXml queries for admins.  Like one to return users they need to assign roles to.  One to return all workflows, or maybe workflow errors.  Maybe another that returns roles.

Maybe also have some way to submit to the repository, where you can define what the query is for, and why you might want to use it.  But then you'll probably also want to implement a search feature as well.  And it would be nice if it didn't require an upgrade of the FXB in order to get the latest version of the Repository.  And maybe in the future you could create a FetchXml Repository store, just like the XTB tools store, where anyone can share their repositories.

**Comment by MarkMpn** [comment]
I'd be interested in a similar thing for SQL 4 CDS too, maybe we could set up a shared repository that both tools could use?
