### ISSUE TITLE
FetchXML for creating/Modifying Dynamics view

### ISSUE THREAD

**Issue by amir-wayn** [rappen/FetchXMLBuilder#331]
FetchXML builder does not allow creating a view from the tool.
In a situation where an existing Dynamics view is modified (add more fields) it still fails

"Cannot save view, returned attributes must not be changed."

I am not changing anything here but only adding a field.

Any advise?

**Comment by rappen** [comment]
First statement: FetchXML Builder can create Personal Views, if the query has been opened from an existing view in Dynamics.

Regarding adding fields, there seems to be a slight misunderstanding here... :)
Attribute = Field, and adding a field to the query means that you are changing the attributes that the query returns.

The reason for this is that FetchXML Builder will only update the *query* of the view, and will not touch the *layout* of the view.
If you just want to add fields to the view, that is best done in the view designer in the platform.

**Comment by amir-wayn** [comment]
Thanks Jonas for your reply.
Please advise me on the "view designer in the platform"
Where can I find that?
Thanks.

**Comment by rappen** [comment]
Are you sure the relationships you want to include are M:1 relationships? A view can only display information from the main entity and its "parent" records. If they are 1:M relationships, it will not be available. Instead you would have to start from the child entity in that case.

**Comment by rappen** [comment]
Closing for now due to lack of feedback. Feel free to reopen if necessary.
