### ISSUE TITLE
Fetching Operators for the record id field throws an exception

### ISSUE THREAD

**Issue by manuelwaldner** [rappen/FetchXMLBuilder#345]
Deployment: Online
DB Version: 9.1.0.19857
XrmToolBox Version: 1.2020.6.40
Tool Version: 1.2020.7.3

I get an exception if i want to add an filter on the id of the opportunity (see screenshot)
![image](https://user-images.githubusercontent.com/43695452/88261640-fb4deb00-ccc6-11ea-9618-90651dbbc9f6.png)

This results in a not applicable condition, as the operators dropdown is empty.

Excuse me for the german call stack, but i think it should help anyway.

************** Call Stack **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Cinteros.Xrm.FetchXmlBuilder.Controls.conditionControl.RefreshOperators()
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rappen** [comment]
Vielen Dank for reporting, this will be fixed in next release.

**Comment by manuelwaldner** [comment]
Any idea when the new release will be?

**Comment by rappen** [comment]
Sorry, nothing planned yet, less than a day since last release... 😕
Perhaps @MarkMpn might have a workaround for now?

**Comment by MarkMpn** [comment]
At the moment the only way appears to be editing the FetchXML directly - `<condition attribute="opportunityid" operator="eq" value="guid" />`

**Comment by rappen** [comment]
Fix is now released in version 1.2020.9.1 🙂
