### ISSUE TITLE
Like and Contains Query functionality

### ISSUE THREAD

**Issue by MattCollins-Jones** [rappen/FetchXMLBuilder#348]
Not sure if this is an issue or a feature enhancement. V1.2020.7.3

In D365/CDS/Microsoft Dataflex Pro you can use the "Contains" operator. But the system converts the Contains into "Like" for FetchXML, which i think then converts back to contains for OData, i'm not sure. If you try to build a query using the FetchXML builder and choose "Contains" it inserts the Contains operator which doesn't execute as it states it's an unknown operator.

I then used the Like operator instead but when I entered my string and hit execute, it didn't work. It didn't automatically insert wildcards around my string in the FetchXML. Once I inserted these, the query worked. Is this as intended? 

Could we have some options that inserts wildcards or something to make it a bit more user friendly? Or could contains convert the FetchXML into Like with the wildcards?

**Comment by MarkMpn** [comment]
Yes, `contains` is not a valid FetchXML operator. I'm not sure why it's displayed in the list of available operators.

The simple fix is to just remove it as an option from the list, but as you say unless you're familiar with the LIKE operator from SQL you may well not know the "magic" wildcard operators to use with it, so I can see the advantage in keeping it as an option and having FXB silently convert between "contains x" and "like %x%" in a similar way to Advanced Find.

Do you have any preferences here @rappen ?

**Comment by MarkMpn** [comment]
I've been doing some more investigation in this area, and there are some edge cases around the conversion to OData.

We can convert the FetchXML `like` operator to either `endswith`, `startswith`, `contains` or `eq` if the value has a `%` character at the start, end, both or neither respectively.

However, there is no OData equivalent for the more general case of using other combinations of either `%` or `_` wildcard characters. As an example, the FetchXML:

```xml
<condition attribute="fullname" operator="like" value="d_n %" />
```

The current logic would convert this (incorrectly) to:

`$filter=contains(fullname, 'd_n %')`

I'm working on a change that will identify the fact that the value ends with a `%` and instead convert it to:

`$filter=startswith(fullname, 'd_n ')`

but this has a different result from the original FetchXML. While the FetchXML would match the names `Dan` and `Don`, the OData version will only match the literal `d_n`.

As far as I can see, we could either:

1. stick with this, and accept that in this (probably unlikely) case the results will be different
2. check for these values and show an error indicating that the OData conversion is not available

I'm inclined to go with option 1, as I imagine when a wildcard character is used within (not at either end) of the value then it is actually meant as a literal character anyway, but I'm open to suggestions.

**Comment by rappen** [comment]
And it's live!
