### ISSUE TITLE
Column compare feature using non text fields

### ISSUE THREAD

**Issue by David161069** [rappen/FetchXMLBuilder#351]
I tired to use the Fetch XML Builder to compare 2 date fields. I get an error. The query builder is asking for something in the 'value' field, but I only want to use the 'value of' field. Text fields work fine, but option sets, whole number and date fields don't. I understand these field types are supported by Microsoft when doing column compare in Fetch XML. Do you plan to support these field types in the Fetch XML Builder.
BTW, love your work.
![FetchXMLBuilderError](https://user-images.githubusercontent.com/69066490/89093563-c866ce00-d40f-11ea-9cf4-05fa35fb386b.JPG)

**Comment by MarkMpn** [comment]
There is a fix for this ready in #349, hopefully this will be in the next release.

**Comment by palashbd** [comment]
![image](https://user-images.githubusercontent.com/48243973/90114431-8412f080-dd74-11ea-8aef-aba7fed8b9e8.png)
_How to eliminate this error!_

**Comment by MarkMpn** [comment]
@palashbd What version of D365 are you running this against? Online or on-prem?

**Comment by palashbd** [comment]
@MarkMpn v1.2020.6.40

**Comment by MarkMpn** [comment]
@palashbd Sorry, I meant the version of D365, not XrmToolBox or FetchXML Builder. In the D365 web interface, click the gearwheel icon in the top right, then About. For example, when I do this I see "Version 1710 (9.1.0.20748) online"

**Comment by palashbd** [comment]
![image](https://user-images.githubusercontent.com/48243973/90115910-93933900-dd76-11ea-9382-d01e45421908.png)
@MarkMpn

**Comment by MarkMpn** [comment]
OK, this feature is only available in online versions at the moment. I'd expect it to be in the next major on-premise release.
