### ISSUE TITLE
Unable to Query by GUID In latest Version

### ISSUE THREAD

**Issue by ACECEO** [rappen/FetchXMLBuilder#353]
The latest version seems to have eliminated the ability to query by record GUID. Now when I attempt to do this, Xrmtoolbox crashes. It does not allow me to choose an operator such as Equal. I needed to restore the previous version to restore this critically important functionality.

**Comment by MarkMpn** [comment]
Duplicate of #345, will be fixed in next release.

**Comment by rappen** [comment]
Fix is now released in version 1.2020.9.1 🙂
