### ISSUE TITLE
Possible error in Power Automate List Records Parameters

### ISSUE THREAD

**Issue by thomassandsor** [rappen/FetchXMLBuilder#361]
When writing a fetchxml query with conditions "or" and "and" in the same fetch, the filter query syntax doesn't show correctly. 

![image](https://user-images.githubusercontent.com/33664322/90976325-57ad6000-e53c-11ea-8c37-56cedd0ae41f.png)

The result in the picture is

prefix_godkjenning eq 914620000 and prefix_godkjenningtime eq 914620000)(prefix_lnnsart eq '10' or prefix_lnnsart eq '15'

It seems to be missing "(" at the start and one a the end.

When I remove one of the last conditions it has
(prefix_godkjenning eq 914620000 and prefix_godkjenningtime eq 914620000)prefix_lnnsart eq '10'
Where the AND statement is ok, but the last one received syntax error in Power Automate. 

When I add "AND" to it, it works fine
(prefix_godkjenning eq 914620000 and prefix_godkjenningtime eq 914620000) **and** prefix_lnnsart eq '10'

The total query that I got working was 
(prefix_godkjenning eq 914620000 and prefix_godkjenningtime eq 914620000) **and** (prefix_lnnsart eq '10' or prefix_lnnsart eq '15')

---
- Deployment: Online
- DB Version: 9.1.0.21048
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2020.7.3

**Comment by rappen** [comment]
> I've never seen a query with two `<filter>` nodes directly within the `<entity>` nodes before, I've only seen them with one nested inside the other. Are the two filters implicitly and-ed together when used in this way?

Yes, adding several `<filter>` paralell nodes we be the same as adding them within a `<filter type="and">` node.
The `<entity>` node works in the same way, in that sense.

**Comment by rappen** [comment]
Fix is now released in version 1.2020.9.1 🙂
