### ISSUE TITLE
NotLike operator missing minor detail

### ISSUE THREAD

**Issue by thomassandsor** [rappen/FetchXMLBuilder#362]
This this might be a feature request, but or another user error :) 
I also believe there might be a smarter way of doing this that I am not aware of..

![image](https://user-images.githubusercontent.com/33664322/90978543-fba00700-e54e-11ea-80ac-c17ed33bb9f6.png)
When using the operator "NotLike" (same as begins with or ends with in advanced find), the expression for Power Automate doesn't include the "+T". It only has "T". In the WebAPI the "+T" is included. 

would it be possible to help the user also understand the NotLike better? To my understanding it is used from advanced find for Doesn't begin with or End with, and probably does not contain? 

![image](https://user-images.githubusercontent.com/33664322/90978607-5b96ad80-e54f-11ea-9b26-1b6d47ec7d45.png)
This syntax "%+T" will be for the does not end with, but I had to figure that out from advanced find XML. Would it make sense to include an option before value with "starts with / ends with"?

**Comment by rappen** [comment]
Fix is now released in version 1.2020.9.1 🙂
