### ISSUE TITLE
convert fetchxml queries into DynamicsMarketing Segments using the "Segment Query Defintion"

### ISSUE THREAD

**Issue by jellevervloessem** [rappen/FetchXMLBuilder#375]
Since Dynamics Marketing is evolving into a mature product, I'm adopting it. I need to migrate my dynamic marketing lists (having fetchxml under the hood) to Segments.

The dynamics marketing Segments have also a query under the hood, but it's another synthax: 
![image](https://user-images.githubusercontent.com/6337073/93060173-10fde200-f672-11ea-94a6-bc987c2d87da.png)

Maybe FetchXMLbuilder can also provide this synthax?

_creating a segment_: https://docs.microsoft.com/en-us/dynamics365/marketing/create-segment 
_Segment Query Defintion_: https://docs.microsoft.com/en-us/dynamics365/marketing/developer/segment-query-definition

**Comment by rappen** [comment]
Interesting! I'll have a look at it when I find some time 🙂

**Comment by rappen** [comment]
I'm cleaning my closet... @jellevervloessem 
Would this be relevant to anything today? I guess we've just moved on from Dynamics Marketing...
Closing time? I'll keep it open a bit more if you have any opinions!

**Comment by jellevervloessem** [comment]
You can close it. It's been 4y now and did not had the requirement again.

**Comment by rappen** [comment]
Thanks for your response!
