### ISSUE TITLE
Multi level Expand in OData 4.0

### ISSUE THREAD

**Issue by BenediktBergmann** [rappen/FetchXMLBuilder#376]
In OData 4.0 and its implementation in the CDS WebAPI we have the possibility to have multi level expands.
[Link to MS docs](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-related-entities-query#multi-level-expand-of-single-valued-navigation-properties)

The FetchXML Builder is not supporting this at the moment. It shows a message, that OData querys only support one level of link entities.
![image](https://user-images.githubusercontent.com/9703748/93722211-703d8400-fb95-11ea-8b26-f76f9074a292.png)
![image](https://user-images.githubusercontent.com/9703748/93722204-6582ef00-fb95-11ea-8a36-aad0e9627d1e.png)

When creating the request myself the WebAPI is giving the correct data.
![image](https://user-images.githubusercontent.com/9703748/93722237-a549d680-fb95-11ea-9f7b-8fd783b909c5.png)
![image](https://user-images.githubusercontent.com/9703748/93722263-d75b3880-fb95-11ea-99bb-45e126e17433.png)

Would be nice to have the possibility to let FetchXML Builder generate multi level expands as well.

**Comment by rappen** [comment]
Fixed in #359

**Comment by rappen** [comment]
And it's live!
