### ISSUE TITLE
Copying text (from Onenote) and Pasting into Edit XML window causes image to be pasted

### ISSUE THREAD

**Issue by xairrick** [rappen/FetchXMLBuilder#39]
When I copy text from OneNote (2013) and pasting it into the Edit XML window, it's getting pasted as an image.  

Most likely a function of the editor, hopefully you'll be able to change the paste event and tell it to grab the text content

**Comment by rappen** [comment]
Hint for future fix: http://stackoverflow.com/questions/22152122/how-to-paste-text-to-richtextbox-as-a-plain-text

**Comment by rappen** [comment]
Done after 6+ years!
Fixed by https://github.com/rappen/FetchXMLBuilder/pull/521
Thanks @MarkMpn 😊

**Comment by xairrick** [comment]
Thanks!!
