### ISSUE TITLE
Current User in FetchXml

### ISSUE THREAD

**Issue by MaceWindu1** [rappen/FetchXMLBuilder#393]
You should be able to add GUID as a variable when executing FetchXml with _operator="eq-userid"_ condition so you can get data from response when you have no records on the current environment.

**Comment by rappen** [comment]
The `eq-userid` operator does not allow any value, since it explicitly implied current user.
Use operator `eq` to provide the id of any user.

Not a limitation of FetchXML Builder, but a constraint in the FetchXML query language.

**Comment by rappen** [comment]
Feel free to re-open if I misunderstood your request!
