### ISSUE TITLE
Power Automate Trigger Conditions

### ISSUE THREAD

**Issue by eamedlab** [rappen/FetchXMLBuilder#401]
When creating the FetchXML and selecting "View Power Automate Parameters", it would be helpful to have a way to view/convert the filter query into PA Trigger Conditions. For example, the query for OData shows as this: 

> _crf73_outsidevendoraccount_value ne null

which needs to be converted for a trigger like so:

> @not(equals(triggerBody()?['_crf73_outsidevendoraccount_value'],null))

**Comment by rappen** [comment]
I'm guessing you mean this?

![image](https://user-images.githubusercontent.com/2572253/100937051-b5b1f200-34f2-11eb-8559-4683c824f10d.png)

Is it not possible to use the CDS (current environment) connector, where you can use the OData filter as trigger filter expression?

![image](https://user-images.githubusercontent.com/2572253/100937289-18a38900-34f3-11eb-8bc5-d3084995adfe.png)

**Comment by eamedlab** [comment]
I hadn't seen that option on the new CDS connector. Many of our flows use the original connector/trigger conditions in your first screen shot. We'll have to test on the the option and see if it properly prevents a flow run. Thanks!

**Comment by rappen** [comment]
Hope it works out well!
Closing this for now - feel free to re-open if necessary :)
