### ISSUE TITLE
for a number of fields i get an error: Failed to generate SQL Query. No metadata for attribute

### ISSUE THREAD

**Issue by vhkt** [rappen/FetchXMLBuilder#407]

**Comment by rappen** [comment]
That sounds nasty 😕
Could you provide an example of query and error message?
Does it occur during building or executing the query?

**Comment by rappen** [comment]
@vhkt any more info on this?

**Comment by vhkt** [comment]
Hi,

I don't use it every day, but it did resolve when i opened the objecttree on the left side of the screen pointing at the particular field
