### ISSUE TITLE
Filtering on nested (two level) entities in WebAPI

### ISSUE THREAD

**Issue by szmarci** [rappen/FetchXMLBuilder#415]
I have a two level deep expand filter, like this (all M:1 relationships):

```
<fetch>
    <entity name="quotedetail" >
        <attribute name="quotedetailid" />
        <link-entity name="quote" from="quoteid" to="salespackage" >
            <attribute name="quoteid" />
            <attribute name="name" />
            <link-entity name="salescategory" from="salescategoryid" to="salescategoryid" >
                <attribute name="salescategoryid" />
                <attribute name="name" />
                <filter>
                    <condition attribute="name" operator="eq" value="string" />
                </filter>
            </link-entity>
        </link-entity>
    </entity>
</fetch>
```

When executed inside FetchXML Builder the query works as expected.

However, the WebAPI version does not. This is what gets generated in the WebAPI block (only the filter part):
`&$filter=salespackage/salescategoryid/name eq 'string'`

After executing the query in the browser, this is what I get:

```
"error": {
    "code": "0x80040216",
    "message": "entityRelationshipRole for given navigation property not found"
}
```

If I try to filter only one level deep (in this example, on `quote`), it works fine with WebAPI.

I don't see any reason why it shouldn't work on two level deep queries or am I missing something?

**Comment by rappen** [comment]
Summoning my minions - @MarkMpn and @LinnZawWin !
![image](https://upload.wikimedia.org/wikipedia/en/7/7d/Minions_characters.png)

**Comment by LinnZawWin** [comment]
@szmarci I believe the relationship "quotedetail to quote" link-entity tag in your FetchXML is incorrect. It should be 
`<link-entity name="quote" from="quoteid" to=" ̶s̶̶̶a̶̶̶l̶̶̶e̶̶̶s̶̶̶p̶̶̶a̶̶̶c̶̶̶k̶̶̶a̶̶̶g̶̶̶e̶̶̶ quoteid" >`
and the WebAPI filter part should be
`&$filter= ̶s̶̶̶a̶̶̶l̶̶̶e̶̶̶s̶̶̶p̶̶̶a̶̶̶c̶̶̶k̶̶̶a̶̶̶g̶̶̶e̶̶̶ quoteid/salescategoryid/name eq 'string'`

I don't have the salescategory table related to Quote in my environment but I replaced it with CreatedBy user.
```
<fetch>
  <entity name='quotedetail' >
    <attribute name='quotedetailid' />
    <link-entity name='quote' from='quoteid' to='quoteid' >
      <attribute name='quoteid' />
      <attribute name='name' />
      <link-entity name='systemuser' from='systemuserid' to='createdby' >
        <attribute name='systemuserid' />
        <attribute name='fullname' />
        <filter>
          <condition attribute='fullname' operator='eq' value='Test User' />
        </filter>
      </link-entity>
    </link-entity>
  </entity>
</fetch>
```

The tool generates the WebAPI query below for the FetchXML above and it is working fine with no error.
`GET [Organization URI]/api/data/v9.1/quotedetails?$select=quotedetailid&$expand=quoteid($select=quoteid,name;$expand=createdby($select=systemuserid,fullname))&$filter=(quoteid/quoteid ne null) and (quoteid/createdby/fullname eq 'Test+User')`

**Comment by szmarci** [comment]
@LinnZawWin Sorry, I did not mention this: `salespackage` is a custom lookup on `quotedetail`, that is pointing also to `quote`. 
So it should work the same. Anyway with `createdby` it works, but here is another scenario: if you try it with `account` (if I can recall it is on quote by default, so it must work for you as well)

```
<fetch>
  <entity name="quotedetail" >
    <attribute name="quotedetailid" />
    <link-entity name="quote" from="quoteid" to="quoteid" >
      <attribute name="quoteid" />
      <attribute name="name" />
      <link-entity name="account" from="accountid" to="msdyn_account" >
        <attribute name="name" />
        <filter>
          <condition attribute="name" operator="eq" value="Test User" />
        </filter>
      </link-entity>
    </link-entity>
  </entity>
</fetch>
```

It fails with the same error. Could you verify it fails for you as well?
Maybe it only works on special, automatically generated lookups, like `createdby`?

**Comment by MarkMpn** [comment]
For me this gives an error because `msdyn_account` does not exist on the `quote` entity. The standard relationship between `quote` and `account` uses the `customerid` attribute instead:

```xml
<fetch>
  <entity name="quotedetail" >
    <attribute name="quotedetailid" />
    <link-entity name="quote" from="quoteid" to="quoteid" >
      <attribute name="quoteid" />
      <attribute name="name" />
      <link-entity name="account" from="accountid" to="customerid" >
        <attribute name="name" />
        <filter>
          <condition attribute="name" operator="eq" value="Test User" />
        </filter>
      </link-entity>
    </link-entity>
  </entity>
</fetch>
```

However, this then gives me the same error when trying to execute the WebAPI request as you reported initially. I can't see anything obviously wrong with the query though, any ideas @LinnZawWin?

**Comment by szmarci** [comment]
@MarkMpn You are right, that was custom as well. I tried to diff `createdby` with `customerid` in the metadata browser, the only thing I found was the security type, not sure if that matters though:
![image](https://user-images.githubusercontent.com/1974290/100089155-87c51180-2e51-11eb-9584-afdff73a01f3.png)

**Comment by LinnZawWin** [comment]
@MarkMpn Interesting... I can now replicate the issue with any other OOB (`opportunityid`, `pricelevelid`, `owningbusinessunit`) or custom columns. Surprisingly, it is working in certain OOB lookup columns (`createdby`, `modifiedby`, `owninguser`, `owningteam`, etc.)
I really cannot pinpoint the issue and it must be a limitation (or a bug) in the Web API query.

**Comment by szmarci** [comment]
@MarkMpn @LinnZawWin Thanks for checking up on these. Where do you think I should report this issue?
[https://github.com/OData/WebApi](https://github.com/OData/WebApi) Here?
Or are there dynamics related WebApi threads?

**Comment by LinnZawWin** [comment]
@szmarci 
I've got a response from Microsoft. Filter on nested single-valued navigation property (2-level or more N:1) relationship is not fully functional yet and thus, it is not supported at the moment. When the full feature is complete, they will update [the docs](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api#filter-records-based-on-single-valued-navigation-property) and support this scenario fully.

CC: @MarkMpn

**Comment by szmarci** [comment]
@LinnZawWin Thank you for the info!
