### ISSUE TITLE
Query Expression generation for field comparison condition is invalid

### ISSUE THREAD

**Issue by bwmodular** [rappen/FetchXMLBuilder#421]
If you have a query which compares the value in one firld with the value in another, the query expression which gets generated is invalid.
See the example below. The fetchXml has two conditions on the modified on column. One users 'greater than' and an absolute value, the other users 'greater than' to compare to another field.
The fetchXml generated is correct, using the 'valueof' operator for the second condition, but the query expression condition is identical for both of the conditions:
![image](https://user-images.githubusercontent.com/1889586/101175749-7348fc00-363d-11eb-9cdd-98683214b102.png)

For the field comparison, it should add another parameter, 'compareColumns' with a value of 'true', and will need to create two different 'condition value' variables to do this:
![image](https://user-images.githubusercontent.com/1889586/101175640-50b6e300-363d-11eb-95b2-ec533e8952af.png)

**Comment by bwmodular** [comment]
That was quick! Thanks @MarkMpn !

**Comment by rappen** [comment]
Expect a new release (with this fix included) before Christmas! 🎄
