### ISSUE TITLE
QueryExpression generation is failing

### ISSUE THREAD

**Issue by bnsp4u** [rappen/FetchXMLBuilder#438]
generating QueryExpression is failing.

ERROR as follows

Failed to generate C# QueryExpression code.

Method not found: 'Boolean Microsoft.Xrm.Sdk.Query.ConditionExpression.get_CompareColumns()'.

**Comment by MarkMpn** [comment]
What version of XrmToolBox are you running? It sounds like you’ve got the latest version of FetchXML Builder but running within an older version of XrmToolBox

**Comment by clmichae** [comment]
I am also experiencing this issue. The version of XrmToolBox I'm running is v1.2020.11.42 and the version of FetchXmlBuilder installed is 1.2020.12.3.

**Comment by rappen** [comment]
Long shot - how about version of the database?
(It should be automatically populated in the issue here when you create it from within XrmToolBox.)

**Comment by rappen** [comment]
Actually.... I get it too.... 
Looking into it!

**Comment by MarkMpn** [comment]
@rappen Can you get the location and version of the SDK assembly that’s loaded when you get the error please? Sounds like it might be picking up a different version from somewhere unexpected

**Comment by catalin-ilie** [comment]
I am also getting this error. With latest xrmtoolbox and fetchxmlbuilder.

**Comment by rappen** [comment]
Until next release of XrmToolBox (which should be this week, according to sources) you may work around this by getting the latest package of [Microsoft.CrmSdk.CoreAssemblies](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreAssemblies/) and place `Microsoft.Xrm.Sdk.dll` in your XrmToolBox folder.

Sorry about that... 🙄
