### ISSUE TITLE
Power Automate filter query doesn't work/look right

### ISSUE THREAD

**Issue by ameyholden** [rappen/FetchXMLBuilder#459]
Lead filter query doesn't look very oData-esque and doesn't work - oh no!

![image](https://user-images.githubusercontent.com/57081102/108616026-c1f87c00-745d-11eb-975b-158339de1c6b.png)

---
- Deployment: Online
- DB Version: 9.2.21014.132
- Connection Controls Version: 1.2021.2.40
- XrmToolBox Version: 1.2020.11.42
- Tool Version: 1.2020.12.3

**Comment by MarkMpn** [comment]
I've just tested this and it seems to work as expected for me. Can you show the error you're getting when you try to use it?

**Comment by ameyholden** [comment]
Hey Mark – sorry it took me so long to reply I thought I was just being an idiot but its come back again, hopefully attached screenshots can help explain the issue


Kind Regards,

Amey Holden
Dynamics 365 & Power Platform Architect | Dynamics 365 Marketing Specialist | Director @ Amey Holden Pty Ltd
M  +61 466 452 299
ameyholden.com<https://www.ameyholden.com/>
[cid:image002.jpg@01D70DE4.E8CAFA40]
Microsoft Business Applications Most Valuable Professional 2020-2021

**Comment by MarkMpn** [comment]
Your email attachments don’t seem to have come through to GitHub properly - can you try adding them again through the GitHub website rather than by email please?

**Comment by ameyholden** [comment]
![SNAG-0000 28-02-2021](https://user-images.githubusercontent.com/57081102/109449762-5c2f7400-7a9d-11eb-969e-16e0e6f6864e.png)
![SNAG-0001 28-02-2021](https://user-images.githubusercontent.com/57081102/109449774-62255500-7a9d-11eb-91ab-0a987427f896.png)
![SNAG-0002 28-02-2021](https://user-images.githubusercontent.com/57081102/109449783-65b8dc00-7a9d-11eb-9962-45b0310b19d5.png)

**Comment by MarkMpn** [comment]
Thanks for those. Looks like you're using the details from FetchXMLBuilder in a "When a row is added, modified or deleted" trigger, but FetchXMLBuilder is generating them in the format required for the "List records" action.

This trigger can use the same OData format for the "Row filter" setting, but for the "Column filter" it uses a comma-separated list of attributes. The Flow will trigger when any of the listed attributes change - it's not necessarily listing the column values to include in the results in the same way that the "List records" action works.

Assuming you want your Flow to run when any of the attributes you've listed change (although things like `leadid` and `createdon` can't be changed, so you could safely remove them) you'll need to simplify the names of the attributes. Simple attributes such as `fullname` will still be the same, but lookup attributes that appear as `_ownerid_value` in the OData query need to be changed to just `ownerid` for this trigger.

**Comment by ameyholden** [comment]
Thanks Mark that makes sense – appreciate your help on this – user error!

Kind Regards,

Amey Holden
Dynamics 365 & Power Platform Architect | Dynamics 365 Marketing Specialist | Director @ Amey Holden Pty Ltd
M  +61 466 452 299
ameyholden.com<https://www.ameyholden.com/>
[cid:image002.jpg@01D70F7F.8EC18770]
Microsoft Business Applications Most Valuable Professional 2020-2021

**Comment by rappen** [comment]
@MarkMpn @ameyholden 😘
