### ISSUE TITLE
Filtering on linked entities without expanding

### ISSUE THREAD

**Issue by aureole82** [rappen/FetchXMLBuilder#502]
I'd like to filter on M:1 relation object without expanding it, it should be like this
> /Employees?$filter=Superior/FirstName eq 'Nancy'

(Example taken from https://github.com/simple-odata-client/Simple.OData.Client/wiki/Retrieving-linked-entries-without-fetching-its-owners#untyped-syntax-1.)

Is this possible?

As far as I know FetchXMLBuilder can only do:
> /Employees?$expand=Superior($filter=(FirstName eq 'Nancy'))

But that's not the same! Unfortunately your documentation tells nothing: https://fetchxmlbuilder.com/features/#advanced.

**Comment by MarkMpn** [comment]
If you use a query like:

```xml
<fetch >
  <entity name="account" >
    <attribute name="name" />
    <link-entity name="contact" from="contactid" to="primarycontactid" >
      <filter>
        <condition attribute="firstname" operator="eq" value="Jonas" />
      </filter>
    </link-entity>
  </entity>
</fetch>
```

this will be converted to:

`/api/data/v9.2/accounts?$select=name&$expand=primarycontactid()&$filter=(primarycontactid/firstname eq 'Jonas')`

You can also rearrange the query to move the `<filter>` up to the top level `<entity>`:

```xml
<fetch >
  <entity name="account" >
    <attribute name="name" />
    <link-entity name="contact" from="contactid" to="primarycontactid" />
    <filter>
      <condition entityname="contact" attribute="firstname" operator="eq" value="Jonas" />
    </filter>
  </entity>
</fetch>
```

This is converted to:

`/api/data/v9.2/accounts?$select=name&$filter=(primarycontactid/firstname eq 'Jonas') and (primarycontactid/contactid ne null)`

**Comment by aureole82** [comment]
@MarkMpn This might work. I tried the same with `order` but `entityname` will be removed every time I change ascending/descending in Query Builder panel.
