### ISSUE TITLE
Cannot copy or edit fetchxml 

### ISSUE THREAD

**Issue by dbcottam** [rappen/FetchXMLBuilder#518]
I can no longer edit or copy the fetchxml  in the fetchxml view.  This is causing me huge problems, as I rely on both the wizard and the edit capability in the view.

Please give me back that functionality.  

-- User of 2 years.

**Comment by rappen** [comment]
Don't know why it does not work for you...
See here: https://www.screencast.com/t/u1tnHbW3
It has not been removed.

**Comment by dbcottam** [comment]
@rappen  -- thanks for the quick follow up.  I did a restart of the application and it worked again! I will close this out

**Comment by rappen** [comment]
👌
