### ISSUE TITLE
Some views appear to be missing

### ISSUE THREAD

**Issue by simes1** [rappen/FetchXMLBuilder#519]
I've noticed quite a view entities that appear to have views defined are missing from the list of views that FXB can open.

Two examples are Record Creation and Update Rules and Record Creation and Update Rule Items.

Regards

--
Simon

**Comment by rappen** [comment]
Try setting option "Allow opening uncustomizable views" to check it.

![image](https://user-images.githubusercontent.com/2572253/125434308-32c23006-5096-4f6c-b3b3-0820b3c23d6f.png)

If it is not checked, then the views that cannot be updated.

Documentation will be updated, at any time...
https://fetchxmlbuilder.com/features/#options
https://fetchxmlbuilder.com/features/#qrymgmt-open

**Comment by simes1** [comment]
Doh! (Why didn't I see that...)

Thank you.
