### ISSUE TITLE
Escape "[" character (and others?) in FetchXML

### ISSUE THREAD

**Issue by simes1** [rappen/FetchXMLBuilder#527]
After much head scratching it appears that D365 requires an open square bracket character "[" to be replaced with "[[]" in a value.  This appears to be what Advanced Find does but not by default the ConditionXML in things like Automatic Record Creation Rule Items (more head-scratching - possibly MS bug???)]

So for example to find subjects beginning with "[Ticket" this works:

```xml
      <condition attribute="subject" operator="like" value="[[]Ticket%" />
```

but this does not:

```xml
      <condition attribute="subject" operator="like" value="[Ticket%" />
```

FetchXML Builder doesn't seem to know about this substitution either (and presumably also for "]"?).  I didn't think these were special characters in XML but they do seem to be treated in a special way by MS.

It would be great if FetchXML Builder handled these situations automatically (or at least called out somehow that they might require some special attention).

Regards

--
Simon

---
- Deployment: Online
- DB Version: 9.2.21064.140
- Connection Controls Version: 1.2021.6.44
- XrmToolBox Version: 1.2021.6.51
- Tool Version: 1.2021.4.4

**Comment by MarkMpn** [comment]
For reference, the `like` operator will be mapped through to the equivalent T-SQL operator which supports various wildcard characters beyond just `%`:

[T-SQL LIKE supported wildcards](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver15&WT.mc_id=DX-MVP-5004203#arguments)

These can be [escaped as described in the docs](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver15&WT.mc_id=DX-MVP-5004203#using-wildcard-characters-as-literals)

I'd be wary about doing this automatically in a way you can't override though, as you may want to use these as wildcards in some circumstances and escape them for use as literals in others.

FetchXML Builder does automatically convert between the "Begins With" / "Ends With" and "Like" operators in various places, and it would probably be a good change to support this in those cases, e.g. you enter a condition as "Begins With" and a value of "[Ticket" and it generates the escaped value `[[]Ticket%`. Maybe if you're entering a Like condition directly though the tool could display a warning or error if it detects a mismatched wildcard like `[Ticket%`

**Comment by simes1** [comment]
Thanks for the insight Mark - I hadn't realised like was passed straight through to SQL in quite this way and now the penny has dropped re why this wasn't working.

Like many using FXB I guess, I'm not a coder, so tend to be using FetchXML builder with all the "friendly" options turned on.  So it would indeed be good to have it do the same translation as Advanced Find in those situations where one is using Begins With/Ends With

For the more developer orientated scenarios some form of warning when you're using Like - ideally with a reference to further information such as you just supplied - would I think also be really useful.
