### ISSUE TITLE
[Feature Request] View "Power Query"

### ISSUE THREAD

**Issue by mores** [rappen/FetchXMLBuilder#529]
Given this fetch xml:

`<fetch>
  <entity name="opportunity" >
    <attribute name="name" />
    <link-entity name="account" from="accountid" to="parentaccountid" >
      <attribute name="name" />
    </link-entity>
  </entity>
</fetch>`

Output:
[PowerQuery.txt](https://github.com/rappen/FetchXMLBuilder/files/6900851/PowerQuery.txt)

This will allow me to paste it in "Advanced Editor" of the PowerBI Power Query Editor

**Comment by rappen** [comment]
Thanks for the idea!
I don't know basically anything of Power Query...
Who want to help this implement this?

**Comment by mores** [comment]
There is another tool in the toolbox:
    https://crmchartguy.com/power-query-builder/
    https://github.com/ITLec/PowerQueryBuilder
that does convert the fetchXML into PowerQuery 
but it just feels clunky jumping from tool to tool and would be better if this functionality was in FetchXMLBuilder

**Comment by UlrikBC** [comment]
The Power Query Builder does have the FetchXML Builder integration. i.e. you can open PQB, click the button to use FXB, create your query and return to PQB and finish the setup. There's a decent amount of logic in PQB that determines how the fields are expanded depending on their type to get the right label.

**Comment by rappen** [comment]
I'm cleaning out my closet...
Thanks @UlrikBC, it seems this is unnecessary to convert in FXB since it is very possible in PQB, so I guess I'll just close this now.
Please reopen @mores if needed!
