### ISSUE TITLE
Some populated columns display as if empty.

### ISSUE THREAD

**Issue by simes1** [rappen/FetchXMLBuilder#556]
I've found FetchXRMBuilder displays certain columns as if they have no value even when (using a filter) it is clear that they do contain a value.

For example these owner columns are empty:
![image](https://user-images.githubusercontent.com/11423243/131693229-648b6e15-1b60-419d-958c-f5630cfa0f2a.png)

But the filter says the owneridtype is a team (as I'd expect):
![image](https://user-images.githubusercontent.com/11423243/131693680-5f7a1d10-bc37-4015-815b-63c493b9c3db.png)

In addition you can only select these columns with the Friendly Names setting off.  If you turn it on it looks like this:
![image](https://user-images.githubusercontent.com/11423243/131694286-7d07ce5c-973a-48e7-87ab-68d142ee0ca5.png)

I'm not sure if that's related or if I'm doing something wrong...

--
Simon

---
- Deployment: Online
- DB Version: 9.2.21082.132
- Connection Controls Version: 1.2021.6.44
- XrmToolBox Version: 1.2021.6.51
- Tool Version: 1.2021.4.4

**Comment by rappen** [comment]
Thanks @simes1, I will investigate!

**Comment by rappen** [comment]
Looking at metadata, it says info about the `ownerid*` attributes, they are fishy.
These attributes can't be used for filter (except the FetchXML does not fail) and the "data" is not set on these attribute, I really don't know when the info is available....

![image](https://user-images.githubusercontent.com/2572253/131733113-16e71c08-2cb5-4f34-a6a5-43ec61fce2f4.png)

Any more info?

**Comment by MarkMpn** [comment]
I found that these virtual attributes aren’t handled in the same way as normal physical attributes in all sorts of ways.

To get the values, the type and name values can be extracted from the EntityReference value in the physical attribute. I’m not sure about the yominame value.

To filter on these attributes you need to add a join to the appropriate other table(s), e.g. to find records owned by a team you can add an inner join to the team entity rather than a filler on the owneridtype attribute.

**Comment by rappen** [comment]
This setting is "safe", where this weird attributes are hidden 😉

![image](https://user-images.githubusercontent.com/2572253/131799804-05095d8c-bb69-4987-a5f5-1daacd2ff247.png)

**Comment by simes1** [comment]
Apologies, I've perhaps not used the best example...  There are many other ways one can check if a row is owned by a user or a team and I couldn't remember the specific column(s) I was looking for at the time I had this problem when I was submitting this.  However, these common owner fields seemed to operate the same way.  I'll try to remember what the original ones were.

@rappen I think the filter clause does actually work (rather than simply not error) - if I select the expected value in the filter condition those rows are returned, if I select that it is empty those rows aren't returned.  I'm using options that superficially look the same as yours but with them I can easily display one of these columns:
![image](https://user-images.githubusercontent.com/11423243/131889120-11c6b870-e21d-4fc7-bb85-786af9b8b8a9.png)

@MarkMpn I'm not actually creating FetchXML queries as such I'm using FetchXML builder just to inspect and analyse data because it's so much quicker and has fewer restrictions than Advanced Find.  I've used PowerQuery as well but I like to be able to easily switch between friendly names and more easily see the option set labels, lookup values etc.

What's so confusing is that it's so easy to add one of these columns to the view and then think it must be empty - rather harder and less obvious to add it to the filter and find that actually it appears to have values in it...

**Comment by simes1** [comment]
I think this is one of the ones I was looking at - Accepting User Or Queue Object Type/acceptingentitytypecode on email:
![image](https://user-images.githubusercontent.com/11423243/131891403-1a54708c-3017-450c-9c7d-d61a9ee6070d.png)

Unlike the owner ones you can use it in advanced find:
![image](https://user-images.githubusercontent.com/11423243/131891126-1ad98916-e6e3-4fef-a620-57a955ea61b1.png)

From memory there was something similar for the regarding lookup on a mailbox.

**Comment by MarkMpn** [comment]
This is the same type of attribute as the others you were looking at around ownerid - this is another virtual attribute that isn't valid to include in the results directly.

So the question is how best to make this less confusing? The main options I can see are:

1. Always exclude virtual entities from the list in the attribute editor
2. Change the default options to include the "Only valid for read" option
3. Change the grid display to extract the name/type values from the EntityReference values

Any opinion @rappen?

**Comment by simes1** [comment]
Well obviously I'd prefer 3 because it would make it so much easier to then use those attributes/columns in any filter.  Perhaps they would need some warning sign next to the column name though so it's clear you couldn't use them in a real view?

On a related note it would also be useful to be able to see the various isvalidfor* metadata when selecting columns to add to the view (but possibly not when choosing them from drop-downs because of the space?).

**Comment by rappen** [comment]
1. I want to see this **dialog** have a few checkboxes where you show which attributes. Easily "Read Only", but also a bunch of various metadata options.
Now it only shows name and type, could also (optional) more meta info.

2. Alse some info from you fetch with "attributes for reading", showing basic like logicname, displayname, entity, and also "all" metadata options. Same thing too for "attributes for filter" and the same info. So you open a fetch-info, with all data about it...

3. From any **Attributes** node property or **Condition** node, it should have a quick to open attribute meta details.

What you think?

**Comment by rappen** [comment]
I haven't heard any more, so the added three new issues will make it at least better :)
Closing now.

**Comment by rappen** [comment]
I agree.
Will try to find the best way of showing this info.

First, my columns here show wrong metadata... 🙄
![image](https://user-images.githubusercontent.com/2572253/136838345-eb076e64-0e8d-4266-bef9-0a1292b800f1.png)

Has now _Read, Create, Update, Custom_.
Would be a lot better with _Read, InGrid, Retrieve, InAdvFind_ at least...

Also some "warning" is the treeview and/or the Node Properties too.

This is good idea, started a bit too fast, I will open it again.

**Comment by rappen** [comment]
What do you think of this?

![image](https://user-images.githubusercontent.com/2572253/149022081-e0a19040-53a4-491a-b1e0-58f25c26638c.png)

![image](https://user-images.githubusercontent.com/2572253/149021889-55b9c15b-915e-4485-8c56-92ffb0c228f4.png)

**Comment by rappen** [comment]
I'm cleaning out my closet...

Three years later, do you have any thoughts about what you would most like to get in FXB regarding this issue, @simes1?

**Comment by simes1** [comment]
It's too long ago, (and I've not used FXB for a while), but my memory was that you fixed quite a bit of this.  I'd close for the moment - if I remember/revisit I'll reopen.
