### ISSUE TITLE
Keyboard Shortcut for Power Automate Parameters

### ISSUE THREAD

**Issue by MattCollins-Jones** [rappen/FetchXMLBuilder#573]
Could we get a Keyboard shortcut to get the Power Automate Parameters please? Or a properties pane on the right that we can pin open and updates as we update the FetchXML query? 

---
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.9.52
- Tool Version: 1.2021.4.4

**Comment by rappen** [comment]
You really need kb-shorts?
Just click on the Power Automote params, and they are copied...

![image](https://user-images.githubusercontent.com/2572253/135288711-eec7f95a-5a3f-471a-972f-f2f44ebcea6c.png)

Example - how do you want it?
_Quickly - new release coming soon...!_

**Comment by MattCollins-Jones** [comment]
No to open the parameter window. I usually have about 3 or 4 FetchXML queries and may go back and edit one. Then I have to click View -> Power Automate Parameters. If we could get a keyboard shortcut, it would save 2 click each time. Although I did just find this, but I thought a keyboard shortcut might be useful as well 😁 I like being efficient.


![2021-09-29_15-39-43](https://user-images.githubusercontent.com/60160115/135291498-dba0c470-4c24-41da-ac34-0584a0c2abe7.png)

**Comment by rappen** [comment]
Ok - so what is a good <xxx>+... we use? 😁

**Comment by MattCollins-Jones** [comment]
Ctrl+P (for Power Automate)
Ctrl+L (for list rows)
Ctrl+O (for I can't be bothered to learn oData so Jonas built this tool for me 😂)

**Comment by MarkMpn** [comment]
I like the idea of having it as a docked tool window and have it updated automatically as the query changes - that would make it the same as the other conversions like Web API & SQL

**Comment by rappen** [comment]
Or hope so this is good for now...

![image](https://user-images.githubusercontent.com/2572253/135299982-81c6236a-4eb2-43d6-b877-6157ccae9f63.png)
