### ISSUE TITLE
When directly editing FetchXML, using Undo will revert the last change on the Query Builder

### ISSUE THREAD

**Issue by MatthewTheRaven** [rappen/FetchXMLBuilder#578]
When manually updating the FetchXML directly, you would expect that hitting Ctrl+Z would undo the last text you've changed in that part of the window. Instead it reverts the last change for the entire Query Builder, which seems to be the last time you've actually edited it directly via that part of the tool. 

The end result is that you may make many changes to the FetchXML that properly parses to the Query Builder, then hit Ctrl+Z, and the manual changes are completely undone all the way back to the last time the user actually made changes in the Query Builder directly.

**Comment by MatthewTheRaven** [comment]
As an additional detail, when the tool gets into this state, where the Query Builder no longer matches the FetchXML, continuing to alter the FetchXML directly will not be reflected in the Query Builder. Any change to the Query Builder after this will totally overwrite anything that was in the FetchXML editor.

**Comment by MarkMpn** [comment]
I'd expect changes in the text editor to only be reflected in the Query Builder area once it is fully valid and either you have the "Live Update Query" option ticked or you click the OK button in the bottom right. If you are still typing it probably won't be valid FetchXML and so the Query Builder won't be updated.

Any changes in the Query Builder will always overwrite the text editor.

I agree the undo experience should be better though.

**Comment by MatthewTheRaven** [comment]
Agreed, but right now even after it has validated and updated the Query Builder many times, and even gotten results, pressing Undo will roll all the way back to the last direct Query Builder update.
