### ISSUE TITLE
Can Not Save Back to CRM 

### ISSUE THREAD

**Issue by Kcross8787** [rappen/FetchXMLBuilder#593]
Hi,

I am trying to edit an existing view in our D365 CRM. For about 15 minutes I was able to make edits and save them back, but now every time I try to make an edit the "Save View" button is greyed out. Would anyone happen to know how to fix this? I have tried refreshing the entities, creating a new view, going to a different entity, redoing the connection with the CRM, restarting XRM Toolbox and restarting my computer.

Here is an example of the issue.
Edit: Here is the correct photo
https://snipboard.io/bl9LcF.jpg

Thank you for your time,

**Comment by Kcross8787** [comment]
For anyone that runs into this error, first open up the view you wish to edit. Then you can get around the error by selecting the Open > Open View option and reopening the same dynamics view. Doing this will then allow you to save it back to the crm.

https://snipboard.io/7kbBtU.jpg

**Comment by rappen** [comment]
Hi

First snip seems wrong one (not doing GP).

I can't really get it to get disabled.
The Dataverse icon stills is enable:
![image](https://user-images.githubusercontent.com/2572253/142460445-8e37079c-086c-481e-8e1f-4c68a8dd1ef4.png)

Technically, it is disabled when:
`tsmiSaveView.Enabled = enabled && Service != null && View != null && View.IsCustomizable();`
and the IsCustomizable gets like this:
```
return entity != null
                && (entity.LogicalName == "userquery"
                || (entity.Contains("iscustomizable")
                    && entity["iscustomizable"] is BooleanManagedProperty iscust
                    && iscust.Value));
```
That's all that disabled the menu.

Any more info for me?

**Comment by rappen** [comment]
Any news @Kcross8787 ?

**Comment by Kcross8787** [comment]
Hi Jonas,

I was able to get around the issue. Thank you for checking into this though.

Have a great day.

**Comment by rappen** [comment]
Thanks, so this is closed since I could not get your problem in any way.
