### ISSUE TITLE
Sorting on date fields 

### ISSUE THREAD

**Issue by kaluznyt** [rappen/FetchXMLBuilder#600]
Hi, 

I noticed that it can be very useful to have an option to sort the results in the Result View by date, currently it seems the sorting is based on the string representation, which is not really useful. 
<img width="69" alt="image" src="https://user-images.githubusercontent.com/572605/145565473-19f858f5-7705-4296-8c60-9a45aab462e0.png">

Is that something that could be added ? I would be really grateful!

Tomasz

**Comment by rappen** [comment]
Ouch... That is bad, really bad!
I will look at it, change your locale ISO 8601 until then 😉

**Comment by rappen** [comment]
This will be fixed for next release.
You have are using weird format date (US etc) you can sort when using "**Not** Friendly Names".
![image](https://user-images.githubusercontent.com/2572253/148077548-7020a66f-0e42-401f-b88b-17adc8f52c6e.png)

When using "Friendly Names" it will show all data as string, and will be sorted like the string as they show you.

**Comment by kaluznyt** [comment]
Great thanks!
