### ISSUE TITLE
Show warnings in the Query Builder

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#612]
Make it easier to find fishy queries.

Related to #556 and #609.

**Comment by rappen** [comment]
Example:

![image](https://user-images.githubusercontent.com/2572253/149023229-a9525dd5-968b-42e3-8cdb-3b5bc7c3310e.png)

**Comment by MarkMpn** [comment]
I like this, I've wanted to add some sort of warnings list for a while. There's various strange things about FetchXML I've come across over time that I could possibly add into the same structure.

**Comment by rappen** [comment]
Here you can see the first warning added to validations - it's about to grow...
https://github.com/rappen/FetchXMLBuilder/blob/master/FetchXmlBuilder/AppCode/Validations.cs

But I guess the code is now robust enough to get it to grow now!
