### ISSUE TITLE
I try to add a condition, i have the error

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#622]
Got the same error. The starting of the app is good, but when i try to add a condition, i have the error 
![image](https://user-images.githubusercontent.com/90260514/149807691-3d3cdda5-cf5a-4b1a-8697-d8ae51500fd1.png)

_Originally posted by @FabriceDB in https://github.com/rappen/FetchXMLBuilder/issues/621#issuecomment-1014720291_

**Comment by FabriceDB** [comment]
Thank you for the great job :)
