### ISSUE TITLE
Not showing in tree view Vs fetchXML code

### ISSUE THREAD

**Issue by citqpdarcy** [rappen/FetchXMLBuilder#624]
![image](https://user-images.githubusercontent.com/97910896/149821630-c42f5b0b-7dd7-4ac9-bf97-77b102412ff1.png)

Also, says an error regarding an alias for a link-entity, it tells the alias is not there , but it is.

Please advise :)

**Comment by rappen** [comment]
That's weird too...
The layout seems strange, almost like screen buggy.
Hard to try this, have you more info for me?

**Comment by citqpdarcy** [comment]
Hi Jonas,

I tried to uninstall FetchXML Builder, then reinstall it... no luck
Tried to install XRM Toolbox and another machine and tested with the Builder, no luck either.

For the example showing the problem, I just used a fetchXML already build and pasted it into the FetchXML windows. Usually, before the last update, everything was working fine regarding that.

Pascal J. Darcy
Directeur informatique et Directeur adjoint à l'administration
CITQ
1010, rue De Sérigny, bureau 810
Longueuil (Québec)  J4K 5G7

Tél. : 450 679-3737, poste 239
Télécopieur : 450-679-1489
Sans frais : 1 866 499-0550, poste 239

Courriel : ***@***.******@***.***>
Site internet : www.citq.info<https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.citq.info%2F&data=04%7C01%7Cpdarcy%40citq.qc.ca%7C845734b900f8451da22908d98e498fa5%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637697268850617829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zm%2BNaa1LZEb2pJa89dbmvGYX0GRBIK9i1P%2BHrt9XxwY%3D&reserved=0>

De : Jonas Rapp ***@***.***>
Envoyé : 17 janvier 2022 14:02
À : rappen/FetchXMLBuilder ***@***.***>
Cc : Pascal Darcy ***@***.***>; Author ***@***.***>
Objet : Infomail Re: [rappen/FetchXMLBuilder] Not showing in tree view Vs fetchXML code (Issue #624)


That's weird too...
The layout seems strange, almost like screen buggy.
Hard to try this, have you more info for me?

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frappen%2FFetchXMLBuilder%2Fissues%2F624%23issuecomment-1014818319&data=04%7C01%7Cpdarcy%40citq.qc.ca%7C2c5c0ff4e4244dde9e3b08d9d9ebcea8%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637780429098490138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3%2F9KW0OWtOtZgqMhZ%2FNKrcvZbEyDfi1bKXKU5%2BZUGvY%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXLAA4FDLLAYH5X5B7AWS3DUWRRRHANCNFSM5MFKUTLA&data=04%7C01%7Cpdarcy%40citq.qc.ca%7C2c5c0ff4e4244dde9e3b08d9d9ebcea8%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637780429098490138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uwDO4V4D%2BQdh%2FB24zHeeGE4jRT2DjEWHY477haHbGcI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpdarcy%40citq.qc.ca%7C2c5c0ff4e4244dde9e3b08d9d9ebcea8%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637780429098490138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Aptz8E5WeHcabM8MMWVacwW5Kno0Y84N3nVHjccGTb4%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpdarcy%40citq.qc.ca%7C2c5c0ff4e4244dde9e3b08d9d9ebcea8%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637780429098490138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bnfCUIdUrXp%2FSLUW9Cv5l2OF5H%2BQB6CU9BznqBsV5cQ%3D&reserved=0>.

**Comment by rappen** [comment]
I will start to look at this problem. 👍
See here if you need to install older version: https://fetchxmlbuilder.com/releases/1-2021-10/
Sorry this bugs exist.

**Comment by citqpdarcy** [comment]
Thank you Jonas, 😊 You’re the best
Will do that meanwhile

Pascal J. Darcy
Directeur informatique et Directeur adjoint à l’administration
CITQ
1010, rue De Sérigny, bureau 810
Longueuil (Québec)  J4K 5G7

Tél. : 450 679-3737, poste 239
Télécopieur : 450-679-1489
Sans frais : 1 866 499-0550, poste 239

Courriel : ***@***.******@***.***>
Site internet : www.citq.info<https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.citq.info%2F&data=04%7C01%7Cpdarcy%40citq.qc.ca%7C845734b900f8451da22908d98e498fa5%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637697268850617829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zm%2BNaa1LZEb2pJa89dbmvGYX0GRBIK9i1P%2BHrt9XxwY%3D&reserved=0>

De : Jonas Rapp ***@***.***>
Envoyé : 17 janvier 2022 14:28
À : rappen/FetchXMLBuilder ***@***.***>
Cc : Pascal Darcy ***@***.***>; Author ***@***.***>
Objet : Infomail Re: [rappen/FetchXMLBuilder] Not showing in tree view Vs fetchXML code (Issue #624)


I will start to look at this problem. 👍
See here if you need to install older version: https://fetchxmlbuilder.com/releases/1-2021-10/<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffetchxmlbuilder.com%2Freleases%2F1-2021-10%2F&data=04%7C01%7Cpdarcy%40citq.qc.ca%7Ce89cff22d33e4987cb9a08d9d9ef8c54%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637780445144721070%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9UOvrXYLm8cHdIC4HxMMZTBRHqHv6UfRXbHA%2FZMndZE%3D&reserved=0>
Sorry this bugs exist.

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frappen%2FFetchXMLBuilder%2Fissues%2F624%23issuecomment-1014834588&data=04%7C01%7Cpdarcy%40citq.qc.ca%7Ce89cff22d33e4987cb9a08d9d9ef8c54%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637780445144721070%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4GFTH7Fb9HE8iBK%2Fp1ywdIIgT9KSWVqABqbPK3kSTyg%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXLAA4D4ORDJKYC3EBPQGS3UWRUVVANCNFSM5MFKUTLA&data=04%7C01%7Cpdarcy%40citq.qc.ca%7Ce89cff22d33e4987cb9a08d9d9ef8c54%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637780445144721070%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JqnZ1CsNwQgWA6vIfUXwonJsCujizRXjU5VqwnlPkJM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpdarcy%40citq.qc.ca%7Ce89cff22d33e4987cb9a08d9d9ef8c54%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637780445144721070%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aESwdnskEJ%2FPW9MjvNRRS8kLdd2LWyeyl2%2F33PyobkY%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpdarcy%40citq.qc.ca%7Ce89cff22d33e4987cb9a08d9d9ef8c54%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637780445144877267%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FMWg0qz57iLUYG9yUHFpuUBRICK6y%2FbyEG5WCalmWNs%3D&reserved=0>.

**Comment by rappen** [comment]
It would also good to know if you do also have the same issue if you start from a new fetchxml, and build it from there?
If so, can you when the problem starts occurring?

**Comment by TaroAM** [comment]
Make sure that you don't have any errors in your fetch (I had a placeholder value I was dynamically populating). I was about to comment saying I had the same error and realised I had the placeholder value. If I make that valid by putting some dummy data. It populates the left tree.

**Comment by rappen** [comment]
Should be fixed in version 1.2022.1.4 - plane try again! 🙏🙂

**Comment by citqpdarcy** [comment]
Hi Jonas,

I confirm it’s now working correctly. Thank you for your kindly help
Is there anything I can do to help you in the development of your tools ? Donation?

Thank you

Pascal J. Darcy
Directeur informatique et Directeur adjoint à l’administration
CITQ
1010, rue De Sérigny, bureau 810
Longueuil (Québec)  J4K 5G7

Tél. : 450 679-3737, poste 239
Télécopieur : 450-679-1489
Sans frais : 1 866 499-0550, poste 239

Courriel : ***@***.******@***.***>
Site internet : www.citq.info<https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.citq.info%2F&data=04%7C01%7Cpdarcy%40citq.qc.ca%7C845734b900f8451da22908d98e498fa5%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637697268850617829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zm%2BNaa1LZEb2pJa89dbmvGYX0GRBIK9i1P%2BHrt9XxwY%3D&reserved=0>

De : Jonas Rapp ***@***.***>
Envoyé : 19 janvier 2022 06:12
À : rappen/FetchXMLBuilder ***@***.***>
Cc : Pascal Darcy ***@***.***>; Author ***@***.***>
Objet : Infomail Re: [rappen/FetchXMLBuilder] Not showing in tree view Vs fetchXML code (Issue #624)


Should be fixed in version 1.2022.1.4 - plane try again! 🙏🙂

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frappen%2FFetchXMLBuilder%2Fissues%2F624%23issuecomment-1016348800&data=04%7C01%7Cpdarcy%40citq.qc.ca%7Ca44178a902c94260231608d9db3c980b%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637781875594019120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JEBac%2FP2tNOQ0HJIhS7UyMUjJoifhDszcWBOgpAxzNs%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXLAA4H2RYDNCU3IWDDJYJDUW2MB3ANCNFSM5MFKUTLA&data=04%7C01%7Cpdarcy%40citq.qc.ca%7Ca44178a902c94260231608d9db3c980b%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637781875594019120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ulyr7mY8qmeJLbwVhhHRGRVuPhAIoVGHTXrCTBjvKwk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpdarcy%40citq.qc.ca%7Ca44178a902c94260231608d9db3c980b%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637781875594019120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JuJGBS5DrROrYHbJ8aG3u5IyuBi9WrVOH4EbRo3dtq8%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpdarcy%40citq.qc.ca%7Ca44178a902c94260231608d9db3c980b%7C93f7ac5df331403398d9afe7cbb6ce43%7C1%7C0%7C637781875594019120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vg3W%2BoZunW6GAVMR4fznCmZLugdM9yxMnkWVzQSf88o%3D&reserved=0>.

**Comment by rappen** [comment]
😊
Donation is always nice 😉
 
![image](https://user-images.githubusercontent.com/2572253/150162477-026cc483-cd4e-41b2-b299-b3bdf77e8d97.png)
