### ISSUE TITLE
Ability to copy the value only from a cell (exclude the column header)

### ISSUE THREAD

**Issue by markduk** [rappen/FetchXMLBuilder#625]
I often want to select the value of a cell so I can paste it somewhere else.  When I try this I always end up with the field name being copied too.  I can see that at different times both might be useful.  

I couldn't find a setting for this or documentation on whether it exists already but I'd love a way to select just the value.

Thanks

**Comment by rappen** [comment]
It should be possible 🙂
This is in menu of the Result View (down, left) and uncheck the _Appearance - Cope with Headers_.

![image](https://user-images.githubusercontent.com/2572253/150085049-3bf357b3-315f-47d6-a511-6ded21d3f70c.png)

Might not be the best place for this setting... 🤔

Copy is simply done with CTRL+C.

**Comment by markduk** [comment]
OMG!! There it is!  I looked almost everywhere :)
Thanks for your help.
