### ISSUE TITLE
FetchXml Crashed all the time now

### ISSUE THREAD

**Issue by JunbinDuan** [rappen/FetchXMLBuilder#632]
Hi FetchXml totally broken now, it even cannot start correctly. Could you have a look? Thanks a lot...

![FetchXml Crashed](https://user-images.githubusercontent.com/35816725/151826189-e4dd3d8f-e0b4-41b4-842d-9c3f4d419940.jpg)

**Comment by rappen** [comment]
Thanks, we are seeing this now - I will get some work on this.
Related with #631

**Comment by JunbinDuan** [comment]
Thank you Jonas, that was a quick fix.

Any idea to push to XmlToolbox, so I can share the news to my colleagues to get the latest?

**Comment by rappen** [comment]
Update is available now!

Please let me know if any more issues! 🙏

Version 1.2022.1.5:

![image](https://user-images.githubusercontent.com/2572253/151846677-f4c0a2e2-d28e-4e31-be33-5f6201b21984.png)

**Comment by JunbinDuan** [comment]
There must be another issue. Please see the screenshot:

![FetchXml Crashed-1](https://user-images.githubusercontent.com/35816725/151849789-70319d79-f653-4076-a8a6-1af6e2776f50.jpg)

**Comment by JunbinDuan** [comment]
I have removed the settings, and reinstalled.
