### ISSUE TITLE
XML fail

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#633]
There must be another issue. Please see the screenshot:

![FetchXml Crashed-1](https://user-images.githubusercontent.com/35816725/151849789-70319d79-f653-4076-a8a6-1af6e2776f50.jpg)

_Originally posted by @JunbinDuan in https://github.com/rappen/FetchXMLBuilder/issues/632#issuecomment-1026068582_

**Comment by rappen** [comment]
@JunbinDuan can you send the fetchxml that fails?
Email if fetch is "secret" to jonas at jonasr.app

Looks like the XML is incorrect though...

**Comment by JunbinDuan** [comment]
to make things easier, I record the steps from building a brand new FetchXml. Please let me know if you have an issue to open it. I recorded with Steps Recorder.

[FetchXmlIssue.zip](https://github.com/rappen/FetchXMLBuilder/files/7973405/FetchXmlIssue.zip)

**Comment by JunbinDuan** [comment]
I am working on an on-premise environment. The issues showed up in new year some time. Even just selecting the account entity/table, then it crashes when trying to select attributes. May be just related to on-premise environment?

**Comment by rappen** [comment]
Ah, probably version of the problem.
When you create an issue from XTB you get version things we like 🙂
<img width="783" alt="image" src="https://user-images.githubusercontent.com/2572253/151863570-4874bb09-6681-41bb-bf21-3a07d2f59f7b.png">

Looking at the recording, but no screenshots are included.

**Comment by rappen** [comment]
Thanks - again!
Ok, DB version 8.* crashes FXB.
I will fix it 💪

**Comment by rappen** [comment]
I'm closing this now, I have not test in any onprem - please reopen if the problem is still there after release version 1.2022.2.
