### ISSUE TITLE
The tool is very handy and useful. However with recent update, I cannot Select attributes.

### ISSUE THREAD

**Issue by JunbinDuan** [rappen/FetchXMLBuilder#635]
[Write your comment/feedback/issue here]

---
- Deployment: OnPremise
- DB Version: 8.2.23.16
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53
- Tool Version: 1.2022.1.5

![Screenshot 2022-01-31 153101](https://user-images.githubusercontent.com/35816725/151868360-1dde086a-5f5c-4ee4-9d1b-3a003e313fbc.jpg)

**Comment by rappen** [comment]
Related to #633 
Closing this now.
