### ISSUE TITLE
small improvement :)

### ISSUE THREAD

**Issue by FabriceDB** [rappen/FetchXMLBuilder#636]
In some fields in the app, as in the Value field in a filter, if we stroke 'Enter', the value disappears. 'Tab' is working fine.
![image](https://user-images.githubusercontent.com/90260514/151939127-c6dd59cb-119c-439b-b11c-61a87d75addd.png)

**Comment by rappen** [comment]
Oh. I see.
That's stupid...

I'll see what I can do.
