### ISSUE TITLE
IsValidForGrid Setting

### ISSUE THREAD

**Issue by RugerSR762** [rappen/FetchXMLBuilder#637]
Is there a way to change the metadata setting for IsValidForGrid? 

![image](https://user-images.githubusercontent.com/2572253/149022081-e0a19040-53a4-491a-b1e0-58f25c26638c.png)

![image](https://user-images.githubusercontent.com/2572253/149021889-55b9c15b-915e-4485-8c56-92ffb0c228f4.png)

_Originally posted by @rappen in https://github.com/rappen/FetchXMLBuilder/issues/556#issuecomment-1010363229_

**Comment by rappen** [comment]
Not sure I understand... You want to change the metadata on an attribute?
Or to change something in how it is shown in FXB?
The metadata `IsValidForGrid` is shown as **Grid** in the Select Attributes form.

**Comment by rappen** [comment]
Sorry, FXB cannot change the metadata. FXB can show the meta, but that's it.
Also, when I try these attributes, I get data back from a few (many/all?) attributes data - so what is this `IsValidForGrid` meaning?

**Comment by rappen** [comment]
Closing this now.
Please reopen if I didn't understand properly!
