### ISSUE TITLE
Revert version (not working after update)

### ISSUE THREAD

**Issue by dm-pr** [rappen/FetchXMLBuilder#641]
[Write your comment/feedback/issue here]

---
- Deployment: OnPremise
- DB Version: 8.2.5.4
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53
- Tool Version: 1.2022.2.1

Hej Jonas

Latest update is not working for me,  is there a way to revert to FetchXMLBuilder of , let's say, december version ?  
It was working fine then.
The current issue is that no entity names are loaded from our on-prem (IFD) CRM.
I have reinstalled (and removed AppData cache) both XrmToolbox and FetchXmlBuilder.

Thanks in advance
Dmitriy

**Comment by rappen** [comment]
Hi, I'm sorry to hear this.
Use this instruction: https://fetchxmlbuilder.com/manual-installation/

Could you check these settings? https://fetchxmlbuilder.com/releases/1-2022-2/#my-best-feature
I want to fix this 😃

**Comment by rappen** [comment]
A new update has been released, it *should* work now!
Sorry for the problems... 🙏

**Comment by dm-pr** [comment]
Latest update works for me,    great job Jonas!
Many thanks :)
