### ISSUE TITLE
Issue Convert FetchXML in Query Expression

### ISSUE THREAD

**Issue by Antonio86Cop** [rappen/FetchXMLBuilder#649]
Hello,
can't convert fetchxml to QueryExpression.
The versions of xrmtoolbox and fetchxmlbuilder are the latest. The error is as follows:

Failed to generate C# QueryExpression code.

Method not found: 'Boolean Microsoft.Xrm.Sdk.Query.ConditionExpression.get_CompareColumns()'.

**Comment by MarkMpn** [comment]
Can you take a look at #438 too, this was a problem with having an old version of the SDK assemblies installed. It could be because FetchXML Builder is running in an old version of XrmToolBox, or I've also seen some people have old versions of the SDK installed in the GAC too.

**Comment by Antonio86Cop** [comment]
Thanks for the support. The problem is that I had old versions of the SDK in the GAC
