### ISSUE TITLE
NotEqualBusinessId operator missing

### ISSUE THREAD

**Issue by GuidoPreite** [rappen/FetchXMLBuilder#651]
When dealing with some column types some specific operators appears, but looks like the NotEqualBusinessId (FetchXML equivalent _ne-businessid_) is missing.
Screenshot:
![image](https://user-images.githubusercontent.com/43754988/153747592-442498c9-e540-4c52-8e66-fe2f80ad93c5.png)

**Comment by rappen** [comment]
Adding `NotEqualBusinessId` and `NotEqualUserId` to contition attributes of type `Uniqueidentifier` or `Owner`.
