### ISSUE TITLE
Throw for fetching of `aaduser` table

### ISSUE THREAD

**Issue by rafek1241** [rappen/FetchXMLBuilder#666]
**issue:** 
QUERY:
```
<fetch>
  <entity name="aaduser">
    <attribute name="displayname" />
    <filter>
      <condition attribute="aaduserid" operator="eq" value="XXX" />
    </filter>
  </entity>
</fetch>
```
Result:
```
Microsoft.Graph.ServiceException: Code: Request_ResourceNotFound
Message: Resource '' does not exist or one of its queried reference-property objects are not present.
Inner error:
	AdditionalData:
	date: 2022-03-03T13:29:09
	request-id: ba4a0d6e-e881-4568-a4b7-26dd25d13cd6
	client-request-id: ba4a0d6e-e881-4568-a4b7-26dd25d13cd6
ClientRequestId: ba4a0d6e-e881-4568-a4b7-26dd25d13cd6
```

![image](https://user-images.githubusercontent.com/9272027/156574550-457a779f-f453-427a-984e-644e15d27232.png)

**Comment by rappen** [comment]
I see the same problem.
Not really sure why...
The `aaduser` is internal and uncustomizable and virtual... Some fishy is happening here...
Any ideas?

**Comment by rafek1241** [comment]
Within SQL 4 CDs the same thing happen :p. It informs us that casting of SQL string to guid can't happen. Maybe that is some helpful input

**Comment by MarkMpn** [comment]
Looks like an error in the virtual table provider for this entity, this would be one for MS to fix in that code rather than FetchXML Builder or SQL 4 CDS.

**Comment by rappen** [comment]
I don't think we can do anymore to this issue... 😕
Please reopen or have any more info!

**Comment by rafek1241** [comment]
@MarkMpn just from curiosity, can you provide me some docs/resources about this virtual table provider? I would like to read about it.

**Comment by rappen** [comment]
@rafek1241 there are a few links here for example:

![image](https://user-images.githubusercontent.com/2572253/156633607-653ee184-5dbe-4077-b4c5-dfaf741b2dac.png)

If you talk about this specific entity, I think it's hard to find anything about it... 😕

**Comment by MarkMpn** [comment]
It's an internal implementation detail for this table so there's no public docs available as far as I'm aware. We can find a little more with some digging:

```sql
SELECT entity.logicalname,
       entitydataprovider.name,
       solution.friendlyname,
       solution.publisheridname
FROM   metadata.entity
       LEFT OUTER JOIN
       entitydataprovider
       ON entity.dataproviderid = entitydataprovider.entitydataproviderid
       LEFT OUTER JOIN
       solutioncomponent AS sc
       ON entitydataprovider.entitydataproviderid = sc.objectid
       LEFT OUTER JOIN
       solution
       ON sc.solutionid = solution.solutionid
WHERE  entity.logicalname = 'aaduser'
       AND solution.ismanaged = 1
```

This shows us that it's a bespoke data provider specific for this entity called "AAD User Custom Data Provider" which is part of the "Metadata Extension" managed solution by Microsoft. Any further details are hidden within the implementation and you'd need to contact Microsoft support for more information.
