### ISSUE TITLE
Attributes missing from select attributes

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#668]
It is hard to find address attributes.
Can it be easier?

See the discussion.

### Discussed in https://github.com/rappen/FetchXMLBuilder/discussions/667

<div type='discussions-op-text'>

<sup>Originally posted by **ergobill** March  3, 2022</sup>
Latest version of Xrm Toolbox (v1.2022.2.54) and FetchXML Builder (1.2022.3.1)

simple account entity fetch   looking for Address 1 and Address 2 constituent fields. 

None showing in the Select Attributes Window.  
![image](https://user-images.githubusercontent.com/24599528/156592958-193e95c7-2032-4661-8495-bd28c8fb7c38.png)

no errors that I can find.</div>

**Comment by mtnmuncher** [comment]
Same issue exists for contacts
![fxb_address_fields_not_available_from_select_attributes1](https://user-images.githubusercontent.com/6696112/156762545-c880c89c-06a9-44e2-8e74-cf2f05c8fbe5.png)

**Comment by rappen** [comment]
Yes, because it is also stored in `customaddress` entity....
So we "know" how to see address attributes.
It would be nice to be easier...
Read the discussion to see how!

**Comment by mtnmuncher** [comment]
My only comment would be that, the fetch xml, generated by advanced find, can no longer be used in FXB.

For example, this XML, 
1. advanced find, include all contact address fields.
2. paste generated XML in FXB - see below.
3. Additional fields are added by selecting 'select attributes. After clicking 'ok' all address fields disappear.
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="contact">
    <attribute name="fullname" />
    <attribute name="contactid" />
    <attribute name="address2_utcoffset" />
    <attribute name="address2_upszone" />
    <attribute name="address2_telephone3" />
    <attribute name="address2_telephone2" />
    <attribute name="address2_telephone1" />
    <attribute name="address2_shippingmethodcode" />
    <attribute name="address2_primarycontactname" />
    <attribute name="address2_postofficebox" />
    <attribute name="address2_name" />
    <attribute name="address2_longitude" />
    <attribute name="address2_latitude" />
    <attribute name="address2_freighttermscode" />
    <attribute name="address2_fax" />
    <attribute name="address2_composite" />
    <attribute name="address1_utcoffset" />
    <attribute name="address1_upszone" />
    <attribute name="address1_telephone3" />
    <attribute name="address1_telephone2" />
    <attribute name="address1_shippingmethodcode" />
    <attribute name="address1_primarycontactname" />
    <attribute name="address1_postofficebox" />
    <attribute name="address1_telephone1" />
    <attribute name="address1_name" />
    <attribute name="address1_longitude" />
    <attribute name="address1_latitude" />
    <attribute name="address1_freighttermscode" />
    <attribute name="address1_fax" />
    <order attribute="fullname" descending="false" />
  </entity>
</fetch>

After selecting 'select attributes.
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="contact">
    <attribute name="fullname" />
    <attribute name="contactid" />
    <order attribute="fullname" descending="false" />
  </entity>
</fetch>

Also, I don't think there is an effective way to return a flat model of address1 and address2, by using customeraddress entity.

**Comment by rappen** [comment]
I see, I understand.
It does work pretty fine, if you have the right showing:
![image](https://user-images.githubusercontent.com/2572253/156881084-150fb3c5-2578-4dbf-a79d-723b54452801.png)

But I see we need it a bit better...
Working on it!

**Comment by rappen** [comment]
Selections:

![image](https://user-images.githubusercontent.com/2572253/163599268-fa2f35f9-7e7d-4242-bd7c-487e77f7f225.png)

Default: Checked (both)

**Comment by mtnmuncher** [comment]
I 'pulled' your latest, and verified the new 'addresses' worked successfully.

**Comment by rappen** [comment]
Good to hear!
It will be released in about a week.
Stay tuned....
