### ISSUE TITLE
Not sure what the issue is with this particular fetch. It appears correct to me.

### ISSUE THREAD

**Issue by JFulfordMS** [rappen/FetchXMLBuilder#674]
---
```
System.ServiceModel.FaultException<Microsoft.Xrm.Sdk.OrganizationServiceFault>:
Object reference not set to an instance of an object.

Server stack trace: 
- System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
- System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
- System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
- System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
- Microsoft.Xrm.Tooling.Connector.CrmServiceClient.RetrieveMultiple(QueryBase query)
- Cinteros.Xrm.FetchXmlBuilder.FetchXmlBuilder.<>c__DisplayClass134_0.<RetrieveMultiple>b__0(BackgroundWorker worker, DoWorkEventArgs eventargs)
- System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
- System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

---

```
<fetch top="1000" aggregate="true">
  <entity name="audit">
    <attribute name="createdon" alias="LastLogin" aggregate="max" />
    <filter>
      <condition attribute="operation" operator="eq" value="4" />
    </filter>
    <link-entity name="systemuser" from="systemuserid" to="objectid">
      <attribute name="fullname" alias="fn" groupby="true" />
    </link-entity>
  </entity>
</fetch>
```
---
- FetchXML Builder Version: 1.2022.2.54
- DB Version: 9.2.22015.131
- Deployment: Online

**Comment by MarkMpn** [comment]
The audit entity was modified recently so it no longer lives in SQL storage - https://powerapps.microsoft.com/en-us/blog/announcing-new-dataverse-auditing-features/

This limits the queries that it's possible to run against it. My guess is that this error is coming from the virtual table data provider that's being used behind the scenes here not understanding what otherwise looks like a valid FetchXML query, and not something you can avoid easily in your query.

**Comment by JFulfordMS** [comment]
Makes sense, I was afraid it was a quirk in the audit records. Thank you!
________________________________

Jordan Fulford
Manager, Software Development and Engineering
9000 Southside Blvd. Suite 1900, Jacksonville, 
FL 
32256
Phone: 
(904) 813-7771
 | 
Ext: 
334
Email: 
***@***.***
Need help with personal or business taxes? Visitwww.moneysolver.orgtoday.

This email message and any attachments to it, are for the sole use of the intended recipients, and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution of this email message or its attachments is prohibited. If you are not the intended recipient, please contact the sender by reply mail and destroy all copies of the original message. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, while the company uses virus protection, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.
