### ISSUE TITLE
Issue with date field

### ISSUE THREAD

**Issue by NithinVanam** [rappen/FetchXMLBuilder#678]
Hello,

I am having a strange issue when i use date/time fields in my fetch XML.

I have a date field "START_DATE" within an entity. Consider two different time stamps "2021-10-06T14:00:00Z" and "2021-10-07T00:00:00Z" . Both are UTC time stamps. The formatted value for both these values are "7/10/2021" as i am in AU timezone.

If i use advanced find to search for records where START_DATE eq 2021-10-07 i get records with both the time stamps. However if i use fetchxml builder, i only get records with "2021-10-07T00:00:00Z" and not the other. 

Any suggestions how do i handle this?

**Comment by MarkMpn** [comment]
Advanced Find uses the "on" operator, rather than "eq". This matches any value within that day, rather than only matching the precise instant.

If you change your operator in FetchXML Builder to "on" you should get the same behaviour.

**Comment by rappen** [comment]
Almost one year later...
Can you please ping me if this needs a fix?
If not, it will be closed soon.
