### ISSUE TITLE
Count is returned as 1 even when there is no record

### ISSUE THREAD

**Issue by rpprasanna1998** [rappen/FetchXMLBuilder#680]
When I tried to get the No of Contacts for each account. I am receiving the count as 1 for accounts which does not have contacts against it.

**Comment by rpprasanna1998** [comment]
Here is the query which I am trying

<fetch aggregate="true">
<entity name="account">
<attribute name="accountid" alias="AccountID" groupby="true" />
<attribute name="name" alias="AccountName" groupby="true" />
<link-entity name="contact" from="parentcustomerid" to="accountid" link-type="outer">
<attribute name="contactid" alias="ContactCount" aggregate="count" />
</link-entity>
</entity>
</fetch>

**Comment by rpprasanna1998** [comment]
<fetch aggregate="true">
<entity name="account">
<attribute name="accountid" alias="AccountID" groupby="true" />
<attribute name="name" alias="AccountName" groupby="true" />
<link-entity name="contact" from="parentcustomerid" to="accountid" link-type="outer">
<attribute name="contactid" alias="ContactCount" aggregate="count" />
</link-entity>
</entity>
</fetch>

**Comment by rpprasanna1998** [comment]
Here is the query
[FetchXML.txt](https://github.com/rappen/FetchXMLBuilder/files/8314747/FetchXML.txt)

**Comment by rappen** [comment]
Bah - Mark you beat me, was just answering the same 😉
Hope that's the answer for you @rpprasanna1998 !

**Comment by rpprasanna1998** [comment]
Thanks a lot @MarkMpn and @rappen for your help.
