### ISSUE TITLE
Feature request, copy url of row

### ISSUE THREAD

**Issue by RhINO-CRM** [rappen/FetchXMLBuilder#683]
Hi,

A nice feature would be the possibility to copy the url to the row rather than just opening the row in "your favourite browser". The reason is that that browser isn't always the one you want to use because you have many different environments you have to access.

Regards
Rickard

**Comment by rappen** [comment]
Right-click, possibility to Open and Copy the URL:

![image](https://user-images.githubusercontent.com/2572253/163054756-ad3eb2e1-1ce2-4ace-ab58-daf2bd464323.png)

If the column as a reference is selected, then you can Open and Copy the URL to the reference:

![image](https://user-images.githubusercontent.com/2572253/163055006-f0047f50-ad0f-434e-a2ac-ee02975a5119.png)

Note that single-clicks are changed to only double-click, both for entity and references (if clicking on the reverence column).
