### ISSUE TITLE
Turn off GUID drill through

### ISSUE THREAD

**Issue by eccountable** [rappen/FetchXMLBuilder#693]
This is a great tool, and it is much appreciated. Can you give me an option to turn off the drill-through on a GUID? The problem is that it goes to my default browser, which is not the one I use when I am configuring my clients environments. I need to copy the GUID so I can paste it elsewhere, not drill through. 

---
- Deployment: Online
- DB Version: 9.2.22031.144
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2022.2.54
- Tool Version: 1.2022.3.1

**Comment by rappen** [comment]
Good idea!
I will add that option to settings, both for "base" entity record and the "drill-through" records.

Note: see the new feature in XrmToolBox https://github.com/MscrmTools/XrmToolBox/discussions/1137

**Comment by rappen** [comment]
Because of #683, this will not be needed.
Issue #683 is implemented and also it now needs double-clicks to open the link.
If the https://github.com/MscrmTools/XrmToolBox/discussions/1137 is released, that will be awesome...
