### ISSUE TITLE
Cannot install because XRMToolBox says incompatible

### ISSUE THREAD

**Issue by ClintWoods** [rappen/FetchXMLBuilder#704]
Not sure whats up @rappen but on this new client's computer I am unable to install fetchxml builder. I tried the current version first, then a down version (2.54) and still no luck. All other tools installed.... just my favorite goto :-) is unable to load.
<img width="577" alt="FetchXML Builder not compatible" src="https://user-images.githubusercontent.com/67845398/165817976-320d13dd-754a-4d93-b412-a85746f60a9d.PNG">

**Comment by ClintWoods** [comment]
chatting with other Users at this client. they are using 2.54 and had no issues installing fetchxml builder. has to be a problem iwth my environment. Hope you have some pointers...

**Comment by MscrmTools** [comment]
Can you confirm your version of XTB?

**Comment by ClintWoods** [comment]
yes, I first tried 4.55 (new install, new computer). when that didn't work (same message as screen shot) i went back to 2.54 since that's working on my other computer

**Comment by ClintWoods** [comment]
OK. I surrender. I deleted older versions. Re-downloaded current (exactly as I did in the first place) and it's installed. Makes no sense whatsoever...

**Comment by rappen** [comment]
So I guess we should close this, right? 🙂

**Comment by ClintWoods** [comment]
yes. Sorry to keep you up. No idea what happened.

**Comment by rappen** [comment]
Anytime! 😊
