### ISSUE TITLE
Contains is not supported in FetchXml

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#708]
Error of Contains operator, here with a super simple query (see in the end).

*Related to #706*

[This docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.query.conditionoperator) says it should work, but give a SQL error, but this one gets a Fetch XML error, just 
*"Unknown Condition Operator: contains"*.

Tried some code to convert from `QueryExpression` to `FetchXml`.
Code:
```csharp
var query = new QueryExpression("kbarticle");
query.ColumnSet.AddColumns("title");
query.Criteria.AddCondition("content", ConditionOperator.Contains, "A");
var fetch = (Service.Execute(new QueryExpressionToFetchXmlRequest { Query = query }) as QueryExpressionToFetchXmlResponse).FetchXml;
```
I get a bit more info - it fails with exception 
*"Unknown Condition Operator: Contains. FetchXml does not support it"*.

Which seems to mean that some features work in QX, but not in Fetch. I know the reverse, but not this!
Are there more features supported in QX but not in Fetch? Is this documented? I am just a bad Binging person... 
Has @JimDaly any more info/link?

---

### Error message from FetchXML Builder below:

---
```
System.ServiceModel.FaultException<Microsoft.Xrm.Sdk.OrganizationServiceFault>:
Unknown Condition Operator: contains
mscorlib

Server stack trace: 
- System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
- System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
- System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
- System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
- Microsoft.Xrm.Tooling.Connector.CrmServiceClient.RetrieveMultiple(QueryBase query)
- Cinteros.Xrm.FetchXmlBuilder.FetchXmlBuilder.<>c__DisplayClass112_0.<RetrieveMultiple>b__0(BackgroundWorker worker, DoWorkEventArgs eventargs)
- System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
- System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

---

```xml
<fetch>
  <entity name="account">
    <attribute name="name" />
    <filter>
      <condition attribute="name" operator="contains" value="A" />
    </filter>
  </entity>
</fetch>
```
---
- XrmToolBox Version: 1.2022.4.55
- FetchXML Builder Version: 1.2022.4.1
- DB Version: 9.2.22041.157
- Deployment: Online

**Comment by JimDaly** [comment]
@rappen 
Looking at the [FetchXml Schema](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/fetchxml-schema#:~:text=%3Cxs%3AsimpleType%20name%3D%22operator%22%3E) I don't see a definition for `CONTAINS`.
We can see it is in the ConditionOperator used by QueryExpression. I expected to find it in the FetchXml Schema, but it isn't there.

**Comment by JimDaly** [comment]
`contains-values` and `not-contains-values` are relatively new to support multi-select optionsets.
Contains has been around a long time and is pretty much only used for certain KB articles attributes that have special indexing.  The error message is pretty clear, but I don't see it documented anywhere.
