### ISSUE TITLE
FetchXML Builder is in the "Not Compatible" list in XrmToolbox???

### ISSUE THREAD

**Issue by Geoff-RSM** [rappen/FetchXMLBuilder#720]
While helping a new XrmToolbox user, I couldn't find FetchXML Builder in the tool library.  Switched to my own install to double check, and I found that FetchXML Builder is now flagged as "Not Compatible" in the tool library.

![image](https://user-images.githubusercontent.com/82680066/169408787-6b831d55-245c-44b8-abae-ea192f31424d.png)

**Comment by BetimBeja** [comment]
Have you tried using the latest version of XrmToolBox?

**Comment by rappen** [comment]
FXB requires version 1.2022.4.55 (or later) of XrmToolBox.
Make sure you *always* update when available 🙂
We don't want to keep the buggy versions...

**Comment by Geoff-RSM** [comment]
Doh!  Thanks Jonas.   I’m glad that it was my error and not yours  😊.

Geoffrey Greene RSM US LLP D: 949.372.3597 I O: 949.255.6500 I E: ***@***.******@***.***>
