### ISSUE TITLE
operator='not-in' value=''

### ISSUE THREAD

**Issue by bwmodular** [rappen/FetchXMLBuilder#724]
When building a query which uses the 'in' or 'not-in' operator, FXB adds a redundant 'value' attribute in the condition node of the query.
![image](https://user-images.githubusercontent.com/1889586/171010667-11d85b41-df61-44ff-910b-9b75f4580d00.png)

Whilst CRM is quite forgiving of this and will run the query anyway, the "value=''" is redundant, and it causes FakeXrmEasy queries to fall over. Once you know this, it's easy to remove it from your query, but if it's possible to take it out in the first place, that would be great. It took me a while to work out what the problem was, so this might save other people some head-scratching too!
Thanks as ever for all your amazing work.

**Comment by rappen** [comment]
Ouch - thanks!
I will fix it...

**Comment by rappen** [comment]
Fixed earlier...
