### ISSUE TITLE
Great and nice tool 

### ISSUE THREAD

**Issue by saurabhtalele** [rappen/FetchXMLBuilder#727]
HI sir ,
I like this tool but while retriving record it will retrieving GUID also, I have made view only for T and U but in fetch XML its like below

T  |         U    |          Guid
10|          20  |        123
10 |          30  |        213
20 |           20   |       222

and a result I want to update my view like its sum in U group by T
T     |       U       
10 |         50      
20     |    20       

and while updating view in crm it will show 
![Screenshot 2022-06-07 141827](https://user-images.githubusercontent.com/61108851/172338364-39ee4844-361b-4df8-a99a-2a5fdbfbe152.png)

I am totally new to this

**Comment by rappen** [comment]
I feel quite stupid now...
What is T U?

You can right-click in the Result View, and uncheck the Primary Key column (the Guid of the retrieved records):
![image](https://user-images.githubusercontent.com/2572253/172342922-a9833c37-aa36-4f36-8454-4dca764f38e6.png)

**Comment by rappen** [comment]
If you open a view, and want to update the query, it is not possible if you change the column to return.
This tool can change the filter and link-entity etc, but not change the layout.

To query a sum U of T - you do it by aggregate on the fetch node. [Read more.](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/use-fetchxml-aggregation?WT.mc_id=BA-MVP-5002475)

This is not possible in Power Platform - too bad...

**Comment by saurabhtalele** [comment]
![1](https://user-images.githubusercontent.com/61108851/172346169-198858ac-94fc-4a94-bd91-6851b8b27c5d.png)
![2](https://user-images.githubusercontent.com/61108851/172346177-a28dcf10-4df8-4522-a453-612d855fa407.png)
![3](https://user-images.githubusercontent.com/61108851/172346183-da8a5cf6-b86e-43c2-ab4b-f3fb734b5caf.png)

**Comment by saurabhtalele** [comment]
sorry for T and U
1- view created
2- Now fetch in miraculous tool
3- miraculous tool give nice output Also

but while updating there was an error because of dynamics limitations am I thinking correctly????

![4](https://user-images.githubusercontent.com/61108851/172347176-2d80a268-cd4b-4200-af15-43b78ced171b.png)

**Comment by rappen** [comment]
Yes, sorry... 😕
Dynamics: You can't aggregate in the plain views (you need to create a dashboardetc)
FXB: It can't update the layout (which columns to show etc), only the query and filter etc.

**Comment by rappen** [comment]
Nothing to fix, closing.
Reopen please if you want me to do more!
