### ISSUE TITLE
 operator="does-not-contain-values" should be operator="not-contain-values" 

### ISSUE THREAD

**Issue by Keppel-M** [rappen/FetchXMLBuilder#752]
operator="does-not-contain-values"  does not work for multi choice picklist. The correct operator seems to be

 operator="not-contain-values"

**Comment by provaj** [comment]
Just joined Github to confirm that this issue is still there.

- XrmToolBox Version: 1.2023.1.60
- FetchXML Builder Version: 1.2022.11.2
- DB Version: 9.2.22122.158
- Deployment: Online

**Comment by rappen** [comment]
Note: related to #708
