### ISSUE TITLE
FetchXML For Insert ?

### ISSUE THREAD

**Issue by amineKL** [rappen/FetchXMLBuilder#772]
Can i use FetchXML API to insert Data in Dynamics or only it's used for Queries ?
If Yes can you send me an example or a link.

Thanks.

**Comment by rappen** [comment]
Sorry, with [FetchXML](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/use-fetchxml-construct-query?WT.mc_id=BA-MVP-5002475) you can only read. Just like Select.
You can try [Mockaroo Data Munger](https://www.xrmtoolbox.com/plugins/LinkeD365.MockarooDataMunger/) instead!
