### ISSUE TITLE
Using valueof also includes value in generated FetchXml which makes generated query invalid (always returns zero results)

### ISSUE THREAD

**Issue by ColinCMillar** [rappen/FetchXMLBuilder#773]
When using the valueof condition type, the generated FetchXML adds in both a "value" AND a "valueof" attribute. This means that the query for all valueof conditions returns no results.

For example:

![image](https://user-images.githubusercontent.com/25770507/186668118-69470969-9607-424c-b0ab-10e80545868d.png)

Many thanks for the otherwise excellent tool.

**Comment by rappen** [comment]
Aouch!
That will be fixed for next release!
