### ISSUE TITLE
Linked Entity columns not displaying in result - could be 'alias'

### ISSUE THREAD

**Issue by mtnmuncher** [rappen/FetchXMLBuilder#775]
The attached fetch did not show linked entity columns, until I assigned an alias.

![fxb_linked_entity_columns_not_displaying](https://user-images.githubusercontent.com/6696112/186946294-18a708c4-a019-442d-b1c6-e662ad622fe2.png)

![fxb_linked_entity_columns_not_displaying_fetch](https://user-images.githubusercontent.com/6696112/186947187-bdaf4e02-c7f9-4c04-86c5-8fea4d99832f.png)

**Comment by rappen** [comment]
That's true, if you have checked the "Layout feature" - it needs alias for the link-entities to work.
I might need to add this to the docs...
