### ISSUE TITLE
Unable to select 'index' or 'primary key' columns

### ISSUE THREAD

**Issue by mtnmuncher** [rappen/FetchXMLBuilder#778]
![image](https://user-images.githubusercontent.com/6696112/188471671-2d67e96d-41d7-4cce-abaa-f1c2c14a2384.png)

**Comment by rappen** [comment]
You can - if you unclick this Settings options feature.

![image](https://user-images.githubusercontent.com/2572253/188472806-71f2516f-900f-4029-92a5-4232156754a8.png)

Which columns to show is always done in the layouts, without working with layouts it works in that "old way".

The *Index* is not there in the data, it's only a number to see row number.
To see the *Primary Key Id*, add it to the attributes in the query.
