### ISSUE TITLE
Working off xml view feature no longer available?

### ISSUE THREAD

**Issue by tsu-dev** [rappen/FetchXMLBuilder#782]
In the old version of fetchxml builder, I can enter the xml query directly in xml view, the query on left panel will update itself and I can run the query directly.  I can also make changes directly in xml view and the change will be reflected on the query view.  It seems like xml view no longer update the query, is there somewhere in setting where I can re-enable this feature?

**Comment by rappen** [comment]
I don't think this has been changed...
Check this checkbox (down left in the FetchXML view).

![image](https://user-images.githubusercontent.com/2572253/190612027-a56235e6-6128-42c2-b866-d9751e04eaa4.png)

If it is checked, the Query Builder (what you said as "left panel") will be updated automatically.
If you don't check that box, it will update the Query Builder when you click the OK button, right in the FetchXML view.

**Comment by tsu-dev** [comment]
seems to be working now, thank you for your help.
