### ISSUE TITLE
Exception after updating to latest XrmToolbox

### ISSUE THREAD

**Issue by bo-stig-christensen** [rappen/FetchXMLBuilder#791]
I have the latest version of FetchXML Builder and want to update XrmToolbox to the latest version, but get this error:
![image](https://user-images.githubusercontent.com/6851915/194327303-29d67d27-62f3-4d62-aa2b-88a13064c9b9.png)

Anyone else able to reproduce this?

**Comment by rappen** [comment]
Old (non-)problem is now introduced in XrmToolBox, the solution is here (and many other issues)
https://github.com/MscrmTools/XrmToolBox/issues/1168

**Comment by bo-stig-christensen** [comment]
Ah okay..... so they were actually old unused files..... Maybe XTB should implement better clean-up then ;-)

**Comment by rappen** [comment]
Yep! 😉
