### ISSUE TITLE
no-lock property of FetchXml not 'translated' to QueryExpression

### ISSUE THREAD

**Issue by bwmodular** [rappen/FetchXMLBuilder#800]
Just a little one...
When 'no-lock' is specified in a fetchXml query, it should also appear in the resulting QueryExpression:
![image](https://user-images.githubusercontent.com/1889586/196447735-60eaf18e-28fe-45d3-a5a7-8dd91a754e30.png)

**Comment by rappen** [comment]
Goodie. Thanks.
Docs (for my fixing): https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.query.queryexpression.nolock
Find in which version it was added to the `QueryExpression`.

**Comment by bwmodular** [comment]
Brilliant, thanks 🙏
