### ISSUE TITLE
Export to Excel would be a nice feature

### ISSUE THREAD

**Issue by jdenicola-pa** [rappen/FetchXMLBuilder#801]
Exporting the Result View to Excel would be a nice feature.

The ClosedXML library lets you implement this nicely and doesn't require Excel. I've used it on a few projects.

https://github.com/ClosedXML/ClosedXML

**Comment by rappen** [comment]
Thanks for the idea, and link!

For now, you can easily:
1. Select the data in Result View
2. `<CTRL> + A` to select everything
3. `<CTRL> + C` to copy it
4. Start new Excel
5. `<CTRL> + V` to paste it

Note that you can get the headers included or not, with this setting in the bottom-left of the Result View.
![image](https://user-images.githubusercontent.com/2572253/197976179-b8ae70b8-592e-4bea-bcee-faa392f89bcd.png)

**Comment by rappen** [comment]
See also #132

**Comment by alex-mcla** [comment]
Hi Jonas

If you come to implement this, it would be great to export into an Excel table.

I'm often copying, pasting into Excel, turning word wrap off, then convert to table.

Kind regards, Alex

**Comment by rappen** [comment]
I didn't use ClosedXML, instead I'm using `Microsoft.Office.Interop.Excel` library.
Hope that's okay :)
