### ISSUE TITLE
Non distinct query on 1:N doesn't return all columns

### ISSUE THREAD

**Issue by paultisski** [rappen/FetchXMLBuilder#804]
If you query two tables with a 1:N relationship then it doesn't return columns from the table that is on the many side of the relationship.  If you run the same code in Fetch XML tester then it does return the columns.
So it seems it is only returning distinct records even though distinct isn't specified.
I've looked through all the settings but can't find anything to change this.
Any help would be appreciated, thanks.

**Comment by rappen** [comment]
This is as intended...
Since Dynamics requires an alias on the link-entity, to be able to display the related columns.
I know, there is bad info, will be better for next version!

Please reopen if you have more issues with this!

**Comment by paultisski** [comment]
Seems obvious now you mention it!  Thanks for the info
