### ISSUE TITLE
Only the first 5000 views are retrieved from Dataverse

### ISSUE THREAD

**Issue by ryanspain** [rappen/FetchXMLBuilder#831]
# Problem
When the **Select View** dialog data is being hydrated, only the first 5000 views from the target environment are retrieved, order descending by name. This leaves view 5001+ excluded from the **View** selector.

![image](https://user-images.githubusercontent.com/8723433/205087992-0b4e1c07-5c0c-4ab9-be5a-2a287c2f70e6.png)

I'm working in an environment that has over 5000 views (`savedqueries`). I need to name my views wisely to have them appear in Fetch XML Builder :)

# Cause
The [RetrieveMultiple(QueryBase query)](https://github.com/rappen/FetchXMLBuilder/blob/a369798dfe136d46b3f3c715967b2ce1639051d3/FetchXmlBuilder/FXBQueries.cs#L22) called by [LoadViews](https://github.com/rappen/FetchXMLBuilder/blob/a369798dfe136d46b3f3c715967b2ce1639051d3/FetchXmlBuilder/FXBQueries.cs#L103) in FXBQueries.cs is handing off to the service clients `RetrieveMultiple` method which by default does not handle pagination where more results exist.

# Solutions
I see 2 solutions here:
1. Update the [LoadViews](https://github.com/rappen/FetchXMLBuilder/blob/a369798dfe136d46b3f3c715967b2ce1639051d3/FetchXmlBuilder/FXBQueries.cs#L103) to use a Fetch XML query to retrieve system views by making use of [RetrieveMultiple(string fetch)](https://github.com/rappen/FetchXMLBuilder/blob/a369798dfe136d46b3f3c715967b2ce1639051d3/FetchXmlBuilder/FXBQueries.cs#L257) instead of the `QueryBase` version.
2. Update the [RetrieveMultiple(QueryBase query)](https://github.com/rappen/FetchXMLBuilder/blob/a369798dfe136d46b3f3c715967b2ce1639051d3/FetchXmlBuilder/FXBQueries.cs#L22) method to support pagination as described in [Working with more than 5,000 records in Dynamics 365
](https://promx.net/en/2020/02/working-with-more-than-5000-records-in-dynamics-365/). Note it would only need to work for `QueryExpression` and `QueryByAttribute` types.

# Next steps
I'm happy to submit a PR to address this. Thoughts?

**Comment by rappen** [comment]
Ah. Nice bug found.
I'd love a PR!

Will your PR give more/better than this? 😉
(Sorry, I had to find an easy solution...)

![image](https://user-images.githubusercontent.com/2572253/205296003-792e2ca4-127d-4fa9-931f-daf0b5c910f2.png)
![image](https://user-images.githubusercontent.com/2572253/205296103-0485a920-44ae-4e40-ab5c-a65716ed5ea0.png)

**Comment by rappen** [comment]
Just wondering... Why do you have 5000+ views?? 😲

**Comment by ryanspain** [comment]
@rappen, it might be easier to just use Fetch XML to retrieve the views because pagination already implemented in [RetrieveMultiple(string fetch)](https://github.com/rappen/FetchXMLBuilder/blob/a369798dfe136d46b3f3c715967b2ce1639051d3/FetchXmlBuilder/FXBQueries.cs#L257) as the default behavior. The query isn't complex.

But I'm also in favor of updating [RetrieveMultiple(QueryBase query)](https://github.com/rappen/FetchXMLBuilder/blob/a369798dfe136d46b3f3c715967b2ce1639051d3/FetchXmlBuilder/FXBQueries.cs#L22) to, by default, include all records. Less records can be returned by setting the `PageInfo.Count` for the query being passed in. The need for an `allRecords` flag or similar could then be removed.

I have an `IOrganizationService.RetrieveMultipleRecursively(QueryBase query)` extension method I use for scenarios like this. It could be dropped into [RetrieveMultiple(QueryBase query)](https://github.com/rappen/FetchXMLBuilder/blob/a369798dfe136d46b3f3c715967b2ce1639051d3/FetchXmlBuilder/FXBQueries.cs#L22).

I'll work on a PR for this at the weekend.

**Comment by ryanspain** [comment]
If I can figure out why there are 7079 views in this environment @rappen, I'll let you know.

For now, it remains a mystery 🔮

**Comment by rappen** [comment]
I guess your extension is like this, right?
https://github.com/rappen/Rappen.XTB.Helper/blob/main/Rappen.XRM.Helpers/Extensions/ServiceExtensions.cs#L51-L79

**Comment by ryanspain** [comment]
Exactly. I guess that makes this easier given this repo references `Rappen.XRM.Helpers` as a submodule! Nice one.

**Comment by rappen** [comment]
So I go back to my previous suggestion.... 😉
