### ISSUE TITLE
FetchXML view No Power Automate Parameters

### ISSUE THREAD

**Issue by CarsonO1** [rappen/FetchXMLBuilder#834]
Hi, I am trying to get the parameters from D365 CRM for a PA Flow. But I cannot see the Power Automate Parameters that all of the instructions and tutorials talk about. There is no documentation that I was able to find that shows this problem and a solution. Please help me activate it. Thanks.

![image](https://user-images.githubusercontent.com/119898875/205751804-f42bacf5-4cbc-4304-b973-4f8a607afbac.png)
![image](https://user-images.githubusercontent.com/119898875/205751832-9b1de14d-25f1-4b8c-a202-c2373dbe88a0.png)
![image](https://user-images.githubusercontent.com/119898875/205751840-ce8228df-c2f8-48ee-bdd2-f46d06d17666.png)

**Comment by rappen** [comment]
It is active. This is a very appreciated feature, it will never be removed, I promise.

I just improved the menu a bit, this is not in the "View" menu, but in the "Convert" menu.
I never remove features - I add features! 😉

Still find it also with `<CTRL>+<ALT>+P`

![image](https://user-images.githubusercontent.com/2572253/205859324-1ff4f7a3-8861-40f4-ba6f-9e5c2f30659c.png)

**Comment by rappen** [comment]
I'm curious about "all of the instructions and tutorials" that you wrote, any links to share? 🙂
