### ISSUE TITLE
Two related Entity Filter

### ISSUE THREAD

**Issue by donalmc** [rappen/FetchXMLBuilder#858]
I can create a view with a filter as follows: User has Security Role "Team Member"
And I can create another view like: User is a member of a Team with Security Role "Team Member"

Is it possible to create an Or to join these
User has Security Role "Team Member"
OR
User is a member of a Team with Security Role "Team Member"

I don't think so but just checking!

**Comment by BetimBeja** [comment]
So you can create this using FetchXML but the tool does not allow you to create it?
If that is not the case I think this is not the right place to ask the question. 😵 
The audience here is more focused on the capabilities of the tool. I think StackOverflow or Microsoft Forums are more suitable for this question.

**Comment by rappen** [comment]
Unfortunately, I agree with @BetimBeja - I don't own the query technology, I only own this tool to help you all out there.
Please search StackOverflow or other communities!
I wish you luck 🙂
