### ISSUE TITLE
Cannot update to version 1.2022.11.2 looping between Restart and Update available

### ISSUE THREAD

**Issue by DMaxwell02** [rappen/FetchXMLBuilder#860]
I tried several times to update FetchXMLBuilder to the latest version 1.2022.11.2 from 1.2022.5. 

In the Tool Box I select FetchXMLBuilder and click on "Install". The prompt to restart comes up and I accept it. XrmToolBox restarts and I am presented with the same prompts again. 

I tried unistalling it and installing it new. It seems to revert back to the previous version and cannot update to the latest version. I do not see any error messages nor am I sure where to find a log.

**Comment by MscrmTools** [comment]
Sûre! Trying it right now

**Comment by MscrmTools** [comment]
In any case, you can revert to legacy tool library in XrmToolBox settings. That might unblock you

**Comment by MscrmTools** [comment]
@DMaxwell02 what is your version of XrmToolBox, btw?

**Comment by kschepperly** [comment]
I had the same issue today while trying to update from 1.2022.11.2 to 1.2023.2.2. It would remain at the old version 1.2022.11.2 and offer an update but persisted in the same unsuccessful loop. I've outlined my troubleshooting steps below with the fix that worked for me, **_clearing packages cache_** in XrmToolBox. 

**XrmToolBox: v1.2023.1.63**

### Troubleshooting:
***
####  Attempt 1 👎 
   **Steps**
   1. Downgrade to 1.2022.5.1.
   2. Restart XrmToolBox.
   3. Upgrade to 1.2023.2.2.
   
   **Result**
   ❌ Remained at 1.2022.5.1.
***
####  Attempt 2 👎 
   **Steps**
   1. Completely uninstall FetchXMLBuilder.
   2. Restart XrmToolBox.
   3. Install 1.2023.2.2.
   
   **Result**
   ❌ Remained at 1.2022.5.1.
***
####  Attempt 3 👍  
   **Steps**
   1. From XrmToolBox menu navigate to > Configuration > Tool Library > Advanced > 🥇 Clear Packages Cache 🥇.
   2. Restart XrmToolBox.
   3. Install 1.2023.2.2.
   
   **Result**
   ✔️ Successfully updated to current version 1.2023.2.2.
***

**Comment by rappen** [comment]
I believe this is now fixed (@MscrmTools did something in his portal).
I'll close this now - please reopen if still see the problem!
Thanks @kschepperly for great report info!
