### ISSUE TITLE
Typo on Share Query Link

### ISSUE THREAD

**Issue by MarcRohde** [rappen/FetchXMLBuilder#868]
There is a typo on the "Share Query Link" that says "Link Titel" rather than "Link Title"

![image](https://user-images.githubusercontent.com/15810225/220187559-6a3a1e45-48ac-432d-8faf-317ba153d01d.png)

**Comment by rappen** [comment]
I'm blaming that darn aphasia! 😂
Thanks for finding my typo 🙏

(Actually, I believe if type it in Swedish, it's spelled like that. Maybe...)
