### ISSUE TITLE
Use primary constants from EBG

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#869]
Use these:
```
PrimaryIdAttribute
PrimaryNameAttribute
```

Q: is this created only in EBG, or a general feature in the CrmUtils? Ping @daryllabar

---
- Deployment: Online
- DB Version: 9.2.23014.178
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.1.63
- Tool Version: 1.2023.2.2

**Comment by daryllabar** [comment]
It used to be only in the EBG.  But I haven't had time to use the new features in the PAC
