### ISSUE TITLE
Friendly Names

### ISSUE THREAD

**Issue by dmkweima** [rappen/FetchXMLBuilder#882]
Hello,

 I would like to know what FetchXML is required to render the results I get when Friendly Names us enabled. My results are what I need but the FetchXML code doesn't render those results. 

Its Business Unit with the name attribute displayed rather than the busniessunitid. 

Thanks
Dean Krueger

**Comment by rappen** [comment]
Hi

I hope you like code, to see how I get the Friendly Names... 🤓

Start in this repo: https://github.com/rappen/Rappen.XTB.Helper/

Details in the `XRMDataGridView` is here: https://github.com/rappen/Rappen.XTB.Helper/blob/18166e771343e7419a84dea7f8b11d236d34f817/Rappen.XTB.Helpers/Controls/XRMDataGridView.cs#L841-L851

This is calling the `AttributeToString` method: https://github.com/rappen/Rappen.XTB.Helper/blob/18166e771343e7419a84dea7f8b11d236d34f817/Rappen.XRM.Helpers/Serialization/EntitySerializer.cs#L384-L452

Click on from there...

Summary: it's not one only in FetchXML.

**Comment by rappen** [comment]
Another way to get what you need is probably a looot easier....

Don't only get these query:
```
<fetch>
  <entity name='account'>
    <attribute name='name' />
    <attribute name='owningbusinessunit' />
  </entity>
</fetch>
```
But get the actual name from the related Business Unit:
```
<fetch>
  <entity name='account'>
    <attribute name='name' />
    <attribute name='owningbusinessunit' />
    <link-entity name='businessunit' from='businessunitid' to='owningbusinessunit' alias='B'>
      <attribute name='name' />
    </link-entity>
  </entity>
</fetch>
```
Result now shows their name also:
![image](https://user-images.githubusercontent.com/2572253/225285122-1299abbd-2125-4e9a-9ca0-92d7c25c670a.png)

(ok, boring "name" of the BU, sorry about that in my environment)

**Comment by rappen** [comment]
Related to this improvement: https://github.com/rappen/Rappen.XTB.Helper/issues/31

**Comment by dmkweima** [comment]
The Friendly Name is great, would be even greater to be able to see the XML required to generate the XML that I see when Friendly Names is on. IE I am trying to pull a few fields that are Choice fields in the Dataverse. When I return the Dynamics field, I am getting the number Value rather than the Lable. Your Friendly Names shows it correctly, but of course the code only renders out the number. 

I have looked all over the internet to try to get the syntax to do this.

![image](https://github.com/rappen/FetchXMLBuilder/assets/105314547/b58ddec3-cdf5-42b5-938e-5aa7cd2fc808)
 
Can it be done with a filter or link-entity? Sorry, this is new to me.

Thanks
Dean

**Comment by rappen** [comment]
Ah, sorry... the "Friendly names" of choices, for example, is not found in the fetch XML. You have to query the metadata to get them. Might be a bit difficult, that is why I have done it in my controls to show meta-related info automagical.

**Comment by dmkweima** [comment]
I have to return the "Choice" Label name in my FetchXML. Are you saying this is not possible using FetchXML?

I know if I was using C# I could make it happen, but I am limited to returning all the data in FetchXML syntax.

Thank you!
Dean

**Comment by rappen** [comment]
![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/ce23c469-a6ce-4838-8547-f71406ec7f02)

![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/90b9487e-552b-4455-86a0-5f4844d537b6)
