### ISSUE TITLE
The fetch is duplicated and Fetch builder not updated. 

### ISSUE THREAD

**Issue by StephaneSeguin** [rappen/FetchXMLBuilder#886]
When modifying the Fetch directly, the query builder doesn't, recognize it. 

The builder also duplicated the Query builder,  even if it doesn't show in the Fetch. 

![image](https://user-images.githubusercontent.com/11836747/226688440-604469e7-3abf-4be2-b13a-bf85ececcc33.png)

**Comment by rappen** [comment]
Can you make sure the query is correct?
I can see that it ends with `</filter><link-entity /></entity></fetch>` twice.
When the query is not a correct XML, it will not understand it and update the Query Builder.
When the query is ok, the Query Builder *should* look okay.

**Comment by rappen** [comment]
No response, so I'll close this issue. Reopen if you have more info.
