### ISSUE TITLE
Update issue 

### ISSUE THREAD

**Issue by siggipop** [rappen/FetchXMLBuilder#887]
I Experienced issue updating to the latest 1.2023.2.2 version of FetchXml Builder via XRMToolBox (v 1.2023.2.64). 

The issue occurs after updating to 1.2023.2.2 (see picture) 

![FetchXML update 1](https://user-images.githubusercontent.com/16526932/227191830-0802289f-4eb0-4f05-8ddd-0b52bbfeb262.png)

After the update, the current version jumps back to version 1.2022.5.1! (se picture)

![FetchXML after update](https://user-images.githubusercontent.com/16526932/227191875-33643870-43b2-4605-9887-4a9adf25a49e.png)

**Comment by rappen** [comment]
I've seen that too, but not in the latest version of XrmToolBox.
Maybe @MscrmTools can understand or help investigate?

**Comment by MscrmTools** [comment]
I will help investigate, for sure... I don't understand it yet...

**Comment by MscrmTools** [comment]
It does work at home... 
@siggipop can you try to install, let's say, version 1.2022.11.2, restart, then install latest version. 
How does it do? are you on the latest version of still on an older version?
If still older version, can you try to clear your cache ? and try again
![image](https://user-images.githubusercontent.com/10774317/228304944-fdf384cd-9e13-4479-951b-89233a93cfcb.png)

**Comment by siggipop** [comment]
Ok, it worked after i "Cleared Packages Cach". 

I also tried these things that didn't worke:

Downgrade to plugin version 1.2022.11.2 (even 1.2022.5.1) and upgrade iteratively up again to 1.2023.2.2
Downgrade XRMToolBox to v1.2022.11.59 -> upgrade to latest XRMToolBox , then upgrade plugin to 1.2023.2.2

**Comment by siggipop** [comment]
Ok, it worked after i "Cleared Packages Cach".
