### ISSUE TITLE
Loading the LayoutXml Truncated Special Attributes in Cell Element

### ISSUE THREAD

**Issue by LinnZawWin** [rappen/FetchXMLBuilder#889]
1. Click Open > Open View and select **Sharepoint Document** entity and **Document Associated Grid** view.
2. Click View > LayoutXML
3. The LayoutXML is loaded with the special attributes missing (imageproviderfunctionname, imageproviderwebresource, ishidden). Additionally, the hidden cells with ishidden="1" are replaced by the default width='100'

![image](https://user-images.githubusercontent.com/14156926/230491679-a7bc6e85-7c70-4f10-9253-5a34ae54f75e.png)
_Original LayoutXML on the left and the LayoutXML loaded by FXB_ 

Expected results: The LayoutXML is loaded as it is stored on the server.

---
- Deployment: Online
- DB Version: 9.2.23032.180
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.2.64
- Tool Version: 1.2023.2.2

**Comment by rappen** [comment]
Oh, I didn't know about [these properties](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/customize-entity-views?WT.mc_id=BA-MVP-5002475#add-custom-icons-with-tooltip-for-a-column)!
I've only focus on with and order of the columns.
I see I need ta take care of more properties, not to break existing view.

![image](https://user-images.githubusercontent.com/2572253/230566107-c87adf8c-6094-4ecf-a7b0-927a2d35e658.png)

Currently it is only looking at width, if it is not there, it will default to 100px.
I'll probably change `width=0` to `ishidden=1`.

Thanks!

**Comment by rappen** [comment]
I'm now handling attribues:
* name
* width
* ishidden
* disableSorting
* imageproviderfunctionname
* imageproviderwebresource

...not the other seen above.
