### ISSUE TITLE
Forcing a Metadata update

### ISSUE THREAD

**Issue by BenediktBergmann** [rappen/FetchXMLBuilder#897]
It would be nice to have the possibility to force a Metadata update without the need of closing the XrmToolBox (XTB).

Example Scenario:
I open the XTB and create some queries using Fetch XML Builder (FXB). While XTB is still open I create a new table or a column on an existing table. To be able to use the newly created table/column I have to close the XTB and reopen it so that the Metadata is updated. This costs time especially because I might have to recreate all queries.

I also created the same issue in the XTB Repo
https://github.com/MscrmTools/XrmToolBox/issues/1256

**Comment by rappen** [comment]
See also discussion #934.
