### ISSUE TITLE
The 'RetrieveMultiple' is only allowed to be accessed from OData endpoint in Dataverse for Teams offering

### ISSUE THREAD

**Issue by xunyicjq** [rappen/FetchXMLBuilder#900]
The 'RetrieveMultiple' is only allowed to be accessed from OData endpoint in Dataverse for Teams offering

**Comment by xunyicjq** [comment]
When I use FetchXMLBuilder to assist in writing FetchXML statements for Dataverse for Teams, it produces this error message. I don't know whether it will be fixed later on.

**Comment by rappen** [comment]
Currently, Microsoft don't allow the CRM SDK to work with Dataverse for Teams.
I'm not sure if they will allow us in the future.
Probably @mscrmtools has some more info?
