### ISSUE TITLE
Linked Entity Column names are empty when Saved as view in D365

### ISSUE THREAD

**Issue by MrHosz** [rappen/FetchXMLBuilder#913]
Tried multiple XRMTB versions, but result is the same.

1. When adding a column/ attribute from a linked entity from a linked entity (aka the parent of the parent) the result is as expected, the column is showing data. 
2. When adding an alias to that same column, the data (and new name of the column) is also showing in the result
3. When Saving this as a new view in D365 the Columns are empty. So the name of the column and data is empty.
4. When removing the alias from the column in XRMTB and save the change back to the view in D365, the data is shown in the results of the advanced find in D365, but the name is missing/ empty.

Could this be a bug/ issue in the view maker in D365 or is this something that is result from XRMTB?

Found this in Dynamicsforum from 2020: https://community.dynamics.com/365/sales/f/dynamics-365-for-sales-forum/399592/custom-fetchxml-query-column-not-shown-in-view

---
- Deployment: Online
- DB Version: 9.2.23051.240
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.2.64
- Tool Version: 1.2022.8.1

**Comment by rappen** [comment]
I had to dig down into my email archive... and found this is still open.
I had similar issues (actually exactly the same issue), and I will keep track of the updates and share (what I can that is not NDA).

My attempt was to have this query:
```
<fetch>
  <entity name='rapp_rocket'>
    <attribute name='rapp_rocketid' />
    <attribute name='rapp_name' />
    <link-entity name='contact' from='contactid' to='rapp_designer' link-type='outer' alias='designer'>
      <attribute name='lastname' />
      <link-entity name='account' from='accountid' to='parentcustomerid' link-type='outer' alias='designaccount'>
        <attribute name='websiteurl' />
      </link-entity>
    </link-entity>
  </entity>
</fetch>
```
And I see the results, but with empty column name:
![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/8db3cadd-5feb-4938-87b3-3ff01d454caa)

**Comment by menegator** [comment]
I have also the same problem, found no solution. I don't think that this is FetchXML Builder's problem though

**Comment by rappen** [comment]
Closing this issue now, please reopen if we have more info, probably from MS.
