### ISSUE TITLE
Sökbarhet på tabellnivå

### ISSUE THREAD

**Issue by ChriPalm** [rappen/FetchXMLBuilder#925]
[Write your comment/feedback/issue here]

Hej
Jag skulle tycka att vore en grym funktion om man kan göra en fritextsökning.
Ibland har ju en entitet ett namn typ som **All Event**
Om jag då säker på Event så får jag ingen träff. 

Har testat att söka med %E, *E, $E men det gick inte insåg jag :) 

---
- Deployment: Online
- DB Version: 9.2.23053.234
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.6.65
- Tool Version: 1.2023.2.2

**Comment by rappen** [comment]
Duplicate with #964.
Closing this one (since it's written in Swedish...)
Stay tuned to progress in #964!
