### ISSUE TITLE
Possible "Me" problem, possible update problem

### ISSUE THREAD

**Issue by thomassandsor** [rappen/FetchXMLBuilder#928]
When trying to update to 1.2023.2.2 I end up in infinite loop. I click update now. It says "restart XrmToolBox", I restart and the update box appears again. It doesn't seem to overwrite the current installation file. 

Could be something local on my PC of course.

**Comment by rappen** [comment]
You have latest greatest version of XTB?
Should be 1.2023.6.65.

If still problem - can you start with uninstalling this tool? Right-click in the  Tools list.

![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/32d4b6d4-6e9c-4657-bd0b-01983630dffb)

...and then install it again.

**Comment by thomassandsor** [comment]
It was a me problem. Something was wrong with my XrmToolBox. I uninstalled it all and removed all files from my profile, and now I was able to install. Before I could click the install, get the green light and still it wasn't there.. Something buggy:) 

Tnx for help:)

**Comment by rappen** [comment]
De nada!
