### ISSUE TITLE
Power Automate parameters missing single quotes for GUIDs

### ISSUE THREAD

**Issue by Roland80** [rappen/FetchXMLBuilder#933]
When you convert a FetchXML to Power Automate parameters and a filter contains a lookup to a specific record, the GUID is missing single quotes.
Example FetchXML:
```
<fetch>
  <entity name="account">
    <filter>
      <condition attribute="accountid" operator="eq" value="3fee3d59-68c9-ed11-b597-0022489b41c4" uitype="account" />
    </filter>
  </entity>
</fetch>
```

Example Filter parameter:
`(accountid eq 3fee3d59-68c9-ed11-b597-0022489b41c4)`

The List rows action expects there to be single quotes around the GUID, as it's a string-type column rather than an integer.

**Comment by rappen** [comment]
Will look into this issue. 👍

**Comment by MarkMpn** [comment]
Sorry, that shouldn’t have auto-closed just yet. Fix is done in the upstream package, will get a PR shortly to include it in FXB

**Comment by rappen** [comment]
Fixed in submodule by @MarkMpn.
