### ISSUE TITLE
Broken dependency in Nuget package

### ISSUE THREAD

**Issue by SebBoulet** [rappen/FetchXMLBuilder#947]
The NuGet package has a dependency on the XmrToolBox package but it is (no longer?) available: 

![image](https://github.com/rappen/FetchXMLBuilder/assets/1759968/d65e88f0-ae95-4905-ae70-e0d5e5bfa7ff)

This is preventing the download and installation of the package though the NuGet Package Manager.

Step to reproduce:
 * using the nuget CLI application (https://www.nuget.org/downloads)
 ```
C:\Temp\poi> nuget install Cinteros.Xrm.FetchXMLBuilder
Feeds used:
  https://api.nuget.org/v3/index.json

Installing package 'Cinteros.Xrm.FetchXMLBuilder' to 'C:\Temp\poi'.
  GET https://api.nuget.org/v3/registration5-gz-semver2/cinteros.xrm.fetchxmlbuilder/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver2/cinteros.xrm.fetchxmlbuilder/index.json 188ms


Attempting to gather dependency information for package 'Cinteros.Xrm.FetchXMLBuilder.1.2023.2.2' with respect to project 'C:\Temp\poi', targeting 'Any,Version=v0.0'
Gathering dependency information took 233 ms
Attempting to resolve dependencies for package 'Cinteros.Xrm.FetchXMLBuilder.1.2023.2.2' with DependencyBehavior 'Lowest'

 Unable to resolve dependency 'XrmToolBox'. Source(s) used: 'nuget.org'.
```

**Comment by SebBoulet** [comment]
Yes, essentially our proxy is blocking the XmrToolBox's tool library, but it allows access to the GitHub repository. Unfortunately, the broken reference is causing the import of the .nupkg into our local repo to fail.
I was wondering if it would be worth removing the reference from the .nuspec ?

**Comment by rappen** [comment]
If you want to install FetchXML Builder, you can install it manually, see https://fetchxmlbuilder.com/manual-installation/
If it's from all tools, I refer you to https://github.com/MscrmTools/XrmToolBox/issues/
