### ISSUE TITLE
Updating fields to be shown not working in latest version

### ISSUE THREAD

**Issue by menegator** [rappen/FetchXMLBuilder#954]
In the latest version updating fields to be shown is not working. If I want to add a field I have to paste again the new FetchXML into a new tab.

**Comment by rappen** [comment]
Can you try to "Reset Layout" in the bottom of the Result view?
![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/c24560db-ac0f-42ac-8fd2-0245f5436da2)

Can you give me more info? I can't reproduce the issue currently.

**Comment by rappen** [comment]
Hopefully these features show solve you problem... See #962

**Comment by rappen** [comment]
Closing this issue, probably works better from version 1.2023.8.2.
Please reopen if needed!
