### ISSUE TITLE
Activity Status Reason displays wrong value lable

### ISSUE THREAD

**Issue by StephaneSeguin** [rappen/FetchXMLBuilder#965]
The emails with the Status Reason "Sent" are shown as "Cancelled" in the Fetch Query result.

![image](https://github.com/rappen/FetchXMLBuilder/assets/11836747/3ae04e74-b577-45c6-b328-2a25d4f8267e)

![image](https://github.com/rappen/FetchXMLBuilder/assets/11836747/3536f45d-22bf-430f-9496-7d3856c16978)

**Comment by rappen** [comment]
That sounds weird... 
I'll try to reproduce that issue.

**Comment by rappen** [comment]
I wasn't possible to reproduce your issue, sorry.
I'll close this issue now, but please reopen it if you have more info for me!
