### ISSUE TITLE
Results don't update when editing query

### ISSUE THREAD

**Issue by Roland80** [rappen/FetchXMLBuilder#967]
After I've created a query and execute it, I get the results I expect. 
If I then find out I want an extra column, I add it via 'Select Attributes' on the entity and execute the query again. The Results window then 'flashes'/refreshes, but the new column isn't shown.
If I choose Reset layout from the Columns 'menu' at the bottom of the Results window, the column suddenly shows up.

If I then select a column/attribute in the query and delete it, the column stays in the Results window until I've (again) chosen 'Reset layout'. 

It's almost as if there's a caching issue preventing the query results from properly updating.

This is on FetchXML Builder version 1.2023.8.2 in XRM Toolbox 1.2023.6..65

**Comment by COkerstrom** [comment]
I've found that cloning the tab resets the layout and shows the newly added fields.  Is there any other  (hopefully easier) techniques for clearing the layout feature and getting the full results?

Thanks
