### ISSUE TITLE
Error when loading metadata in larger environments (timeout?)

### ISSUE THREAD

**Issue by KenT185** [rappen/FetchXMLBuilder#971]
The error occurs when opening FetchXML and loading metadata. The "Reloaded Metadata into the cache..." progress indicator is displayed, and after approximately 8 minutes, the following error occurs. Subsequently, it becomes impossible to use the tool as none of the buttons are responsive.

I can reproduce this error only in environments with a large number of components. In smaller environments, the tool works flawlessly. Is it possible to fix this issue in larger environments, or are there CRM limitations that cause it?

---
```
System.Net.WebException:
The remote server returned an error: (502) Bad Gateway.
System
- System.Net.HttpWebRequest.GetResponse()
- System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
```

---
- XrmToolBox Version: 1.2023.9.66
- FetchXML Builder Version: 1.2023.8.2
- DB Version: 9.2.23082.184
- Deployment: Online

**Comment by rappen** [comment]
I've never heard this type of issue, can you check your settings?

![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/7a92d1cf-1e5a-4eeb-9fdf-ae7c181cd4b6)

**Comment by rappen** [comment]
Please reopen if you have more info.
