### ISSUE TITLE
Bug: Issue using filter in linked entity.

### ISSUE THREAD

**Issue by sabin-sharma** [rappen/FetchXMLBuilder#972]
Scenario:  Add the link entity and use the filter with two condition in the link entity. 

Issue: If the condition's attribute exists in both the main entity and the link entity then it works fine. If the attribute is only in the link entity  and does not exists in the main entity it throws error.

Error: 'Account' entity doesn't contain attribute with Name = 'new_exclude' and NameMapping = 'Logical'.

Example.

Say 'new_exclude' attribute exists in Contact table but not in Account and we would like to filter record based on the value of this attribute.

### FetchXML that generates error.  
```
<fetch>
  <entity name="account">
    <attribute name="name" />
    <link-entity name="contact" from="parentcustomerid" to="accountid" link-type="inner" alias="contact">
      <attribute name="fullname" />
      <filter>
        <condition attribute="statecode" operator="eq" value="0" />
        <condition attribute="new_exclude" operator="eq" value="1" />
      </filter>
    </link-entity>
  </entity>
</fetch>
```

### In order to make above FetchXML work we have to add another filter as shown below.
```
<fetch>
  <entity name="account">
    <attribute name="name" />
    <link-entity name="contact" from="parentcustomerid" to="accountid" link-type="inner" alias="contact">
      <attribute name="fullname" />
      <filter>
        <condition attribute="statecode" operator="eq" value="0" />
      </filter>
      <filter>
        <condition attribute="new_exclude" operator="eq" value="1" />
      </filter>
    </link-entity>
  </entity>
</fetch>
```
---
- Deployment: Online
- DB Version: 9.2.23091.160
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.2.64
- Tool Version: 1.2023.8.2

**Comment by rappen** [comment]
I really can't reproduce your issue...
I created this one, and there are no issues.

```xml
<fetch>
  <entity name='account'>
    <attribute name='name' />
    <link-entity name='contact' from='parentcustomerid' to='accountid' alias='contact'>
      <attribute name='fullname' />
      <filter>
        <condition attribute='lastname' operator='not-null' />
        <condition attribute='firstname' operator='not-null' />
      </filter>
    </link-entity>
  </entity>
</fetch>
```

Can you reproduce it now?
Any more info for me?

**Comment by rappen** [comment]
No response. Closing this issue, please reopen if you have any feedback!
