### ISSUE TITLE
Issue with Repository

### ISSUE THREAD

**Issue by CFITire** [rappen/FetchXMLBuilder#987]
Hi all, I'm trying to install FetchXML Builder and am getting this error

could not load file or assembly 'xrmtoolbox.pluginsstore version=1.2022, 10.58 culture=neutral pulickeytoken=null or one of it's dependencies. the system cannot find the file specified

Anyone come across this before?

**Comment by ingerAH-PP** [comment]
I am experiencing the same issue with this tool specifically. 
I am using the latest versions of XrmToolbox and have installed the latest version of FetchXMLBuilder.

XrmToolbox: v1.2023.10.67
FetchXMLBuilder: 1.2023.8.2

**Comment by CFITire** [comment]
For what it's worth I deleted the plugin for it from  appdata and then downloaded version 1.2021.4.4 and it worked fine.

**Comment by ingerAH-PP** [comment]
Great, thanks! I will try installing that version. 
I'll add that I have the same issue with Bulk Data Updater, so I will try a previous version of that plugin as well.

**Comment by ingerAH-PP** [comment]
The Bulk Data Updater version that works for me is: 1.2019.12.1

**Comment by ingerAH-PP** [comment]
And CRM version is 9.2(.23101.230) if that is useful information to fix the issue

**Comment by rappen** [comment]
Use latest version, if you have an issue regarding PluginsStore, find how we can temporary solution:
https://jonasr.app/missing-xrmtoolbox-pluginsstore/

**Comment by ingerAH-PP** [comment]
Thanks! That solved the issue
