### ISSUE TITLE
Installation failing on New PC with XrmToolBox.PluginsStore, Version=1.2022.10.58, Culture=nutral, PublicKeyToken=null"

### ISSUE THREAD

**Issue by suduko-tom** [rappen/FetchXMLBuilder#992]
As per the discussions - 

Hi, not sure why this is happening, but when I click the tool I get "Could not load file or assembly 'XrmToolBox.PluginsStore, Version=1.2022.10.58, Culture=nutral, PublicKeyToken=null"... This is a new installation of XrmToolBox (just downloaded, first run), went to store and downloaded and installed the FetchXML Builder and get that error when trying to use it. Close app and reopen, still get the error. Ran the XrmTooBox as Admin, still get the error. Thanks!

I am also experiencing the same on new Windows 11 PC with new installation of XRM Toolbox.

**Comment by LucX4** [comment]
Facing same issue in Windows 11 with a fresh installation.

**Comment by viavn** [comment]
Take a look into this one: https://github.com/rappen/FetchXMLBuilder/issues/987#issuecomment-1793737591
Solved to me.

**Comment by rappen** [comment]
I'm sorry for these issues... I blame Tanguy 😉
I will release a new version of all my tools, unfortunately I'm quite busy these days. I'll try!
I'll close this issue, I assume that link solves it, for now.
https://jonasr.app/missing-xrmtoolbox-pluginsstore/
